### ISSUE TITLE
Additional "de-telstra" options

### ISSUE THREAD

**Issue by juzman** [seud0nym/tch-gui-unhide#1]
I currently have a DJA0231 and was running the lates 0543 test firmware, but have rolled back to 18.1.c.0514-950-RB and re-rooted it.

Have ran the de-telstra script and tch-gui-unhide-DJA0231-18.1.c.0514, however thought of a couple little additional things to add maybe to the "de-telstra" script.

```
# Disable lotagent
/etc/init.d/lotagent stop
/etc/init.d/lotagent disable

# Remove Telstra NTP
uci del_list system.ntp.server=chronos.ntp.telstra.net
uci del_list system.ntp.server=chronos1.ntp.telstra.net
uci commit
/etc/init.d/sysntpd restart

# Disable LTE Doctor
SRV_ltedoctor=0

if [ "$(uci -q get ltedoctor.config.enabled)" -eq "1" ]
then
  echo [$SCRIPT]: Disabling LTE Doctor
  uci set ltedoctor.config.enabled='0'
  uci commit ltedoctor
  /etc/init.d/lte-doctor-logger stop
  /etc/init.d/lte-doctor-logger disable
  SRV_ltedoctor=$(( $SRV_ltedoctor + 1 ))
else
  echo [$SCRIPT]: LTE Doctor already disabled
fi

# Disable UPnP (https://www.forbes.com/sites/andygreenberg/2013/01/29/disable-a-protocol-called-upnp-on-your-router-now-to-avoid-a-serious-set-of-security-bugs/#12054ae876b4)
SRV_upnpd=0

if [ "$(uci get upnpd.config.enable_natpmp)" = '1' -a "$(uci get upnpd.config.enable_upnp)" = '1' ]
then
  echo [$SCRIPT]: Disabling UPnP
  uci set upnpd.config.enable_natpmp='0'
  uci set upnpd.config.enable_upnp='0'
  uci commit upnpd
  SRV_upnpd=$(( $SRV_upnpd + 1 ))
else
  echo [$SCRIPT]: UPnP already disabled
fi
```

Not sure if this helps, but disabling the power saving too?

```
pwrctl config --cpuspeed 0
pwrctl config --wait off
pwrctl config --ethapd off
pwrctl config --eee off
pwrctl config --autogreeen off
```

**Comment by juzman** [comment]
It's currently only a test firmware at the moment and still a little buggy with Geo filters and extras in DumaOS.

I can get you a copy, or wait until we've ironed out the bugs and get the next build.

**Comment by seud0nym** [comment]
If it is not going to be released, then no. I just wanted to get ahead of developing a new unhide script to deal with a new version.

I am about to start looking at changes to de-telstra, and I have a couple of questions for you:

- Do you know what lotagent is/does? I had assumed it was something to do with QoS, and therefore should it really be disabled?
- Isn't ltedoctor used by the 4G backup? I think it is what provides the Diagnostics tab on the Mobile card.

The problem with disabling samba is that it then breaks the GUI - you can't enable file sharing at all.

I agree with your suggestion of disabling/enabling services. I am thinking of an option for each service, which has probably 3 options: on/off/unchanged with the default being unchanged, so it just leaves it as is.

**Comment by juzman** [comment]
> If it is not going to be released, then no. I just wanted to get ahead of developing a new unhide script to deal with a new version.

No worries, when I get a new final build I will let you know. :)

> I am about to start looking at changes to de-telstra, and I have a couple of questions for you:
> 
> * Do you know what lotagent is/does? I had assumed it was something to do with QoS, and therefore should it really be disabled?
> * Isn't ltedoctor used by the 4G backup? I think it is what provides the Diagnostics tab on the Mobile card.

I believe lotagent has something to do with logging and sending it off.

I have ltedoctor disabled and the only thing I don't have on the diagnostic tab is "No signal quality history available for the selected period". However I still have live Status/Signal Quality/Operator Info and Cell Info.

> The problem with disabling samba is that it then breaks the GUI - you can't enable file sharing at all.
> 
> I agree with your suggestion of disabling/enabling services. I am thinking of an option for each service, which has probably 3 options: on/off/unchanged with the default being unchanged, so it just leaves it as is.

Ah, I didn't know about it breaking the GUI disabling Samba (for me personally I don't need file sharing as I have a NAS anyway).

The services with on/off/default sounds good. :)

**Comment by juzman** [comment]
I now have 18.1.c.0543-950-RA final build if you would like a copy of the .rbi file?

**Comment by seud0nym** [comment]
Yes, please. 

What is the difference between the -RA and the usual -RB?

**Comment by juzman** [comment]
http://fwstore.bdms.telstra.net/Technicolor_vcnt-a_18.1.c.0543-950-RA/vcnt-a_18.1.c.0543-950-RA.rbi

Honestly, I wouldn't a clue. Looking at it I am guessing it's just a naming thing. However I have sent of a query to the team to clarify.

18.1.c.0215-950-RA (BASE)
18.1.c.0241-950-RA (MR1)
18.1.c.0283-950-RA (MR2.1)
18.1.c.0347-950-RC (MR3.6)
18.1.c.0384-950-RB (MR4.1)
18.1.c.0443-950-RA (MR 5.1)
18.1.c.0443-950-RB (MR 5.2)
18.1.c.0462-950-RA (MR 5.3)
18.1.c.0462-950-RB (MR 5.4)
18.1.c.0514-950-RB (MR 5.3)

etc etc

**Comment by seud0nym** [comment]
Help text from new version (run on my test TG800vac):

```
Syntax: ./de-telstra <options>
Optional parameters:
 -h u|d|s|<hostname>
    where u            Leave hostname unchanged (Default)
          d            Set the hostname to TG800vac
          s            Set the hostname to TG800vac-CPxxxxxxxx
          <hostname>   Use the specified hostname
 -d u|g|<domainname>
    where u            Leave domain name unchanged (Default)
          g            Set the domain name to gateway
          <domainname> Set the domain name to <domainname>
 -n u|a|c|g|f|o|<n.n.n.n>
    where u            Leave DNS servers unchanged (Default)
          a            Automatically use the DNS servers from the ISP (device default)
          c            Set the DNS servers to Cloudflare
          g            Set the DNS servers to Google
          f            Set the DNS servers to OpenDNS Family Shield
          o            Set the DNS servers to OpenDNS
          <n.n.n.n>    Set the DNS servers to 1 or 2 comma-separated IPv4 addresses (e.g. 8.8.8.8,1.1.1.1)
 -a u|y|n
    where u            Leave ALGs unchanged (Default)
          y            Enable ALGs (device default)
          n            Disable ALGs (except SIP if telephony enabled)
 -c u|y|n
    where u            Leave Content Sharing unchanged (Default)
          y            Enable Content Sharing (device default)
          n            Disable Content Sharing
 -f u|y|n
    where u            Leave File Sharing unchanged (Default)
          y            Enable File Sharing (device default)
          n            Disable File Sharing
 -p u|y|n
    where u            Leave power saving unchanged (Default)
          y            Enable power saving (device default)
          n            Disable power saving
 -r u|y|n
    where u            Leave Printer Sharing unchanged (Default)
          y            Enable Printer Sharing (device default)
          n            Disable Printer Sharing
 -t u|y|n
    where u            Leave Telephony (mmpbx) unchanged (Default)
          y            Enable the telephony service (device default)
          n            Disable the telephony service
 -u u|y|n
    where u            Leave UPnP unchanged (Default)
          y            Enable the UPnP service (device default)
          n            Disable the UPnP service
 -A                    Equivalent to: -h d -d g -n c -a n -f n -p n
 -S                    Equivalent to: -h s -d g -n c -a n -f n -p n
```
Sample output:
```
[de-telstra]: Applying default hardening rules...
[de-telstra]: - Checking SSH access
[de-telstra]: - authorized_keys already replaced /etc/dropbear/authorized_keys
[de-telstra]: - dropbear re-configuration already completed
[de-telstra]: - CWMP already disabled
[de-telstra]: - Telstra monitoring already disabled
[de-telstra]: - Telstra AIR already removed
[de-telstra]: - Telstra NTP servers already removed
[de-telstra]: - lotagent already disabled
[de-telstra]: - Web GUI default user access already removed
[de-telstra]: Host name is already test
[de-telstra]: Domain name unchanged [gateway]
[de-telstra]: ISP peer DNS unchanged [Disabled]
[de-telstra]: DNS Servers unchanged [ 1.1.1.1 1.0.0.1 ]
[de-telstra]: Content sharing unchanged [Disabled]
[de-telstra]: Printer sharing unchanged [Disabled]
[de-telstra]: File sharing unchanged [Disabled]
[de-telstra]: Telephony unchanged [Enabled]
[de-telstra]: FTP ALG unchanged [Disabled]
[de-telstra]: TFTP ALG unchanged [Disabled]
[de-telstra]: SNMP ALG unchanged [Disabled]
[de-telstra]: PPTP ALG unchanged [Disabled]
[de-telstra]: SIP ALG left enabled because Telephony enabled
[de-telstra]: IRC ALG unchanged [Disabled]
[de-telstra]: AMANDA ALG unchanged [Disabled]
[de-telstra]: RTSP ALG unchanged [Disabled]
[de-telstra]: UPnP unchanged [UPnP Disabled NAT-PMP Disabled]
[de-telstra]: Power saving settings unchanged [Enabled]
[de-telstra]: Applying required service changes...
[de-telstra]: Removing packages that are no longer required
No packages removed.
[de-telstra]: Done!
[de-telstra]: NOTE: If you haven't changed the root password, you should do it now...
```

**Comment by juzman** [comment]
Oh, wow that looks awesome! Easy to disable everything you don't need, and setup DNS too (I use adguard), so having option to do -n x.x.x.x,x.x.x.x is great.

**Comment by seud0nym** [comment]
Yes, the script is re-runnable as many times as you wish.

I have just done the release.
