### ISSUE TITLE
Broadband Information Bug

### ISSUE THREAD

**Issue by juzman** [seud0nym/tch-gui-unhide#10]
If logging into 192.168.0.1 and clicking on "Broadband", the Connection Information shows:

`Status
IPv4 disconnected
IPv6 connected
Uptime
06:07:42
Data Transfered
18.15 MB(Sent)
1.08 GB(Received)
IPv4 Address
0.0.0.0
Primary DNS
0.0.0.0
Secondary DNS
0.0.0.0
IPv6 Address
2001:8004:xxxxxx
IPv6 DNS server
2001:8004:xxxxxx
2001:8004:xxxxxx`

However if I go to Advanced, then clicking the settings icon on "Internet Access" it shows:

IPv6 (toggled off)

IPv4 address
101.xxxxxx
Gateway
101.xxxxx
DNS servers
176.103.130.130,176.103.130.131

Not sure where the main Broadband page is getting the IPv6 connection details from, and why it isn't showing the IPv4 stuff, haha.

**Comment by seud0nym** [comment]
I don't do anything at all with the Basic screens (except change the theme). Personally, I bypass them and always just go straight into the advanced screen (by bookmarking http://192.168.0.1/gateway.lp)

Are you sure you the 4g backup is not connected? I have just connected via mobile and I am seeing similar to what you report...

**Comment by juzman** [comment]
I didn't think you did touch any basic screen stuff (except theme), and I usually go straight to Advanced too.

Not connected to to the 4G backup, as under Broadband:

DSL Status: Up
DSL Enabled: On
DSL Uptime: 13 minutes 35 seconds
DSL Type: VDSL2
DSL Mode: Fast

Says only 13 minutes, as I rebooted the modem just in case the basic broadband page was having issues - logged back in and still showing no IPv4 etc on basic and only IPv6 haha.

**Comment by seud0nym** [comment]
I am going to close this one, because I think it is more a configuration issue than a bug.

**Comment by juzman** [comment]
Sorry to bother you with this one @seud0nym - I've been testing this.

If I go to http://192.168.0.1/gateway.lp and go into Mobile, I have "Mobile Only Mode" disabled, and "Enabled" disabled.

Currently connected to FTTN/DSL and have connection. If I tick "Enabled" and save, the light goes red and it switches to 4G backup, even though "Mobile Only Mode" is turned off.

I think this is where the IPv4/IPv6 stuff is going funky, as it is switching to Mobile Mode but still on the DSL link too.

**Comment by juzman** [comment]
Just an update. Still have 4G disabled so it's on the FTTN service, I have all the phone services etc disabled too.

Back of modem: Wi-Fi, ONLINE and WAN green. Front of modem: red.

So I am guessing the modem is "seeing" something not working, and showing the red status light on front (usually green when on fixed line). I have no idea what the modem is doing, but I will simply ignore the lights :P

**Comment by seud0nym** [comment]
It doesn't sound very happy. I would be inclined to reset-to-factory-defaults and reconfigure from scratch.
