### ISSUE TITLE
Disable preventDNSRebind in webUI

### ISSUE THREAD

**Issue by shermanx** [seud0nym/tch-gui-unhide#104]
Hi seud0nym

I'm trying to use a reverse proxy to access my router from wan, but got this error in the nginx log, I know it's a security feature to prevent attacks, but how may I disable this if I need it that way? I tried to add the proxy url/ip to the server_name field in nginx.conf but still didn't work.

Thanks.

Wed Jul  6 21:53:44 2022 daemon.err nginx[6901]: 2022/07/06 21:53:44 [error] 6908#0: *20 [lua] sessionmgr.lua:251: preventDNSRebind(): HTTP Host header does not refer to us, client: 192.168.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "XXXXXXXX", referrer: "http://XXXXXXXX/gateway.lp"

**Comment by seud0nym** [comment]
Looking at the code, Dynamic DNS host names should just work. Otherwise, you could add XXXXXXXX into /etc/config/dhcp in the lan dnsmasq config as a `option hostname XXXXXXXX`.

Wouldn't it be easier to just set up permanent remote access? (It is only permanent until a reboot, however.)
