### ISSUE TITLE
Option for auto firmware update - Technicolor DNA0332TLS (VCNT-8)

### ISSUE THREAD

**Issue by s12321** [seud0nym/tch-gui-unhide#105]
Will there be an option to turn off auto update? I've found the following in /etc/config/system, but i cannot in the ui. 

> config fwupgrade 'fwupgrade'
        option keeprebootingonlybank '0'
        option maxbootattempts '1'
        option switchbacktofailedbank '0'

does this mean auto update on or off ?

**Comment by seud0nym** [comment]
Firmware is auto-updated through CWMP. 

If you have run `de-telstra` with the default options, CWMP is completely removed from the device, and auto-updates can never happen.

If you haven't run `de-telstra` or have run it with the `-kc` or `-kT` options, then you can disable CWMP through the card in the GUI. Or you can run the following commands:
```
 uci set cwmpd.cwmpd_config.state='0'
 uci commit cwmpd
```
There is a slight chance that some other Telstra modification will re-enable CWMP if you chose this route.

**Comment by s12321** [comment]
> There is a slight chance that some other Telstra modification will re-enable CWMP if you chose this route.

Thanks, that's my concern 😆 i hope there is no hidden backdoor with this embedded OS

**Comment by seud0nym** [comment]
> that's my concern

If that is what you are worried about, run `de-tesltra` and it will remove the cwmpd package completely. It will also remove all the other Telstra monitoring and "phoning home" packages.

**Comment by s12321** [comment]
Thanks 💯 
Is `de-telstra` write into the bank (firmware)? 
have you try this - if doing a hard reset the machine after `de-telstra`, will all the modules come back and need to root again?

**Comment by seud0nym** [comment]
> Is `de-telstra` write into the bank (firmware)?

No. This is not possible on these devices.

> if doing a hard reset the machine after `de-telstra`, will all the modules come back and need to root again?

Yes. But don't do a hard reset. If you need to reset, use the `reset-to-factory-defaults-with-root` script.
