### ISSUE TITLE
Bridge mode default gateway validation error

### ISSUE THREAD

**Issue by willat8** [seud0nym/tch-gui-unhide#106]
When swapping from routed mode to bridged mode in Local Network, the default gateway is set to empty.
I tried to then set it to a value on the subnet and received a validation error that prevented me from saving (I have IPv6 state off).
I was able to eventually get it to save by toggling on IPv6 state and then back off.

Not sure if this is a stock issue or not. Thanks for your time.

**Comment by seud0nym** [comment]
No, it looks like a bug I have introduced. Thanks for letting me know.

**Comment by seud0nym** [comment]
I forgot to add the issue number to the commit message, so it isn't cross-referenced here. The commit fix is https://github.com/seud0nym/tch-gui-unhide/commit/f4a394703a3becacf29abd443ccff85b74043703. I will do a release soon because there are a couple of other issues to fix.

**Comment by willat8** [comment]
All good, thank you.

**Comment by seud0nym** [comment]
Fixed in [Release 2022.07.28](https://github.com/seud0nym/tch-gui-unhide/releases/tag/2022.07.28)
