### ISSUE TITLE
QoS Bandwidth Shaping not working

### ISSUE THREAD

**Issue by RexyAU** [seud0nym/tch-gui-unhide#108]
Hello, I have recently installed your GUI and wanted to use the bandwidth shaping to fix bufferbloat but I am still getting near my sync rates of 50/20 in speedtests when the shaping is enabled. Is it not supported on the TG799VAC or am I missing something?

TG799VAC tch-gui-unhide Release 2022.08.20 for Firmware 17.2.0284-820-RA (Mint)

Thanks for your work and assistance. 

![Screenshot 2022-08-30 173745](https://user-images.githubusercontent.com/78418040/187385192-c8084e58-f939-474a-848b-9badce0e94e8.png)

![Screenshot 2022-08-30 173508](https://user-images.githubusercontent.com/78418040/187385224-b68fbb04-1b2a-442a-9b2c-f124db329b0f.png)

**Comment by seud0nym** [comment]
What does the following command return:
```
bqos status
```

**Comment by RexyAU** [comment]
> What does the following command return:
> 
> ```
> bqos status
> ```

Device br-lan:
/usr/sbin/tc: line 1: syntax error: unexpected word (expecting ")")
Device br-lan-ifb:
/usr/sbin/tc: line 1: syntax error: unexpected word (expecting ")")

**Comment by seud0nym** [comment]
Thanks. I think I know what the issue is. What does this return?
```
cat /proc/cpuinfo
``

**Comment by RexyAU** [comment]
> Thanks. I think I know what the issue is. What does this return?
> 
> ```
> cat /proc/cpuinfo
> ``
> ```

system type             : VANT-F
processor               : 0
cpu model               : Broadcom BMIPS4350 V8.0
BogoMIPS                : 397.31
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : no
hardware watchpoint     : no
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 1
cpu model               : Broadcom BMIPS4350 V8.0
BogoMIPS                : 409.60
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : no
hardware watchpoint     : no
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

**Comment by seud0nym** [comment]
The problem is that the bandwidth shaping relies on an executable called `tc` which is not included in the firmware. tch-gui-unhide installs it, but it looks like the version is incompatible with your board. 

Please post the results of:
```
cat /proc/socinfo
uname -a
```

And I will see if I can find a version for you to try (I don't have a TG799VAC to test on).

**Comment by RexyAU** [comment]
> The problem is that the bandwidth shaping relies on an executable called `tc` which is not included in the firmware. tch-gui-unhide installs it, but it looks like the version is incompatible with your board.
> 
> Please post the results of:
> 
> ```
> cat /proc/socinfo
> uname -a
> ```
> 
> And I will see if I can find a version for you to try (I don't have a TG799VAC to test on).

cat /proc/socinfo returns: cat: can't open '/proc/socinfo': No such file or directory

uname -a: Linux OpenWrt 3.4.11-rt19 #1 SMP PREEMPT Mon Mar 25 21:05:01 UTC 2019 mips GNU/Linux

**Comment by seud0nym** [comment]
Broadcom use both MIPS and ARM processors on their bcm63xx boards. The version included with tch-gui-unhide is the ARM version, but your device is MIPS.

We need to get the right version, then install it:
```
curl -kLo /tmp/tc_4.0.0-1_brcm63xx-tch.ipk https://github.com/fexofenadine/brcm63xx-tch/raw/master/base/tc_4.0.0-1_brcm63xx-tch.ipk
opkg --force-depends --force-reinstall install /tmp/tc_4.0.0-1_brcm63xx-tch.ipk
```

Not sure about those options. Hopefully they will force the correct version top be installed.

**Comment by RexyAU** [comment]
> Broadcom use both MIPS and ARM processors on their bcm63xx boards. The version included with tch-gui-unhide is the ARM version, but your device is MIPS.
> 
> We need to get the right version, then install it:
> 
> ```
> curl -kLo /tmp/tc_4.0.0-1_brcm63xx-tch.ipk https://github.com/fexofenadine/brcm63xx-tch/raw/master/base/tc_4.0.0-1_brcm63xx-tch.ipk
> opkg --force-depends --force-reinstall install /tmp/tc_4.0.0-1_brcm63xx-tch.ipk
> ```
> 
> Not sure about those options. Hopefully they will force the correct version top be installed.

After downloading tc_4.0.0-1_brcm63xx-tch.ipk to the /tmp folder I tried installing it with that second command and it said * pkg_init_from_file: Malformed package file. 

So I tried uninstalling the original tc package (which worked) that was installed with tch unhide and then installing the new one but it said "segmentation fault (core dumped)" then the modem crashed and rebooted.

**Comment by seud0nym** [comment]
Sorry about that. I found a reference to the fexofenadine repository in the Whirlpool thread, and it said that it contained MIPS packages compiled for the Technicolor devices.

I will see if I can find another source.

**Comment by RexyAU** [comment]
I found this website: http://archive.openwrt.org/snapshots/trunk/brcm63xx/generic/packages/base/

And it has tc_4.4.0-2_brcm63xx.ipk available to download on there, should I try this package?

**Comment by seud0nym** [comment]
Yes, please.

If you have the scripts extracted from the tch-gui-unhide release archive, you can run:
```
./reboot-on-coredump -off
```
before installing to prevent your device from rebooting if the install core dumps.

**Comment by RexyAU** [comment]
> Yes, please.
> 
> If you have the scripts extracted from the tch-gui-unhide release archive, you can run:
> 
> ```
> ./reboot-on-coredump -off
> ```
> 
> before installing to prevent your device from rebooting if the install core dumps.

Tried installing it and got this:

Unknown package 'tc'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for tc found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package tc.

**Comment by seud0nym** [comment]
You will need to add the brcm63xx as an allowed architecture:
```
echo 'arch brcm63xx 50'>>/etc/opkg.conf
```

**Comment by RexyAU** [comment]
> You will need to add the brcm63xx as an allowed architecture:
> 
> ```
> echo 'arch brcm63xx 50'>>/etc/opkg.conf
> ```

root@OpenWrt:/tmp# opkg install tc*
Installing tc (4.4.0-2) to root...
Configuring tc.

Looks like it installed

**Comment by seud0nym** [comment]
You will probably need to restart bqos, and then you will be able to check the status:
```
/etc/init.d/bqos restart
bqos status
```

**Comment by RexyAU** [comment]
> You will probably need to restart bqos, and then you will be able to check the status:
> 
> ```
> /etc/init.d/bqos restart
> bqos status
> ```


root@OpenWrt:~# /etc/init.d/bqos restart
root@OpenWrt:~# bqos status
Device br-lan:
/usr/sbin/bqos: line 133: tc: not found
Device br-lan-ifb:
/usr/sbin/bqos: line 133: tc: not found

**Comment by seud0nym** [comment]
Well, that's sad. Probably means incompatible kernel.

The archive was where I was going to look for `tc`, so I am not sure where to look next...

**Comment by RexyAU** [comment]
> Well, that's sad. Probably means incompatible kernel.
> 
> The archive was where I was going to look for `tc`, so I am not sure where to look next...

GOOD NEWS!

Its all working. I found another here and installed it: https://archive.openwrt.org/chaos_calmer/15.05.1/brcm63xx/generic/packages/base/tc_4.0.0-1_brcm63xx.ipk

I set the shaper to 35mbps down and 10mbps up
![Screenshot 2022-09-01 174048](https://user-images.githubusercontent.com/78418040/187865461-fa11c849-6bb8-40e3-b8ee-d8aa87af5936.png)

**Comment by RexyAU** [comment]
I set the shaper to 47mbps/17mbps and now get this result:

![Screenshot 2022-09-01 180130](https://user-images.githubusercontent.com/78418040/187869637-6dff9e02-cb50-4836-8535-17e9c4d47ca5.png)

**Comment by seud0nym** [comment]
> It's all working.

That is great news. A+ for buffer bloat is a great result.

Thanks for finding and trying out those packages. I will fix tch-gui-unhide so that it installs the correct package depending on CPU.

**Comment by RexyAU** [comment]
> > It's all working.
> 
> That is great news. A+ for buffer bloat is a great result.
> 
> Thanks for finding and trying out those packages. I will fix tch-gui-unhide so that it installs the correct package depending on CPU.

All good, thanks for making tch-gui-unhide

Btw, would it be possible for you to add an Eco LED setting like in Ansuels GUI where only the status LED on the modem is green and the rest are off?

**Comment by seud0nym** [comment]
> Eco LED

I'll think about it, but LED handling is very different across different devices. The way that the Ansuel GUI does it doesn't really fit with the tch-gui-unhide approach.

**Comment by seud0nym** [comment]
I have done a pre-release for this fix:
https://github.com/seud0nym/tch-gui-unhide/releases/tag/2022.09.06
