### ISSUE TITLE
Feature Request - SMS Forwarding

### ISSUE THREAD

**Issue by kk246** [seud0nym/tch-gui-unhide#110]
Any chance to add sms forwarding as an option?
Given we already have an interface for receiving and sending SMSs;
Forwarding would be awesome, as well.

I have a sim in my router with a plan that has unlimited calls and sms;
And it's such a waste that I can't make calls or send sms, from my phone (as kind of line a second sim)

Adding the ability to make calls using the sim in the router would be swell as well.
(maybe that's already a built in option? ), given the original device could connect to dect wireless handsets.

as for receiving calls, thankfully, there's carrier call-forwarding.

**Comment by seud0nym** [comment]
@UncleSam1966 has an SMS forwarder script. You can find it here: https://github.com/UncleSam1966/tch-sms-fwder

Both tch-gui-unhide and de-telstra enable VoLTE, so if your SIM provider supports that, then you should be able to make/receive calls via an attached handset.

**Comment by kk246** [comment]
Thanks, I'll check out the forwarder script.

About the VOLTE, feature (not sure what that is).
Does it use the number on the sim card to make calls?

Or do you need a seperate VoIP account?

If can use the sim, how do I connect a VoIP client on phone or PC to make the call, if I didn't have a dect handset?

Appreciate the advice, thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by seud0nym** [comment]
VoLTE = Voice over LTE

I have never had a VoLTE-capable SIM, so I am guessing at the answers. You need something like a Telstra or Boost SIM. Other Telstra MVNO SIMs mostly don't have it enabled. I think Optus and Optus MVNOs do, but I don't really know.

It may be better to ask on the Whirlpool forum: https://forums.whirlpool.net.au/thread/9vxxl849

> Does it use the number on the sim card to make calls?

Yes, I _believe_ it uses the mobile number. 

> If can use the sim, how do I connect a VoIP client on phone or PC to make the call, if I didn't have a dect handset?

I _believe_ it is integrated to use a handset connected to the router. I don't think a VoIP client will work.

**Comment by kk246** [comment]
Does this service look like it has VoLTE?
FYI, I'm on Felix.

PS: I've found I got a panasonic DECT6 handset, so that part is all good.

![image](https://user-images.githubusercontent.com/10692617/190627920-ea4072c8-906c-4c00-a745-febf0dfe1744.png)

**Comment by seud0nym** [comment]
I guess so. I have only ever seen the VoLTE APLN as "sos" (for emergency calls only).

**Comment by kk246** [comment]
Can't say what I did in particular, Tried a bunch of stuff.
One of them made it work. It works now lol.
So, calls can work, even without a telstra sim.
