### ISSUE TITLE
DumaOS?

### ISSUE THREAD

**Issue by SmartBoy84** [seud0nym/tch-gui-unhide#111]
Any way to fix this (maybe uninstall `netduma` all together?)

> Installing terminfo (6.1-1) to root...
> Downloading https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/base/terminfo_6.1-1_arm_cortex-a9_neon.ipk
> Collected errors:
>  * check_data_file_clashes: Package terminfo wants to install file /usr/share/terminfo/a/ansi
>         But that file is already provided by package  * netduma
>  * check_data_file_clashes: Package terminfo wants to install file /usr/share/terminfo/d/dumb
>         But that file is already provided by package  * netduma
>  * check_data_file_clashes: Package terminfo wants to install file /usr/share/terminfo/l/linux
>         But that file is already provided by package  * netduma
>  * check_data_file_clashes: Package terminfo wants to install file /usr/share/terminfo/r/rxvt
>         But that file is already provided by package  * netduma
>  * check_data_file_clashes: Package terminfo wants to install file /usr/share/terminfo/r/rxvt-unicode
>         But that file is already provided by package  * netduma
>  * check_data_file_clashes: Package terminfo wants to install file /usr/share/terminfo/s/screen
>         But that file is already provided by package  * netduma
>  * check_data_file_clashes: Package terminfo wants to install file /usr/share/terminfo/v/vt100
>         But that file is already provided by package  * netduma
>  * check_data_file_clashes: Package terminfo wants to install file /usr/share/terminfo/v/vt102
>         But that file is already provided by package  * netduma
>  * check_data_file_clashes: Package terminfo wants to install file /usr/share/terminfo/x/xterm
>         But that file is already provided by package  * netduma
>  * check_data_file_clashes: Package terminfo wants to install file /usr/share/terminfo/x/xterm-256color
>         But that file is already provided by package  * netduma
>  * check_data_file_clashes: Package terminfo wants to install file /usr/share/terminfo/x/xterm-color
>         But that file is already provided by package  * netduma
>  * opkg_install_cmd: Cannot install package nano.

**Comment by seud0nym** [comment]
Use the `--force-overwrite` option to `opkg`.
