### ISSUE TITLE
Deleted a file

### ISSUE THREAD

**Issue by SmartBoy84** [seud0nym/tch-gui-unhide#112]
In my experimentation, I accidentely deleted a file;
Do you have the contents for `functions-tch.sh`?
Running 20.3.c.0389-MR20-RA

**Comment by seud0nym** [comment]
You can get a copy of any system files from the `/rom` directory, so just copy it back with:
```
cp /rom/lib/functions/functions-tch.sh /lib/functions/functions-tch.sh
```
