### ISSUE TITLE
Request: device bandwidth

### ISSUE THREAD

**Issue by OzKnight2013** [seud0nym/tch-gui-unhide#115]
Hi.
Thanks for all your hard work.

Is it possible to have the device bandwidth re-enabled? I know it wasn't accurate but I found it immensely useful to track down bandwidth hogs.

Cheers 😁

**Comment by seud0nym** [comment]
Maybe.

**Comment by seud0nym** [comment]
There is a new pre-release with the bandwidth monitor restored:

https://github.com/seud0nym/tch-gui-unhide/releases/tag/2022.11.16

**Comment by OzKnight2013** [comment]
Tested. Working on DJA0231. Legend. Thanks.
