### ISSUE TITLE
RADVD for IPv6

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#117]
I wonder if the SMG3 have the RADVD option for IPv6 as I'm unable to find that in the Local Network card? As I'm with Future Broadband and their best recommendation is use RADVD for IPv6 for LAN (Local Network). 

This is a back up modem I used for the last few days to test it out, which you can see in the screenshot. 

![Screenshot_20221121_015821](https://user-images.githubusercontent.com/45726972/204120993-89c9f8bb-f8a2-477c-afed-05a9fb6aabca.png)

**EDIT: I'm aware there is SLAAC + RA and future broadband does not use SLAAC. Only need the RA option.**

**Comment by seud0nym** [comment]
Not as far as I am aware, but I can't get to my SMG3 right now.

IPv6 address allocation is confusing, but my understanding is that addresses are sent by DHCPv6, or SLAAC, or both, and that SLAAC = RA. I could be wrong.

From looking at this Openwrt post https://forum.openwrt.org/t/what-happend-to-accept-ra-and-ip6slaac/121552, I would try those configurations. See if the first one works, if not set `noslaaconly` to 1 and try again. If not try the second option.

Let me know how you go. If one of them works, I will add an RA option for IPv6 to configure it that way.

**Comment by seud0nym** [comment]
I have gotten myself all confused. I have gone off and made some changes that allow setting of WAN IPv6 via RA only.

However, I have now reread your issue and realised that you are talking about local network. 

So, now I am really confused, because you said you were talking to Future Broadband about this issue. 

If your issue is LAN only, then what happens is that Future assign you a prefix that your router then uses to hand out IPv6 addresses to your LAN clients. Your router deals with handing out those addresses, not Future. You can use DHCPv6 or SLAAC (which uses Router Advertisement) or both. But it is your router doing it from the prefix range assigned by Future. Future doesn't hand out addresses to your LAN devices. 

Now,  I am not an expert on IPv6 by any means an I could be completely wrong, but from everything I have read, that seems to be the way it works. 

On the other hand, if you want your WAN IPv6 assigned by RA, then the changes I have made in the latest pre-release should work for you. You can update with this command:
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```

**Comment by jmytch** [comment]
I’ll leave this here;

https://ausgeek.net/viewtopic.php?p=317#p317

With FBB we are given WAN IPv6 and as well LAN IPv6  I believe are prefix.

Thanks, will try again tomorrow as setting up static ip with your latest release doesn’t do anything? Won’t even connect to internet. But updating your pre-release should fix the trick.

**Comment by seud0nym** [comment]
I would be surprised if it doesn't work. A Future Broadband user helped me correctly fix things for Future static IPv6, and I haven't changed anything (well, not until last night when I got confused about what you needed).

Just fill in the 3 static IPv6 fields on the Internet card with the address, gateway and prefix provided by Future. Address and prefix have to have their CIDR suffixes (/128 and /56 probably). 

On the Local Network card, set the prefix size to /64. You can turn off DHCPv6 if you want, but it all works just fine.

**Comment by jmytch** [comment]
![Screenshot 2022-11-29 123308](https://user-images.githubusercontent.com/45726972/204424526-10a04778-32a5-471b-b729-4d95cd0bb5cc.jpg)

Ok I have set up the SMG3 again today, and for some reason the Internet card was saying Service is down but the internet works. Is there any ways you can fix the Internet card for Static IP to show as Green? Like the screenshot shown, DSL already connected and consumed some downloads earlier! 

I'm trying to figure out the DNS part on SMG3, as I set the FBB DNS in the DNS card, and went to https://www.top10vpn.com/tools/what-is-my-dns-server/ and it only picks up Google DNS from the US for some reason that I did not put in the DNS card, and Auto Discover is disabled also.

Thirdly, I cannot use 4G Backup in WAN Sensing along with Static IP can I? Because whenever I have WAN Sensing enabled, it keep switching Static IP to DHCP automatically which is quite annoying so I had to disable WAN Sensing for now and see if you can sort this out or not possible?

Now lastly, when setting up Static IP in the internet card, the WAN IPv6 Address, and IPv6 LAN Prefix with CIDR "/126", I noticed the IPv6 gateway does not have CIDR at all? FBB have IPv6 gateway along with CIDR, eg 24x0:8x0:0:1a:0:x:0:9/126 (not real ip, as just changed it out)

**Comment by seud0nym** [comment]
> Is there any ways you can fix the Internet card for Static IP to show as Green?

Please post the result of this command:
```
transformer-cli get sys.class.xdsl.@line0.Status
```

This is the setting that the card checks to determine if the service is up or down.

 

> EDIT: I've solved it

Great!

> I cannot use 4G Backup in WAN Sensing along with Static IP can I?

I have been able to reproduce this, but I can't see where it is doing it. I will have to do more research.



> I noticed the IPv6 gateway does not have CIDR at all?

No. The Openwrt IPv6 configuration page for the static protocol says that the address and prefix are in CIDR notation, but not the gateway. I assume it derives it from the address.



> IPv6 LAN Prefix with CIDR "/126"

This looks wrong, and you should double check it. The prefix length is normally a /56. You won't be able to assign addresses to your LAN devices out of a /126.

**Comment by jmytch** [comment]
> Please post the result of this command:
> `transformer-cli get sys.class.xdsl.@line0.Status`

![Screenshot 2022-11-29 135435](https://user-images.githubusercontent.com/45726972/204434838-2f5af7fe-90db-4279-aeb7-915841827795.jpg)

Here is the result;

Bootloader: U-Boot 2019.07 (Aug 30 2022 - 10:00:47 +0000), Build: 5.04L.0
root@mymodem:~# transformer-cli get sys.class.xdsl.@line0.Status
sys.class.xdsl.@line0.Status [string] = Up

It says it is up and the Internet card isn't showing correctly.

> No. The Openwrt IPv6 configuration page for the static protocol says that the address and prefix are in CIDR notation, but not the gateway. I assume it derives it from the address.

Ah right, no problem. Even though internet is up so should be ok anyway.

>This looks wrong, and you should double check it. The prefix length is normally a /56. You won't be able to assign addresses to your LAN devices out of a /126.

Good catch, and yeah the /126 only belongs to WAN IPv6 Address, and with the LAN prefix, it is at /48 👍🏼

**Comment by seud0nym** [comment]
> [sys.class.xdsl.@line0.Status](mailto:sys.class.xdsl.@line0.Status) [string] = Up

Hmm. Just strange. What do these return?
```
transformer-cli get uci.network.interface.@wan.auto
transformer-cli get uci.network.interface.@wan.ifname
transformer-cli get uci.xdsl.xdsl.@dsl0.enabled
transformer-cli get sys.class.xdsl.@line0.Status
transformer-cli get sys.eth.port.@eth4.status
```

**Comment by jmytch** [comment]
> transformer-cli get uci.xdsl.xdsl.@dsl0.enabled

Gives Error

![Screenshot 2022-11-29 141101](https://user-images.githubusercontent.com/45726972/204436903-6d25fd90-ef47-4982-b1de-c73fc3945e3d.jpg)

Am connecting this over DSL though, so I don't think Ethernet is important as ethernet 4 port is connected to a CCTV, port 3 for Sonos, port 2 for Energy Monitoring Hub and Port 1 for my desktop PC.

**Comment by seud0nym** [comment]
Yes, I think it is that error that is causing the grief. All those settings are retrieved in a one block, but because `uci.xdsl.xdsl.@dsl0.enabled` is returning an error, they all fail. Because none of the values are returned, it defaults to the Down message on the card. Yes, you are correct that the xDSL card doesn't show for the same reason.

The reason I asked for the eth4 setting was just to make sure it wasn't throwing some weird error there. And, FYI, eth4=WAN Port, not LAN port 4.

**Comment by seud0nym** [comment]
I have just uploaded another pre-release that should fix the Internet card:
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```

**Comment by jmytch** [comment]
![Screenshot 2022-11-29 123308](https://user-images.githubusercontent.com/45726972/204442781-d8c60069-8c0e-4f50-84ca-f26737f33aca.jpg)
Yep your latest pre-release fixed the internet card as that one now shows up as Fixed Broadband online as that one is now solved. Appreciates it

**Comment by jmytch** [comment]
Also in the Local Network card in the Static Leases section, what does IPv6 Host ID means? When I tried entering just the MAC Address, Host-name and IPv4, then tried to save. It force me to input IPv6 Host ID as I have no idea what that is as never seen this before.

Need static leases so that it doesn't renew lease every 24 hours.

**Comment by seud0nym** [comment]
Oops! It is a new feature for allocating static IPv6 addresses. It is supposed to be optional. I have fixed it now.
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```
Thanks.

**Comment by jmytch** [comment]
> Thanks.

Oh no problem, and glad you fixed that. Now I can enter them without IPv6 Host ID. I don't think I need them do I? Renewing lease with LAN IP and MAC Address should remain to stay the same?

Only left is the WAN Sensing for Static IP connection, and that might be a little difficult since Smart Modem never came with Static IP unless rooting them to get that feature.

**Comment by seud0nym** [comment]
No, you don't need it. Ipv6 addresses are naturally sticky. 

Yes, you are correct. It could be difficult, because WAN sensing works on PPP and DHCP only by default. It might be a bigger job for a future release, if I can work it out. Permanent WWAN would probably work.
