### ISSUE TITLE
setting static ipv4 address not working?

### ISSUE THREAD

**Issue by legend069** [seud0nym/tch-gui-unhide#118]
hello,

following the guide here"https://www.techpowerup.com/forums/threads/guide-unlocking-and-modding-telstra-routers-technicolor-hardware.296503/"

recently gained root access and rap script. starting to setup everything 
trying to add a static ip address doesn't seem to work or do anything?
once entering in the details and clicking the "+" icon nothing happens 

reverted back with " ./tch-gui-unhide-20.3.c -r"
tried to set static IP and loaded fine.

ran "./tch-gui-unhide" again went to try added another static IP and same thing nothing happens.

think i'll just need to revert back set all the static IP addresses.

**Comment by seud0nym** [comment]
There is a bug in the 2022.11.01 release that broke static IP leases. It is fixed in pre-release 2022.11.07, which you can download manually from here: https://github.com/seud0nym/tch-gui-unhide/releases/tag/2022.11.07

Otherwise you can run this command on your device to download the latest pre-release automatically:
```
curl -skL https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/get | sh -s -- -p
```

**Comment by legend069** [comment]
Oh awesome thanks.

I'm still trying to figure out the UI and all ect.

Is there a log somewhere so I can view all traffic/firewall rules?

**Comment by seud0nym** [comment]
You can view (and edit some of) the rules in the tabs on the Firewall card. Most of the rules do not log (except I think DoS Protection), but you can enable logging for the Intrusion Protection rules.
