### ISSUE TITLE
Latest release bug

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#12]
Just a head up there is a bug in the latest release that I've found. 

Footer copyright for some reason shows 4 of them instead of 1. Not sure what caused this, maybe during the theme change. 
![Capture](https://user-images.githubusercontent.com/45726972/98463044-44896280-2204-11eb-894f-1010f460cd81.PNG)

With themes selection, I tested all the light/dark which works perfectly then revert back to Telstra branding, for some reason when selecting Telstra branding it like it complete frozen, and refreshing the page bring back that light blue theme along with visible icon and Telstra logo. Shouldn't Telstra branding have their own GUI or something

![Capture](https://user-images.githubusercontent.com/45726972/98463139-f759c080-2204-11eb-922d-68efab373600.PNG)
![Capture2](https://user-images.githubusercontent.com/45726972/98463141-f88aed80-2204-11eb-88fd-c1d213ad9549.PNG)

Also lastly I tried to use `./tch-gui-unhide-cards` with a number of 6 and h but it didnt hide it? 

`./tch-gui-unhide-cards 6 h` or is it suppose to be `./tch-gui-unhide-cards 6h` ?

**Comment by seud0nym** [comment]
Thanks for the report.

There is a bug in the handling of the `-T` option of `tch-gui-unhide` that causes the copyright to be updated each time it is run, when it should only be done when `-T` is not specified. You can fix the display by running `./tch-gui-unhide -y`. I will fix also the bug.

The "Telstra branding" option applies the Telstra logo and Telstra colours (blue) on top of the GUI changes that the script makes. When you select that theme, you cannot change the colour. It doesn't revert to the default Telstra GUI. There does seem to be a bug when you try and change icon visibility. I will have to look further into that one.

`./tch-gui-unhide-cards` is meant to be run interactively. It does not accept parameters for card number and visibility. Run it without options, select the card number and the visibility when prompted. When the display of the cards is the way you want it, enter `a`  at the prompt to apply the changes.

**Comment by jmytch** [comment]
Thank you for letting me know about the `./tch-gui-unhide-cards` part, I got it working in the end. Just have to choose the number, once chosen then select h or u then a to apply. Makes sense now and works good without issues 👍

**Comment by seud0nym** [comment]
Fixed in Release 2020.11.09
