### ISSUE TITLE
Instructions for Adblock Post Install Outdated?

### ISSUE THREAD

**Issue by TheBlueJester** [seud0nym/tch-gui-unhide#121]
Hi!

I'm running through the post install instructions for the tch-gui-unhide -x adblock script and the instructions for where to change settings seem to be incorrect for my GUI / device.

"Configure the IPv4 Primary DNS Server under Local Network to the local device (depending on your version of tch-gui-unhide, this will be "RSP/ISP DNS Servers", "Custom WAN DNS Servers", or the device variant (e.g. "DJA0230" or "DJA0231"))"
- I am not sure if this is done in the Local Network Menu under DHCP or if it's now under the DNS menu. So I've set both up with local.

"Configure your preferred DNS Servers under Internet Access"
- My Internet Access menu doesn't allow you to edit the DNS values. In this case there is no issue as the upstream DNS here is fine. But still, I am unable to follow this instruction.

"Enable DNS Intercept under Firewall (leave DNS Server Address blank)"
- I can't find anything like this in Firewall menu. 
- I've enabled DNS Hijacking under the DNS menu which seems to be the same / intended setting?

I can take screen-snips of the various menus/sub-menus if required/useful.

Thanks so much!

**Comment by seud0nym** [comment]
Hi. 

Thanks for the report. 

This should be fixed now. Hopefully it is clearer (and simpler).

On the DNS Configuration tab, you should add your preferred upstream DNS servers (like 8.8.8.8 or 1.1.1.1 or 9.9.9.9) as as Custom DNS Servers. If you have configured DNS Hijacking, then you do not have to set the DNS Servers on the Local Network screen.

**Comment by TheBlueJester** [comment]
Oh thank you! 
Very clear and easy to follow now 👍
