### ISSUE TITLE
GUI upgrade fails

### ISSUE THREAD

**Issue by willat8** [seud0nym/tch-gui-unhide#126]
Am receiving the following error when upgrading via the GUI on 18.1.c

```
set() failed: Upgrade already running?
13643 
```

**Comment by seud0nym** [comment]
Hi.

The upgrade checks for a running install process. The 13643 is the process ID that it found. You can confirm it with this command:
```
ps | grep '^13643'
```

Could it have been a failed previous upgrade attempt? There may be a lock file hanging around as well.

You can kill the old upgrade process and remove the lock file with:
```
kill 13643
lock -u /var/run/tch-gui-unhide.lck
[ -f /var/run/tch-gui-unhide.lck ] && rm /var/run/tch-gui-unhide.lck
```

and then re-run the above `ps` command to make sure that it has gone.

**Comment by willat8** [comment]
Unfortunately I've already done the upgrade via the command line.

However this happened with the last upgrade as well, and running on the command line succeeded both times.

**Comment by seud0nym** [comment]
I will change the GUI upgrade process so that it checks for an existing running process _before_ starting the upgrade.

**Comment by seud0nym** [comment]
Should be fixed in release 2023.02.02.

**Comment by willat8** [comment]
Thanks a lot. I've noticed the same behaviour when upgrading to 2023.02.02, but I assume it will work fine when upgrading to the next release?

**Comment by seud0nym** [comment]
Ah, no. I should be fixed now. I will have another look.

**Comment by willat8** [comment]
Is the logic for performing the upgrade in the GUI coming from the existing version, or the new version? I would assume existing, since the new version hadn't been applied yet.

**Comment by seud0nym** [comment]
Yes, you are correct that the check is in the new version. But I am concerned about how you are getting upgrade processes hanging around in the first place. I actually had it happen to me just now upgrading a Gen 3 - the previous upgrade was stuck on restarting the firewall. I need to work out how and why that is happening.

**Comment by seud0nym** [comment]
Another user reported the same issue on 18.1.c, and I have finally tracked it down. The Lua version on 18.1.c seems to behave differently to other FW versions (even though it reports the same version number). You can fix it with these commands:
```
sed -e "s/\('tch-gui-unhide-%s'\)\"/\1|grep -v pgrep\"/" -i /usr/share/transformer/mappings/rpc/gui.map
/etc/init.d/watchdog-tch stop
/etc/init.d/transformer restart
/etc/init.d/watchdog-tch start
```

**Comment by willat8** [comment]
Good find! Will apply and keep an eye on how future upgrades go.

**Comment by willat8** [comment]
It's working on today's release. Thanks.

**Comment by DrSpaldo** [comment]
I am not sure if this is worthy of another issue/thread. However, for the latest update 2023.05.16, I am getting the following error when trying to update:

```set() failed: Download of https://github.com/seud0nym/tch-gui-unhide/releases/latest/download/20.3.c.tar.gz FAILED (Response code=0)```

This is in the GUI update. I wasn't sure how to do the update via the command line, if there is a special command to update rather than the full install method?

**Comment by seud0nym** [comment]
That would normally indicate an internet connection failure or a DNS lookup failure.

To update via the command line, just run:
```
./tch-gui-unhide -U
```

Install and upgrade instructions can be found in the wiki:
https://github.com/seud0nym/tch-gui-unhide/wiki/Upgrading

**Comment by DrSpaldo** [comment]
Great, thanks @seud0nym
