### ISSUE TITLE
Remote Assistance not working using Static WAN

### ISSUE THREAD

**Issue by unclelez** [seud0nym/tch-gui-unhide#128]
Firmware Version | 20.3.c.0389-MR20-RA
tch-gui-unhide | 2022.12.31@16:22

Hi,

I’m having an issue getting getting remote assistance working, seems the remote assistance modal can’t detect the Static WAN address. The modal will detect the NATed Mobile WAN address

Thank you

![979209D5-254F-405F-BAC6-C4DFD284213A](https://user-images.githubusercontent.com/112058383/211414116-eb6f407d-131e-4410-9bc0-d2564b0f4249.jpeg)

![7A91CCD7-C594-4756-805A-33E0A14C847D](https://user-images.githubusercontent.com/112058383/211414131-b9708687-882f-48c2-a6e8-476ed7b71804.jpeg)

**Comment by seud0nym** [comment]
Hmm. Very strange. I can't actually reproduce this. And I can't see how it could happen. It uses the same source for the IP address for building the URL that it uses on the Internet Access card.

Can you try these commands:
```
transformer-cli get uci.web.assistance.@remote.interface
transformer-cli get uci.web.assistance.@remote.interface6
```

They should return `wan` and `wan6` respectively.Assuming they do, can you run these commands and verify that they match your external WAN IP address(es):
```
transformer-cli get rpc.network.interface.@wan.ipaddr
transformer-cli get rpc.network.interface.@wan6.ip6addr
```
 (They will return `wwan` and `wwan6` when running on 4G backup.)

**Comment by unclelez** [comment]
Hi,

Thank you for your time

The issue seems to have fixed itself. My IP address is now showing.

May I ask you two more questions?

1. Is it possible to unlock the forbidden APN's on WWAN so I can use my Optus sim?

2.  I'm using a  Static Fixed + Mobile Broadband configuration (no wan sensing), all my traffic is routing out the wan but the monitoring WAN Download and WAN Upload cards reflect the WWAN interface. Can they default them to the WAN interface instead?

![image](https://user-images.githubusercontent.com/112058383/211669659-d9bbd503-e010-42b8-af9d-390158f62348.png)

![image](https://user-images.githubusercontent.com/112058383/211670075-f0286fe0-08e6-4df0-b5ff-a228a1a6edf0.png)

**Comment by seud0nym** [comment]
> 1. Is it possible to unlock the forbidden APN's on WWAN so I can use my Optus sim?

I don't know that there any "forbidden" APN's. You can add telcos on the Network Operators tab, and there associated APN's on the Profiles tab.

> 2 I'm using a  Static Fixed + Mobile Broadband configuration (no wan sensing), all my traffic is routing out the wan but the monitoring WAN Download and WAN Upload cards reflect the WWAN interface. Can they default them to the WAN interface instead?

Hmm. I fixed the download volume quantity on the Broadband card so that it includes both, but I may have forgotten to do the same charts. I will have a look.

**Comment by seud0nym** [comment]
I have fixed the WAN Up/Down charts so that they show the combined WAN/WWAN throughput.

I have put a pre-release so that you can give it a go. Run these commands to download and apply the fixed version:
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```

**Comment by unclelez** [comment]
It worked.

Thank you very much for your help.

You have helped me resolve all my issues.

One last question, In Static IP mode with Mobile failover. Since it uses QoS is there any purpose to using WAN Supervision?

**Comment by seud0nym** [comment]
Thank you very much for the donation. It is much appreciated. 

You are correct, you can probably safely disable WAN Supervision.
