### ISSUE TITLE
VoIP on a 3rd party SIP client

### ISSUE THREAD

**Issue by SmartBoy84** [seud0nym/tch-gui-unhide#131]
This may sound extremely naive; have you been able to register a SIP client with the VoIP information on your router so that you can send/receive calls on that number?

More so, would it be possible to receive messages on that number?

**Comment by seud0nym** [comment]
Yes, we are using SIPtalk as our VoIP provider for our landline. 

For a regular SIP connection, you just add the SIP server details on the Telephony Global tab, and then define the SIP Profile on the Phone Numbers tab.

**Comment by seud0nym** [comment]
Sorry, I don't understand what you mean. What do you mean by: 

> stock SIP service

Are you talking about VoLTE?

**Comment by seud0nym** [comment]
Ah, that's not VoLTE.

I assume you are a Telstra client? I don't think it is possible. Pretty sure it wouldn't work if you aren't connected to the router, and you would have to disable Telephony.
