### ISSUE TITLE
Error in Web GUI: 2023.01.20

### ISSUE THREAD

**Issue by TheBlueJester** [seud0nym/tch-gui-unhide#133]
Howdy!

I've just tried out the new pre-release: 2023.01.20
Have a small issue to report: Web GUI Errors.

Hardware: DJA0230
Firmware: 20.3.c.0432-MR21-RA

Steps taken:
I overrode all the previous scripts in root with the new ones. Minus Xtras scripts.  
Ran de-telstra, no changes to the config.
Then ran tch-gui-unhide.

I have an error message on screen when using the Web GUI, details below.

Troubleshooting:
I tried running tch-gui-unhide-cards.
Options v, then s, then a.
No change. 
I did the same update procedure and steps on my other DJA0230 and there are no errors.

Extra Info:
The DJA0230 with the issues have the wireguard and samba Xtra scripts installed/running.

![image](https://user-images.githubusercontent.com/80931844/213611490-467171cf-4f7f-45ef-9ddf-f8ce2772a290.png)

Error shown on screen:

> /usr/lib/lua/web/taint.lua:280: bad argument #3 to 'format' (no value)
stack traceback:
	[string "/gateway.lp"]:32: in function <[string "/gateway.lp"]:32>
	[C]: in function 'format'
	/usr/lib/lua/web/taint.lua:280: in function 's'
	/www/lua/devicescard_helper.lua:21: in function 'getDevicesCardHTML'
	[string "009_Devices.lp"]:4: in function 'content'
	/usr/lib/lua/web/lp.lua:171: in function 'include'
	[string "/gateway.lp"]:32: in function <[string "/gateway.lp"]:32>
	[C]: in function 't'
	[string "/gateway.lp"]:32: in function 'content'
	/usr/lib/lua/web/web.lua:249: in function 'process'
	content_by_lua(nginx.conf:132):4: in function

**Comment by seud0nym** [comment]
Oops! The change to show inactive devices on the card broke the WireGuard extras script.

Thanks for letting me know. 

Please re-run:
```
./tch-gui-unhide -x wireguard
```

and that should fix it.

**Comment by TheBlueJester** [comment]
Yep, that's solved it!
Thanks! :D
