### ISSUE TITLE
USB issues

### ISSUE THREAD

**Issue by CoreyGreen** [seud0nym/tch-gui-unhide#134]
Hi, 

Thanks for everything, have got everything installed and running without too many problems. I'm just having a strange issue with USB drives. Was hoping to run adguard from usb but whenever I try and access the USB I get an issue regarding too many symbolic links. I've been troubleshooting it for a while now and am able to access the USB over winscp right up until the the GUI install and then get the same error. Not sure if it's something I've done wrong during the install or another issue. I've tried resetting the router and rooting again,  have reformatted multiple drives but am now a bit stuck. Wondering if you might have some ideas?

**Comment by legend069** [comment]
what directory are you going to access the USB drive?
`/tmp/run/mountd/sda1/` ?

**Comment by CoreyGreen** [comment]
Yeah /tmp/run/mountd/sda1. I was receiving errors when trying to install adguard on usb so then used winscp to try and access the directory to find out what was happening but no luck.

**Comment by legend069** [comment]
is the usb formatted with fat32 ?

i had adguard running directly on the device.(not using it now )

**Comment by seud0nym** [comment]
Can you tell me:

- what device;
- what firmware;
- the exact steps and commands that you ran (even things that you think might be unimportant);
- the exact error messages you got.

From Googling, it seems the most common reason is a link that points back to itself. I really can't think of anything that would cause this. None of the scripts use symbolic links.

**Comment by seud0nym** [comment]
I have finally tracked down what causes this error. The "Too many levels of symbolic links" error is a symptom, rather than being related to the cause. There was a bug in `de-telstra` that caused mounting of the USB stick to fail, that then caused that error message.

I have fixed the problem, and added some repair code.

You can get the fixed version of `de-telstra` using this command:
```
./de-telstra -U
```

Run it as you normally would and it will repair the issue. Make sure you remove the USB stick and the re-insert it.

**Comment by CoreyGreen** [comment]
Hey, thank so much for taking a look at this, really ppreaciate it and everything seems to working now. Apologies for not following up sooner, life got in the way a bit over the past month so haven't had a chance to have a look at it until now.

**Comment by jameselks** [comment]
I tried updating to the latest 2025.05.25 and I couldn't access the GUI. Then I had this issue. So I ended up installing using the automated method:
https://github.com/seud0nym/tch-gui-unhide/wiki/Before-Installing

Thought it would be worth posting here as it took me a while to figure it out.
