### ISSUE TITLE
Enhancement SSH via WWAN

### ISSUE THREAD

**Issue by unclelez** [seud0nym/tch-gui-unhide#136]
My sim card has a static IP, and I was hoping to be able to SSH into my router using it, but drop dear isn't configured to listen to that interface.

Are you able to add the WWAN interface to dropbear?

`
 4420 root      2484 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -j -p 192.168.0.1:22 -I 600 -K 300 -T 3

10647 root      2612 S    /usr/sbin/dropbear -F -P /var/run/dropbear.2.pid -j -p xx.xxx.xxx.xxx:22 -I 600 -K 300 -T 3

12838 root      3384 S    grep dropbear

19807 root      2484 S    /usr/sbin/dropbear -F -P /var/run/dropbear.2.pid -j -p xx.xxx.xxx.xxx:22 -I 600 -K 300 -T 3

24431 root      2612 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -j -p 192.168.0.1:22 -I 600 -K 300 -T 3`

**Comment by seud0nym** [comment]
The existing dropbear configuration on the System screen only deals with the WAN interface. It shouldn't be too difficult to add WWAN s well. 

I will have a look.

**Comment by seud0nym** [comment]
Hmm. It is a bit more complicated than I first thought. There are complexities with firewall rules if I just add another dropbear configuration for the WWAN interface.

It might be better (and much easier for me) to just give the option to use either WAN or WWAN for the external SSH connection.

Can you try this and make sure it works:
```
uci set dropbear.wan.Interface='wwan'
uci commit dropbear
/etc/init.d/dropbear restart
```

The other major concern that I have is that my understanding was that all mobile providers use CGNAT, so you might not be able to access it anyway...

**Comment by unclelez** [comment]
Thank you, I managed to get both working in dropbear

**Comment by seud0nym** [comment]
Do you mean that changing the interface worked?
