### ISSUE TITLE
Configure landing page

### ISSUE THREAD

**Issue by willat8** [seud0nym/tch-gui-unhide#139]
It would be nice to have either "home.lp" or "gateway.lp" configurable as the default landing page, to provide a more consistent experience across bridged (always gateway.lp) and router (always home.lp) modes. I've also noticed the URL in the browser gets rewritten to the IP address in bridged mode only- is that possible to prevent?

Thanks as always.

**Comment by seud0nym** [comment]
I tend to always bookmark the IP with gateway.lp, and name the bookmark as I want it, so it is always consistent. Also means I never noticed that it gets re-written.

The problem also is that home.lp isn't appropriate in bridged mode, so choosing it as a configuration option is problematic. The only way would be to force gateway.lp, so that the only way to get tot Basic mode is through the button on gateway.lp.

I will have a look and a think.

**Comment by willat8** [comment]
I have done the same, but often find myself reflexively typing the hostname in directly, especially on mobile. Thanks for considering the options.

**Comment by seud0nym** [comment]
Bridged mode isn't the issue that I thought it was (it always redirects from home.lp in bridged mode anyway).

If I use the hostname to get to a device rather than its IP address, I just get a `401 Authorisation Required` message. I'll have to look at that further.

**Comment by seud0nym** [comment]
I was using the fully qualified domain name instead of just the host name, which is why I was getting the `401`. I have modified `de-telstra` so that the FQDN is now a valid name.

**Comment by willat8** [comment]
Thank you :) will the redirect now use the original URL?

**Comment by seud0nym** [comment]
The redirects that used to go to `http://mymodem.modem` or `http://mygateway.gateway` will now go to `http://<your_host_name>.<your_domain_name>`. Is that what you mean?

**Comment by willat8** [comment]
With current tch-gui-unhide, I see the following (only for bridged devices, normal gateways work fine)

```har
{
  "log": {
    "entries": [
      {
        "request": {
          "bodySize": 0,
          "method": "GET",
          "url": "http://smbhost/",
          "httpVersion": "HTTP/1.1",
        },
        "response": {
          "status": 302,
          "statusText": "Moved Temporarily",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Server",
              "value": "nginx"
            },
            {
              "name": "Date",
              "value": "Fri, 17 Feb 2023 08:35:53 GMT"
            },
            {
              "name": "Content-Type",
              "value": "text/html"
            },
            {
              "name": "Content-Length",
              "value": "154"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Set-Cookie",
              "value": "sessionID=<snipped>; Path=/; HttpOnly"
            },
            {
              "name": "cache-control",
              "value": "no-cache"
            },
            {
              "name": "Content-Language",
              "value": "en-us"
            },
            {
              "name": "Location",
              "value": "http://192.168.0.9:80/gateway.lp"
            },
            {
              "name": "X-Frame-Options",
              "value": "SAMEORIGIN"
            },
            {
              "name": "Content-Security-Policy",
              "value": "default-src 'self';script-src 'self' 'unsafe-eval' 'unsafe-inline';style-src 'self' 'unsafe-inline'"
            },
            {
              "name": "Cache-Control",
              "value": "public, max-age=31536000"
            }
          ]
          "content": {
            "mimeType": "text/html",
            "size": 9142,
            "comment": "Response bodies are not included."
          },
          "redirectURL": "http://192.168.0.9:80/gateway.lp",
          "headersSize": 537,
          "bodySize": 9679
        },
        "time": 152,
        "_securityState": "insecure",
        "serverIPAddress": "192.168.0.9",
        "connection": "80"
      }
    ]
  }
}
```

Where the original hostname (smbhost) has been replaced with the IP address (192.168.0.9). This also happens if I browse `<hostname>.<domain>`.

I also notice that when using HTTPS, 404 is returned (on the bridged device only) and no redirect happens. I also get 404 if I try to browse straight to /gateway.lp. Maybe that's an 18.1 version thing?

**Comment by seud0nym** [comment]
Is `smbhost` the actual device host name, or is that an A or CNAME record (alias) defined in another DNS server?

**Comment by willat8** [comment]
It was set in de-telstra
```
  Host name                                -hsmbhost        smbhost
  Domain name                              -dlan            lan
```
And I have a static lease for it on my main DJA0230 (and define the same hostname there).

**Comment by seud0nym** [comment]
Thanks for that info.

The nginx redirect functionality is overridden in `/usr/lib/lua/web/sessioncontrol.lua` to always use an IP address. This is the associated comment:
```
--- override the ngx.redirect function to handle the case were the publicly used
-- ip and/or port are different from the ones actually used.
-- This happens for remote assistance and in cases traffic is redirected.
```

I don't think I want to play around with that and maybe break something...

**Comment by willat8** [comment]
Makes sense - thanks!

**Comment by legend069** [comment]
> The redirects that used to go to `http://mymodem.modem` or `http://mygateway.gateway` will now go to `http://<your_host_name>.<your_domain_name>`. Is that what you mean?

ooh nice, that redirect to ```http://mymodem.modem``` always bugged me

**Comment by willat8** [comment]
Working great on today's release, thanks @seud0nym!
