### ISSUE TITLE
enhancement request

### ISSUE THREAD

**Issue by unclelez** [seud0nym/tch-gui-unhide#140]
Hi and Thank you for your help.

I would like to see if you could add this feature or guide me to a workaround.

With the "reset-to-factory-defaults-with-root" script, is there a way to keep the mobile profiles & mobile operators config after reset?

Many thanks

**Comment by seud0nym** [comment]
I have added a new `-m` option that will restore mobile operators and profiles, and the linked WWAN profile.

You can update to the latest version before the next release is out with this command:
```
./reset-to-factory-defaults-with-root -U
```
