### ISSUE TITLE
0 Boosters Found

### ISSUE THREAD

**Issue by Peter-3126** [seud0nym/tch-gui-unhide#141]
I am using at DJA0231 as a controller and agent and a DJA0230 as a booster and agent. The DJA0231 WAN address is 192.168.0.X and DJA0231 LAN address is 192.168.3.1. LAN on controller is connected to LAN on booster. It is all working well and the Wi-Fi is being replicated on the booster. Wi-Fi works on controller and booster. It is just that the Wi-Fi tile on DJA0231 still has '0 Boosters found'. I have tried toggling the enable/disable boosters, but makes no difference.  I can live with like this, but others may have a similar issue... maybe there is an easy fix.

DJA0231 & DJA0230 config: Technicolor 2022 [tch-gui-unhide Release 2023.02.02 for Firmware 20.3.c.0432-MR21-RA (Egyptian Blue)]

![image](https://user-images.githubusercontent.com/74580531/219621371-382aa24a-9676-4c56-923a-4b31176867e9.png)

**Comment by seud0nym** [comment]
Why are you running your booster on a different subnet (192.168.3.x instead of 192.168.1.x)?

The usual configuration is to have the booster in the same subnet.

**Comment by seud0nym** [comment]
Sorry, I meant 192.168.3.x instead of 192.168.0.x?

**Comment by Peter-3126** [comment]
I am not using the DJA0231 (controller) as my main ISP gateway. My ISP requires VLAN tagging and neither the DJA0231 nor the DJA0230 supports VLAN tagging. My existing gateway (which supports VLAN tagging) is on the 192.168.0.x network. When I programmed the booster I did so with the command ./bridged-booster -i192.168.3.2 -g192.168.3.1  It all works, there is just no indication on the controller.

**Comment by seud0nym** [comment]
But you are still running the controller and the booster on different subnet, aren't you?

Anyway, you definitely _can_ do VLAN tagging on the DJA0231... It is one of the things that tch-gui-unhide exposes.

Click on the Broadband card, and on the Configuration tab under the heading "Internet Channel", set the "Using VLAN" switch to on. You can then enter your VLAN ID. You should first turn off WAN Sensing, as it does not play well with VLAN tagging.

I would try that first, and it will get rid of your double NAT problem, and hopefully fix this issue as well.

**Comment by Peter-3126** [comment]
Thanks for the quick response. I will try that ... I know it uses VLAN ID 2. The controller WAN port is on 192.168.0.x and LAN port on 192.168.3.1, the booster is 192.168.3.2 (same subnet). If I replace the existing gateway I will need to configure the VoIP phone as well. It is worth it to get rid of the double NAT. Thanks again.

**Comment by legend069** [comment]
> I am not using the DJA0231 (controller) as my main ISP gateway. My ISP requires VLAN tagging and neither the DJA0231 nor the DJA0230 supports VLAN tagging. My existing gateway (which supports VLAN tagging) is on the 192.168.0.x network. When I programmed the booster I did so with the command ./bridged-booster -i192.168.3.2 -g192.168.3.1 It all works, there is just no indication on the controller. The controller and booster LAN segment are both on the 192.168.3.x network, which means I have a double NAT happening. I don't have much choice if I cannot do VLAN tagging on the DJA0231.

hey mate, my isp required vlan tagging too and it works fine for me?
the backup internet still works as expected too
