### ISSUE TITLE
Chengelog?

### ISSUE THREAD

**Issue by SmartBoy84** [seud0nym/tch-gui-unhide#142]
Is there a changelog of what things were changed between firmware versions?
Is there any incentive for me to upgrade to the latest firmware?

**Comment by seud0nym** [comment]
Telstra does not publish a change log. I have a program that I run that can tell _what_ packages have changed between firmware versions, but not _why_ they were changed.

18.1.c.0241-950-RA to 18.1.c.0543-950-RA: https://whrl.pl/Rgbyv8
18.1.c.0543-950-RA to 18.1.c.0585-MR7.1-RA: https://whrl.pl/RgbF6Z
18.1.c.0514-950-RB to 18.1.c.0585-MR7.1-RA: https://whrl.pl/RgdCB8
20.3.c.0329-MR19-RB to 20.3.c.0389-MR20-RA: https://whrl.pl/RgmfTf
20.3.c.0389-MR20-RA to 20.3.c.0432-MR21-RA: https://whrl.pl/RgpLlZ
20.4.0319-MR0-RA to 20.4.0428-MR1-RA: https://whrl.pl/RgwKYp
