### ISSUE TITLE
SSH Authorized Keys

### ISSUE THREAD

**Issue by willat8** [seud0nym/tch-gui-unhide#143]
Since the latest release that lists SSH authorized keys, I notice there is a mysterious no-name key installed. Is this expected?

![Screenshot_20230224-155023](https://user-images.githubusercontent.com/2316013/221094983-e3ee3caa-8b23-419a-a761-43215d4d23bb.png)

**Comment by seud0nym** [comment]
There is a blank line in the file. I should have checked that de-telstra does, which is to write an empty line into the file to delete the default entries. *sigh*

You can safely delete it.

I will add a check for a blank line as the last record, and ignore it.

Sorry and thanks for reporting it.

**Comment by willat8** [comment]
Sounds good, thanks :).

**Comment by seud0nym** [comment]
Fixed in release 2023.03.23
