### ISSUE TITLE
Port forwarding stopped working suddenly

### ISSUE THREAD

**Issue by areographe** [seud0nym/tch-gui-unhide#144]
I'm new to using the DJA230 and to networking in general, but thanks for doing an amazing job with this software.

I set up the DJA230 in bridge mode when I moved from a property with HFC NBN connection to a FTTB vDSL connection, and kept using my old router, which was set up with port forwarding for transmission-daemon, navidrome and other services running on a raspberry pi. recently, i decided to switch to just using the DJA230 for everything, and gained root access / installed tch-gui-unhide.

I created port forwarding rules to match those on my old router, and tested them to confirm they were working. I was then able to quickly and easily set up a Dynamic DNS account, a Wireguard server and the Adblock software, but then when I tested whether certain ports were open, they were now closed. I deleted the port forwarding rules and recreated them, but now I can't seem to get any ports open or forwarded. My ISP is not using CG-NAT for my internet connection, I can access the services locally using the ports I've specified, and all port forwarding rules I've set use the same WAN and LAN port number, so I can't work out what's going wrong. 

Is there any log file you would recommend inspecting to try to work out what's happened?

Thanks in advance!

**Comment by areographe** [comment]
Interesting! I went into the "IP Tables" tab, selected "NAT (IPv4 ONLY)" and typed in the two port numbers I am currently forwarding, and there's 0 rules for either of them. In the web browser I Ctrl-F'd the port numbers on the full list of firewall rules and no results, so it looks like even though the "Port Forwarding" card says "2 Port Forwarding rules defined", the firewall rules don't seem to show it.

I'm using a DJA0230TLS with Firmware Version 20.3.c.0389-MR20-RA if that helps.

**Comment by seud0nym** [comment]
There is a bug I found on the Gen 3 that showed the same symptoms. 

Try running this command in PuTTY or whatever SSH client you are using:
```
/etc/init.d/firewall restart
```
Then recheck IP Tables.

**Comment by areographe** [comment]
I logged in with ssh and ran that command, but the command never exited, it just sat there for several minutes. I've rechecked the IP Tables tab, no change yet. I ran top in the ssh client and there are a handful of `/bin/sh /etc/rc.common /etc/init.d/firewall` processes, looks like around 3 or 4 of them.

**Comment by seud0nym** [comment]
Well, that means it could be a _different_ bug that I recently discovered. Do you have DNS Hijacking enabled? If so, disable it.

Then run this command:
```
kill $(pgrep -f /etc/init.d/firewall)
```
You may need to run it multiple times (until it says `you need to specify whom to kill`). Then restart the firewall and recheck to see if the port forwards are active.

Assuming that works, it would be helpful if (with DNS Hijacking still disabled) if you could try to define a new port forward and see if works. That will tell me if it is the port forwarding bug or the DNS Hijacking bug.

**Comment by areographe** [comment]
I did not have DNS Hijacking enabled. I ran that command twice until it had gave the desired response, but when I then ran `/etc/init.d/firewall restart`, the same thing happened - the command just hangs indefinitely (20+ minutes). I opened a second ssh connection and ran top to check if there are any firewall processes now:
```
11182 11181 root     S     3384   0%   0% /bin/sh /etc/rc.common /etc/init.d/firewall enabled
11323 24423 root     S     3384   0%   0% /bin/sh /etc/rc.common /etc/init.d/firewall restart
```
The port forwards still don't show up in the "IP Tables" tab, so I don't think they're active.

**Comment by seud0nym** [comment]
Well that is really annoying. I had this exact issue with firewall restart getting caught on a lock from firewall enabled. I had assumed that it was DNS Hijacking (although I couldn't work out how) because the problem went away when I disabled it.

In the directory where you extracted tch-gui-unhide, there is a script called `./ptree`. Can you please run it, and post the hierarchy of the processes where /etc/init.d/firewall is the child? Thanks.

**Comment by areographe** [comment]
I appreciate your help with this, it certainly is really annoying! Looks like the hierarchy is:

```
    1 root        S  3132   0% /sbin/procd
 3856 root        S  2832   0% ├─ /sbin/netifd
11140 root        S  3384   0% │  ├─ /bin/sh /sbin/hotplug-call iface
11181 root        S  3384   0% │  │  └─ /bin/sh /sbin/hotplug-call iface
11182 root        S  3384   0% │  │     └─ /bin/sh /etc/rc.common /etc/init.d/firewall enabled
11186 root        S  2260   0% │  │        └─ flock 1000
```
There's also about 7 `flock` processes sitting directly under `/sbin/procd`, not sure if that's relevant.

**Comment by seud0nym** [comment]
Thanks for that.

> There's also about 7 `flock` processes sitting directly under `/sbin/procd`, not sure if that's relevant.

Yes, it is relevant. They are what we actually need to kill. So, try:
```
kill $(pgrep -f flock)
```
Again, you may need to run it multiple times. Then restart the firewall. Hopefully it won't get hung up, and then recheck to see if the port forwards are active.

**Comment by areographe** [comment]
OK, so I tried that, restarting the firewall still hung seemingly indefinitely. I repeated the suggestion of killing `flock` and `/etc/init.d/firewall`, and this time I just ran `/etc/init.d/firewall` without the `restart` argument, and then backgrounded and resumed the process with Ctrl-Z and `bg`. Now, it seems that the port forwards are active, so that's promising. I'm just still not sure why it kept hanging when I tried to restart the firewall.

**Comment by areographe** [comment]
An interesting development: port forwarding worked correctly for a few days after that last post. However, today I needed to power off the router and restart it later in the day.

The two port forwarding rules I set are still visible in the 'Port Forwarding' tab, but when I go to the 'IP Tables' tab and set the 'NAT (IPv4 ONLY)' filter and search for either of the port numbers for the two rules, instead of 3 rules/chains I only see two rules (a TCP rule and a UDP rule) under the `Chain zone_wan_prerouting (0 references)` chain.

I might try following the steps from https://github.com/seud0nym/tch-gui-unhide/issues/144#issuecomment-1473108836 to see if that sets up the correct 3 rules in 'IP Tables'. I will update this thread with the results.

**Comment by seud0nym** [comment]
After making sure there are no `flock` processes running, you should then run this:
```
rm -f /var/lock/procd_firewall.lock
```
That is the actual file that the file descriptor refers to.

Then try restarting the firewall.

**Comment by areographe** [comment]
OK, I've done that. This time, instead of `/etc/init.d/firewall restart` hanging, it printed 145 lines of output and then exited seemingly normally. The firewall is now working and the port forwarding rules are in effect.

**Comment by areographe** [comment]
Thanks so much for this, I meant to close the issue but forgot - everything seems to be working even after a reboot, etc. I appreciate the assistance diagnosing and solving the problem.
