### ISSUE TITLE
cp: can't create '/www/docroot/font/fontawesome/fontawesome-webfont.eot': No such file or directory

### ISSUE THREAD

**Issue by fznx922** [seud0nym/tch-gui-unhide#145]
Hey guys 

when trying to install im getting this error and once the install finishes im just greeted with a page with the logo up top but no cards or any interface, if i click basic page it gives me a server500 error.  

already had nginx-gui running for a while now but wanted to swap over to your interface is this because im applying after this? 

is there any fix for this? or has it been seen before

cp: can't create '/www/docroot/font/fontawesome/fontawesome-webfont.eot': No such file or directory
cp: can't create '/www/docroot/font/fontawesome/fontawesome-webfont.woff': No such file or directory

thanks so much!

**Comment by seud0nym** [comment]
If you had tch-nginx-gui installed, you will have to reset to factory defaults _twice_ before you can install tch-gui-unhide.  You can use the `reset-to-factory-defaults-with-root` script to simplify that task.
