### ISSUE TITLE
DNS issue when running Wireguard server

### ISSUE THREAD

**Issue by areographe** [seud0nym/tch-gui-unhide#147]
Hi, thanks for helping with my previous issue. This one may simply be a mistake on my part in configuring something, but I am pretty sure I set everything up with the default configuration options on my DJA0230 device and don't remember tweaking anything.

When installing, I used `-x wireguard` to create a Wireguard-specific GUI card, installed the other packages, got the Wireguard server running using a `duckdns`-provided dynamic DNS service. I generated the .conf files and QR codes for my phone and laptop, set up both devices with the automatically generated config files, and then checked that the Wireguard card in the GUI read

```
VPN Server enabled
2 of 2 server peers active
```

Everything seemed to be working perfectly, except I then found I couldn't get through to any devices on my LAN, or get access to any domains in the web browser. I could `ssh` into the DJA0230 device over the Wireguard VPN, but nothing else would connect.

In the auto-generated config files, the DNS server was set to `192.168.0.1`, the same address as the GUI for the device. I tried changing this on both my phone and laptop to `8.8.8.8` and reconnected the Wireguard tunnel on both devices, and I could then access, not only websites, but also other devices on my LAN (including the router via `ssh`).

Everything is 'working' now in the sense that I can do everything I wanted, but I'm curious why the default setting of the router itself as DNS server isn't working but the Google public DNS one is. Do you have any recommendations for steps to take to debug this? Thanks!

**Comment by seud0nym** [comment]
I assume you had all the access controls for your peer set to "ON" (LAN,WAN,SSH, and GUI)?

**Comment by seud0nym** [comment]
Sorry,  I haven't had a chance to look at this. I hope to get to it soon.

**Comment by seud0nym** [comment]
My sincere apologies that it has taken so long to get to this.

I have reproduced the issue and found the problem. I had not added the WireGuard interface to the DNS server, so it was not listening for requests.

I have uploaded the fixed extras script. You can download and apply with:
```
./tch-gui-unhide -x wireguard -y
```
