### ISSUE TITLE
Telstra theme

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#15]
Have you thought of adding another option for Telstra theme? So for telstra, people should have two choices with Telstra theme if one decides to use it. 

Highlight color: Classic, and or Modern
![Capture](https://user-images.githubusercontent.com/45726972/101272314-db7f1580-37d6-11eb-9907-5d4085e2a37d.PNG)

So two simple choices in the drop down menu for Telstra theme only. 

Basically, the modern would be using your polished up and nicer looks. The classic would be the default ones from Telstra

**Comment by seud0nym** [comment]
Actually, I think you have found a bug. The Telstra theme is not supposed to have the flatter modern look with the different font.

What I have done for the next release is that there will now be 2 Telstra themes. As you suggested, they will be named Classic and Modern.
