### ISSUE TITLE
firewall issue

### ISSUE THREAD

**Issue by legend069** [seud0nym/tch-gui-unhide#151]
hey there,

i'm not sure if this is an issue on my end or not.

but it seems the user defined firewall rules are not working ?
copy/paste of some logs from netgear 

setup;
outside internet -> DJA0231(192.168.2.1) -> netgear D6220(dhcp server 192.168.1.0) -> x2 DJA0231(bridged mode)
![image](https://github.com/seud0nym/tch-gui-unhide/assets/40685552/082b7027-0532-413c-9438-fc154e734c96)

```
[Service blocked: ICMP_echo_req] from source 34.80.0.147, Monday, May 15,2023 15:48:02
[Service blocked: ICMP_echo_req] from source 34.106.8.177, Monday, May 15,2023 14:18:38
[Service blocked: ICMP_echo_req] from source 104.44.11.102, Monday, May 15,2023 14:12:01
[Service blocked: ICMP_echo_req] from source 104.44.7.164, Monday, May 15,2023 14:12:01
[Service blocked: ICMP_echo_req] from source 104.44.11.167, Monday, May 15,2023 14:12:01
[Service blocked: ICMP_echo_req] from source 104.44.236.129, Monday, May 15,2023 14:12:01
[Service blocked: ICMP_echo_req] from source 104.44.46.63, Monday, May 15,2023 14:12:01
[Service blocked: ICMP_echo_req] from source 27.32.160.204, Monday, May 15,2023 14:12:01
[Service blocked: ICMP_echo_req] from source 10.20.21.188, Monday, May 15,2023 14:12:01
[Service blocked: ICMP_echo_req] from source 192.168.2.1, Monday, May 15,2023 14:12:01
[Service blocked: ICMP_echo_req] from source 13.104.184.198, Monday, May 15,2023 14:12:00
[Service blocked: ICMP_echo_req] from source 104.44.46.63, Monday, May 15,2023 14:12:00
[Service blocked: ICMP_echo_req] from source 27.32.160.204, Monday, May 15,2023 14:12:00
[Service blocked: ICMP_echo_req] from source 10.20.21.188, Monday, May 15,2023 14:12:00
[Service blocked: ICMP_echo_req] from source 192.168.2.1, Monday, May 15,2023 14:12:00
[Service blocked: ICMP_echo_req] from source 104.44.32.103, Monday, May 15,2023 14:11:55
[Service blocked: ICMP_echo_req] from source 104.44.29.241, Monday, May 15,2023 14:11:54
[Service blocked: ICMP_echo_req] from source 104.44.16.148, Monday, May 15,2023 14:11:54
```

**Comment by seud0nym** [comment]
I am not a networking expert at all, but my understanding is that the firewall operates at level 3 of the networking stack, but bridging operates at level 2.

So, your internet connection is passing through the DJA0231 at a lower level, and the DJA0231 firewall doesn't see the packets at all. 

Also, the firewall operates on the concept of zones, especially the WAN zone. The bridge had no active wan interface to work with (again, the layer 2 thing).

All firewall rules have to be applied at the router behind the bridge

**Comment by legend069** [comment]
yeah i can understand the x2 DJA0231 firewall not "in use" when in bridged more. 
but my main gateway(DJA0231) is not in bridged mode, i've got it setup so it just makes the internet connection and switch over to simcard back up if needed. this is why i'm confused.
my neatgear is acting as a second firewall,DHCP server, ect.
the other two DJA0231 i have are in bridged mode and are just used as a AP/switch

**Comment by legend069** [comment]
hmmm ok. this is werid.
i made a duplicate wan zone.wanted to see if my upload speed would change. and it did.(jumped from under 300kibs to over 1500mibs)
i also can't ping my public ip address.( was able to before i messed with DJA0231 firewall. also no log for it in the netgear)
i've now deleted the entry i made,rebooted and all seems to be still fine.

so i'm not sure what i did but it seems better now.
