### ISSUE TITLE
Telephony: Port 1 - Phone 1 Not working

### ISSUE THREAD

**Issue by unclelez** [seud0nym/tch-gui-unhide#153]
Hi, and thank you for all your efforts.

I registered a SIP account in the Telephony tab and connected a Telstra T1000C analogue handset to the `Phone` port, but the handset doesn't receive any dial tone or line voltage. `Phone 1` is enabled on both `Incoming Maps` and `Outgoing Maps`  I've connected a DECT handset, which works fine with the SIP account and replicates this on my second router. It seems the `FXS` port is disabled.

Any help would be great.

**Comment by seud0nym** [comment]
Was the port ever working?

tch-gui-unhide doesn't change the configuration of the ports.

The only related configuration option as far as I can see is the FXO profile. What does this return:
```
uci show mmpbxbrcmfxonet.fxo_profile.enabled
```

**Comment by seud0nym** [comment]
Oops, sorry, you said FXS. There doesn't seem to be any option to disable it:
```
uci show mmpbxbrcmfxsdev.fxs_dev_0
```

**Comment by unclelez** [comment]
No, I have never used this port before but its a supported handset on Telstra site

`root@mymodem:~# uci show mmpbxbrcmfxsdev.fxs_dev_0
mmpbxbrcmfxsdev.fxs_dev_0=device
mmpbxbrcmfxsdev.fxs_dev_0.user_friendly_name='Phone 1'
mmpbxbrcmfxsdev.fxs_dev_0.comfort_noise='silence'
mmpbxbrcmfxsdev.fxs_dev_0.echo_cancellation='1'
mmpbxbrcmfxsdev.fxs_dev_0.fax_transport='inband_renegotiation'
mmpbxbrcmfxsdev.fxs_dev_0.t38_redundancy='1'
mmpbxbrcmfxsdev.fxs_dev_0.rtcp_interval='5000'
mmpbxbrcmfxsdev.fxs_dev_0.relay_state='0'
mmpbxbrcmfxsdev.fxs_dev_0.codec_black_list='G722'
mmpbxbrcmfxsdev.fxs_dev_0.cw_cas_delay='758'
mmpbxbrcmfxsdev.fxs_dev_0.fxs_privacy_reason='P'
mmpbxbrcmfxsdev.fxs_dev_0.fxs_unavailability_reason='O'
mmpbxbrcmfxsdev.fxs_dev_0.fxs_port='1'
mmpbxbrcmfxsdev.fxs_dev_0.cid_display_date_enabled='1'
mmpbxbrcmfxsdev.fxs_dev_0.cid_display_calling_line_enabled='1'
mmpbxbrcmfxsdev.fxs_dev_0.cid_display_calling_party_name_enabled='1'
mmpbxbrcmfxsdev.fxs_dev_0.vmwi_display_date_enabled='0'
mmpbxbrcmfxsdev.fxs_dev_0.pos='0'
mmpbxbrcmfxsdev.fxs_dev_0.early_detect_faxmodem='0'`

**Comment by unclelez** [comment]
```
root@mymodem:~# uci show mmpbxbrcmcountry.global_provision
mmpbxbrcmcountry.global_provision=mmbrcmglobalprovisionmap
mmpbxbrcmcountry.global_provision.min_connect_time='150'
mmpbxbrcmcountry.global_provision.min_disconnect_time='270'
mmpbxbrcmcountry.global_provision.min_hookflash_time='40'
mmpbxbrcmcountry.global_provision.max_hookflash_time='145'
mmpbxbrcmcountry.global_provision.plsdl_minbreak_time='20'
mmpbxbrcmcountry.global_provision.plsdl_maxbreak_time='200'
mmpbxbrcmcountry.global_provision.plsdl_minMake_time='20'
mmpbxbrcmcountry.global_provision.plsdl_maxMake_time='200'
mmpbxbrcmcountry.global_provision.plsdl_interdigit_time='100'
mmpbxbrcmcountry.global_provision.plsdl_enabled='0'
mmpbxbrcmcountry.global_provision.call_wtg_delay='10'
mmpbxbrcmcountry.global_provision.cid_mode='3'
mmpbxbrcmcountry.global_provision.cid_sigprotocol='1'
mmpbxbrcmcountry.global_provision.cid_fskafterring='550'
mmpbxbrcmcountry.global_provision.cid_fskafterdtas='50'
mmpbxbrcmcountry.global_provision.cid_fskafterrpas='800'
mmpbxbrcmcountry.global_provision.cid_ringafterfsk='500'
mmpbxbrcmcountry.global_provision.cid_dtasafterlr='250'
mmpbxbrcmcountry.global_provision.fxs_cid2ack_timeout='360'
mmpbxbrcmcountry.global_provision.cid_fskrpas_duration='600'
mmpbxbrcmcountry.global_provision.cid1_dtas_tone_id='0'
mmpbxbrcmcountry.global_provision.vmwi_dtas_tone_id='0'
mmpbxbrcmcountry.global_provision.cid2_dtas_tone_id='1'
mmpbxbrcmcountry.global_provision.cid1_dtas_level='24'
mmpbxbrcmcountry.global_provision.cid2_dtas_level='24'
mmpbxbrcmcountry.global_provision.fxo_clip2_ack_tone_level='12'
mmpbxbrcmcountry.global_provision.vmwi_mode='9'
mmpbxbrcmcountry.global_provision.vmwi_sigprotocol='3'
mmpbxbrcmcountry.global_provision.vmwi_fskafterdtas='50'
mmpbxbrcmcountry.global_provision.vmwi_fskafterrpas='650'
mmpbxbrcmcountry.global_provision.vmwi_dtasafterlr='500'
mmpbxbrcmcountry.global_provision.vmwi_msgformat='1'
mmpbxbrcmcountry.global_provision.pte_detectadmin='3'
mmpbxbrcmcountry.global_provision.pte_mindetectpower='31'
mmpbxbrcmcountry.global_provision.pve_egressvolume='0'
mmpbxbrcmcountry.global_provision.dtmf_dbLevel='12'
mmpbxbrcmcountry.global_provision.dtmf_pulseTime='100'
mmpbxbrcmcountry.global_provision.highvring_support='1'
mmpbxbrcmcountry.global_provision.powerring_frequency='25'
mmpbxbrcmcountry.global_provision.ring_waveform='0'
mmpbxbrcmcountry.global_provision.ring_dcoffset='25'
mmpbxbrcmcountry.global_provision.tx_gain_fxs='0'
mmpbxbrcmcountry.global_provision.rx_gain_fxs='0'
mmpbxbrcmcountry.global_provision.tx_gain_pstn='2'
mmpbxbrcmcountry.global_provision.rx_gain_pstn='8'
mmpbxbrcmcountry.global_provision.tx_gain_dect='1'
mmpbxbrcmcountry.global_provision.rx_gain_dect='0'
mmpbxbrcmcountry.global_provision.tx_gain_nosig='0'
mmpbxbrcmcountry.global_provision.rx_gain_nosig='0'
mmpbxbrcmcountry.global_provision.voice_jitter_buff_fixed='0'
mmpbxbrcmcountry.global_provision.voice_jitter_buff_min='0'
mmpbxbrcmcountry.global_provision.voice_jitter_buff_max='0'
mmpbxbrcmcountry.global_provision.voice_jitter_buff_target='20'
mmpbxbrcmcountry.global_provision.data_jitter_buff_target='0'
mmpbxbrcmcountry.global_provision.pstn_cdis_det_disabled='1'
mmpbxbrcmcountry.global_provision.dect_cdis_det_disabled='1'
mmpbxbrcmcountry.global_provision.fxs_cdis_det_disabled='0'
mmpbxbrcmcountry.global_provision.ring_voltage='50'
```

**Comment by seud0nym** [comment]
Sorry, but I have no idea. I would suspect a hardware fault on the telephone port. Do you have a spare DJA0230/1 you can test the phone on?

**Comment by unclelez** [comment]
Yes, it was a faulty port. Weird enough, 2 out 3 of my device we faulty.

Thank you help any

**Comment by seud0nym** [comment]
Glad you got it sorted out.
