### ISSUE TITLE
Smart Modem 3 - "Received a non string value." when setting wifi password.

### ISSUE THREAD

**Issue by Petarkco** [seud0nym/tch-gui-unhide#155]
On the SM3 on 21.4.0372-MR2-RA firmware with version 2023.05.29 the modem will not accept any wifi passwords (including the default).

When Security Mode is set to WPA 2 PSK it will state "Received a non string value.". When Security Mode is set to other settings it will show it saved successfully but the password will revert back to the default.

**Comment by seud0nym** [comment]
I am sorry, but I cannot reproduce this.

My test SMG3 is running 21.4.0372 and tch-gui-unhide 2023.05.29.

I just changed the password to `thisisalongpassword`. I didn't get any error and it did not revert back. I changed it back to the default password, and it saved okay and stuck. I then split the SSIDs and just changed the 5GHz password, and that worked without error and stuck.

I don't really like recommending it, but maybe try resetting?

**Comment by Petarkco** [comment]
Have now tried resetting and it's still not working. Was working before running de-telstra/tch-gui-unhide.

![image](https://github.com/seud0nym/tch-gui-unhide/assets/25685344/b6925025-6ca0-4b96-af84-4a5308914240)

When submitting the change it's posting: 
```split_ssid=0&ap_enabledcred0=1&ssidcred0=TelstraDCD885&ap_broadcast_ssidwl1=false&securitycred0=wpa2-psk&passwordcred0=TEST&pmfwl1=true&acl_modewl1=disabled&ap_enabledcred1=1&ssidcred1=TelstraDCD885&ap_broadcast_ssidwl0=false&securitycred1=wpa2-psk&passwordcred1=TEST&pmfwl0=true&acl_modewl0=disabled&action=SAVE&CSRFtoken=fe322e230160581d2ca9fc888dc82881bd51dcfae19ff716d2813673e3c210d9```

```split_ssid: 0
ap_enabledcred0: 1
ssidcred0: TelstraDCD885
ap_broadcast_ssidwl1: false
securitycred0: wpa2-psk
passwordcred0: TEST
pmfwl1: true
acl_modewl1: disabled
ap_enabledcred1: 1
ssidcred1: TelstraDCD885
ap_broadcast_ssidwl0: false
securitycred1: wpa2-psk
passwordcred1: TEST
pmfwl0: true
acl_modewl0: disabled
action: SAVE
CSRFtoken: fe322e230160581d2ca9fc888dc82881bd51dcfae19ff716d2813673e3c210d9```

**Comment by Petarkco** [comment]
Looks like resetting works.

**Comment by seud0nym** [comment]
Great.
