### ISSUE TITLE
Adblock removal instructions not working

### ISSUE THREAD

**Issue by gyCfjSnO** [seud0nym/tch-gui-unhide#158]
[These instructions](https://github.com/seud0nym/tch-gui-unhide/tree/master/extras#removal-instructions) don't work, yields the following:

```
root@DJA0231:~# sh tch-gui-unhide-xtra.adblock setup
>> Determining installed and current versions of required packages...
>> Setup complete
```

**Comment by seud0nym** [comment]
My apologies. The command should be:
```
sh tch-gui-unhide-xtra.adblock remove
```
I have updated the instructions.

**Comment by gyCfjSnO** [comment]
> My apologies. The command should be:
> 
> ```
> sh tch-gui-unhide-xtra.adblock remove
> ```
> 
> I have updated the instructions.

Thanks, muchly appreciated.
