### ISSUE TITLE
Unable to get IPv6 prefix from WAN

### ISSUE THREAD

**Issue by Hellohi3654** [seud0nym/tch-gui-unhide#159]
So I have been trying to get IPv6 working on my DJA0231 which is connected to my Starlink setup
I have Starlink in bypass mode which is needed to get IPv6 to work
I followed this issue https://github.com/seud0nym/tch-gui-unhide/issues/24 and changed my internet access settings to this:

![image](https://github.com/seud0nym/tch-gui-unhide/assets/57390764/e473e858-6cd5-4b09-ae13-5523b1b20716)

This allows the router itself to get an IPv6 address which I tested with ping6 in the CLI
But devices connected via ethernet and wifi are not assigned an IPv6 address by the router

I also have an Arcadyan LH1000 which I connected to Starlink it got an IPv6 address straight away and all devices connected to it also got IPv6 access without changing any settings

From this, I discovered that the problem with my DJA0231 appears to be that it is not getting an IPv6 prefix on the eth4 interface tried a number of different configs in the internet access tab but the only two that even get an IPv6 for the router are

![image](https://github.com/seud0nym/tch-gui-unhide/assets/57390764/a0e0062e-3713-4db8-bf00-6e19ec7ebeec)
![image](https://github.com/seud0nym/tch-gui-unhide/assets/57390764/cff2b939-a243-4531-a125-b76e9c0321c7)

I can change the IPv6 prefix request from auto to /56 but that doesn't seem to change anything

As for my local network config I generated a random ULA prefix

![image](https://github.com/seud0nym/tch-gui-unhide/assets/57390764/08c9703d-8dc2-4336-88a3-eaf6dfd7833a)

and this is my DHCP settings

![image](https://github.com/seud0nym/tch-gui-unhide/assets/57390764/43315ff2-f89d-46c5-aa7b-70857ac3456c)
![image](https://github.com/seud0nym/tch-gui-unhide/assets/57390764/437aadd0-5a74-4f3b-97f0-27fdadfb14f3)

I still have my Telstra SIM card that still seems to be working and when I switch on mobile only mode IPv6 works for all devices
Well actually IPv4 doesn't work at all only IPv6

![image](https://github.com/seud0nym/tch-gui-unhide/assets/57390764/f11bfa01-3105-4d5d-ac42-3fa235ba296b)

This is what the same page looks like with mobile only mode disabled

![image](https://github.com/seud0nym/tch-gui-unhide/assets/57390764/9331dcb1-6f0a-4331-87cf-e6fc8d144f1f)

Blanked out my public IPv4 and part of IPv6

I am running Firmware Version 20.3.c.0501-MR22-RC
But I have tried to get it working with MR19 and MR21.1 as well
I have also tried plugging it in before running tch-gui-unhide and de-telstra but I don't even get a IPv6 for the router

Just wondering if anyone could help me get IPv6 working 
Thanks

**Comment by Hellohi3654** [comment]
Forgot to also mention I got IPv6 working by setting the DJA0231 to bridge mode and connecting it to the LH1000 which got IPv6 working but I would like to have everything handled by my DJA0231 so that I can setup things such as adblocking

**Comment by seud0nym** [comment]
I would have thought the default settings on the LH1000 and the DJA0231 were the same, so if the LH1000 works, the default settings on the DJA0231 should also work. But you said you tried that and it didn't work.

Pretty sure that the only thing that de-telstra changes is WAN Supervision from BFD to DNS, but that wouldn't affect getting and IPv6 prefix.

IPv6 ULA prefix and DHCP settings only affect your LAN, and have nothing to do with the WAN.

IPv6 Force Prefix means that if can't get a prefix, that don't bother with an IPv6 address, so that is okay. Have you tried No SLAAC Only enabled?

Starlink doesn't have any publicly accessible configuration info, apart from it should work if the router supports it, which isn't much help. Is it DHCP routed mode or PPoE routed?

**Comment by Hellohi3654** [comment]
My LH1000 said IPoE which I think is DHCP routed on DJA0231
I tried enabling SLAAC Only but then I don't even get a IPv6 for the router 
I also noticed that LH1000 was set to BFD and tried changing it on my DJA0231 but it doesn't change anything 
I've tried to set the IPv6 prefix for wan6 in /etc/config/network manually to /56 using `option ip6prefix '56'`

I found it in the openwrt docs here: https://openwrt.org/docs/guide-user/network/ipv6/configuration#protocol_dhcpv6

Should I try ip6assign doesn't appear to be in the list of options for dhcpv6 but it might work

**Comment by Hellohi3654** [comment]
Could also try static mode I guess

**Comment by seud0nym** [comment]
The `ip6assign` configuration is set by the `IPV6 Prefix Size` GUI option.

Forcing the prefix size won't do anything.

Is there anything in the log?
```
logread -e wan6
```

**Comment by Hellohi3654** [comment]
Doesn't seem like there's anything useful
`Fri Jun 30 10:05:02 2023 daemon.notice netifd: Interface 'wan6' is enabled
Fri Jun 30 10:05:03 2023 daemon.notice netifd: Interface 'wan6' has link connectivity
Fri Jun 30 10:05:03 2023 daemon.notice netifd: Interface 'wan6' is setting up now
Fri Jun 30 10:05:17 2023 daemon.notice wansensing: The L3DHCP entry script is configuring DHCP on wan and wan6 interface on l2type interface ETH
Fri Jun 30 10:05:18 2023 daemon.notice netifd: Interface 'wan6' is now up
Fri Jun 30 10:05:24 2023 daemon.notice wansensing: (L3DHCP) runs L3DHCPMain.check(ETH,supervision_wan6_ok)
Fri Jun 30 11:55:24 2023 user.notice firewall: Reloading firewall due to ifup of wan6 (eth4)
Fri Jun 30 11:55:28 2023 daemon.notice lot: hotplug "ifup wan6 eth4"`

**Comment by seud0nym** [comment]
What do the following return:
```
uci show network.wan
uci show network.wan6
```
(You can use \`\`\` on the line before and after your output to format the results nicely.)

**Comment by Hellohi3654** [comment]
uci show network.wan
```
network.wan=interface
network.wan.reqopts='1 3 6 43 51 58 59'
network.wan.iface6rd='0'
network.wan.vendorid='technicolor'
network.wan.metric='1'
network.wan.release='1'
network.wan.proto='dhcp'
network.wan.ifname='eth4'
network.wan.auto='1'
network.wan.ipv6='1'
network.wan.peerdns='1'
```
uci show network.wan6
```
network.wan6=interface
network.wan6.proto='dhcpv6'
network.wan6.defaultreqopts='0'
network.wan6.reqopts='23 17'
network.wan6.iface_464xlat='0'
network.wan6.soltimeout='240'
network.wan6.ifname='eth4'
network.wan6.forceprefix='0'
network.wan6.noslaaconly='0'
network.wan6.reqaddress='try'
network.wan6.auto='1'
network.wan6.reqprefix='56'
network.wan6.ip6prefix='56'
network.wan6.peerdns='1'
```
Seems alright to me 
I added ip6prefix myself 
I'll try adding ip6assign 
Might work

**Comment by Hellohi3654** [comment]
Adding ip6assign
Assigns the wan6 interface the lan IPv6 address funnily enough

**Comment by Hellohi3654** [comment]
![Screenshot_20230630-201659.jpg](https://github.com/seud0nym/tch-gui-unhide/assets/57390764/e82b3195-a1ce-4f23-b63a-8925f9ec669a)

Found a small mention of IPv6 which confirms the prefix is /56. But that's about it

**Comment by Hellohi3654** [comment]
Would you like me to send my entire /etc/config/network file?
Maybe I should also plug in my LH1000 and grab the same file from it since rooting it is ridiculously easy

**Comment by Hellohi3654** [comment]
Nevermind think I have bricked my LH1000 tried to update busybox last time I used it and now it's in a boot loop lol
Oh well
Just let me know if you want the /etc/config/network file from my DJA0231

**Comment by seud0nym** [comment]
> ip6assign

I will have to double check the code, I was sure the GUI sets it.

> Seems alright to me
> I added ip6prefix myself

I am pretty sure that ip6prefix is supposed to be a full IPv6 subnet with CIDR, and is an *additional* IPv6 prefix for distribution to clients. So, if you had the prefix that was delegated to your LH1000, you could enter that there as a workaround.

I did find a post that indicated that MTU might be the issue. Please try this:
```
uci set network.wan.mtu='1492'
uci commit network
/etc/init.d/network restart
```

It is a pity you have lost access to your LH1000 - it would have been interesting to see what MTU it was using.

**Comment by Hellohi3654** [comment]
Thanks I'll try that
I still remember the prefix was the IPv6 address shortened with /56 at the end I'll try setting ip6prefix to that

**Comment by Hellohi3654** [comment]
I was playing around with using static mode instead of DHCP and I got the prefix to show up but ipv6 still didn't work so I'm guessing I got the IPv6 gateway wrong or the prefix

**Comment by Hellohi3654** [comment]
Tried different mtu doesn't seem to change anything

**Comment by Hellohi3654** [comment]
Found why I am getting a prefix 
Static mode leaves all it's config options even though the proto is set to dhcpv6

```
config interface 'wan6'
        option defaultreqopts '0'
        option reqopts '23 17'
        option iface_464xlat '0'
        option soltimeout '240'
        option ifname 'eth4'
        option forceprefix '0'
        option reqprefix '56'
        option noslaaconly '0'
        option peerdns '1'
        option ip6prefix '2406:2d40:4000:50f6::/56'
        option ip6gw 'fe80::200:5eff:fe00:101'
        option ip6addr '2406:2d40:4000:50f6:a691:b1ff:xxxx:xxxx
        option proto 'dhcpv6'
        option reqaddress 'try'
```

**Comment by Hellohi3654** [comment]
Deleted these two lines 

```
        option ip6gw 'fe80::200:5eff:fe00:101'
        option ip6addr '2406:2d40:4000:50f6:a691:b1ff:xxxx:xxxx'
```
But kept 
```
option ip6prefix '2406:2d40:4000:50f6::/56'
```
Still not working

**Comment by Hellohi3654** [comment]
Yaaay
Finally figured it out

So I was reading the openwrt docs and noticed that the firewall rule they mention that allows dhcpv6 replies was missing well not completely it was partly there just missing the src port
Didn't want to mess with system rules so I just made a new firewall rule
```
config rule
        option target 'ACCEPT'
        option src 'wan'
        option proto 'udp'
        option dest_port '546'
        option name 'Allow DHCPv6 replies'
        option family 'ipv6'
        option src_port '547'
```
Which I copied from 
https://openwrt.org/docs/guide-user/network/ipv6/configuration
And then I got a IPv6 prefix straight away and IPv6 is now working on all my devices

I also set the mtu back to 1500 before trying all this

Thanks for your help

**Comment by seud0nym** [comment]
I am very glad that you worked it out. I don't think I was much help at all.

**Comment by Hellohi3654** [comment]
Wonder why that firewall rule doesn't have the src port included in it
According to the openwrt docs you need the src port to allow dhcpv6 to work 
Might just be a bug

**Comment by seud0nym** [comment]
It is very strange. I am just using the default rules and I get my IPv6 prefix without src_port in the default system rule. Anyway, it is working for you, and that is the main thing.
