### ISSUE TITLE
Uptime in basic view does not match with uptime in internet access "modal"

### ISSUE THREAD

**Issue by gsstudios** [seud0nym/tch-gui-unhide#16]
There is a minor UI issue that I noticed where if 24hours has passed (1day), the basic view does not display that 1 day has passed. Only after 48 hours (2 days) has passed, it displays correctly (screenshot pending).  
Basic view:
![image](https://user-images.githubusercontent.com/9124784/101416076-2c108300-393d-11eb-850d-03c0b6287b62.png)
Internet Access modal:
![image](https://user-images.githubusercontent.com/9124784/101416122-421e4380-393d-11eb-8e76-f8474d966e3e.png)

**Comment by seud0nym** [comment]
Yes, I can see the bug. It will be fixed in the next release.
