### ISSUE TITLE
Tor (Extended Capabilities)

### ISSUE THREAD

**Issue by haps-basset** [seud0nym/tch-gui-unhide#162]
Would it be possible to add a tor service to extended capabilities?

**Comment by seud0nym** [comment]
It looks like there is a Tor client in the macoers repository, so you could install that and give it a try.

Looking at this info: https://openwrt.org/docs/guide-user/services/tor/client I can't see much that I could put on a card and the associated screen to add much value.

Also, I suspect that it may not work if IPv6 is enabled, given that these devices have no IPv6 NAT capability.

If I get a chance I will install it on my test box and see what happens.

**Comment by haps-basset** [comment]
Many thanks, I am working now to configure the tor as a proxy. It is not that easy as I have expected. The squid configuration was quite painful but tor as a proxy even more challenging fun.

I don't want to create a new issue because I think I did something foolish. I would appreciate it if you could help me to understand my mistake. Yesterday, I disabled guest networks (LAN and Wi-Fi).
To my surprise, I lost access to SSHD, and web admin console, but the router worked fine. I had to unlock shell and tch-gui-unhide to get the router to work as before. Question, is it possible that the disabling LAN/Wi-Fi guest services might cut web/shell access?

**Comment by seud0nym** [comment]
I can't imagine why that would cause a problem. I have a DJA0231 running as a managed switch at the moment - in bridged mode with all Wi-Fi disabled, although I didn't disable the guest networks.

**Comment by haps-basset** [comment]
I am sorry that I bother you again, but I cannot find solution to my problem, Perhaps you will be able to help me.
My router hangs quite often, showing the following message: 
[ERROR xtm] bcmxapi_xmit_packet,309: rdpa_cpu_tx_port_enet_or_dsl_wan() for XTM port returned -13 (wan_flow: 127 queue_id: 7)
I don't know what is mean, and this problem is beyond Telstra's help desk knowledge. Could explain or point me a forum that will be able to help me diagnose and troubleshoot this problem, please? I have already asked openwrt experts but without success. 
Any support highly appreciated.
Haps

**Comment by seud0nym** [comment]
I am sorry - I have no idea. It is too low level my knowledge or expertise.

**Comment by haps-basset** [comment]
That is fine. You have always helped me, and I am grateful for all your support, advice, always much appreciated.
