### ISSUE TITLE
FR Sim card use in bridged mode

### ISSUE THREAD

**Issue by legend069** [seud0nym/tch-gui-unhide#163]
Hey there, is it possible to get the simcard working while it's in bridged mode ?

**Comment by seud0nym** [comment]
There is a guide here for doing that:
https://hack-technicolor.readthedocs.io/en/stable/Unlock/#keep-wwan-functionality-while-homeware-gateway-is-bridged

**Comment by legend069** [comment]
just thought i would post an update here
while messing about in the DJA0231 i somehow locked myself out.
got back into it set it up again and ect, first thing i noticed was the easy mesh discovered the other AP's right away, neat i guess.

continued trying to get it to work with the SIM still active while in bridged mode.. 
and it works !! yay
set the second one up exactly the same(part different IP's )
configured pfsense  to add it as another gateway,adjusted gatewaygroups
and yes it still works. unplugged main WAN cable it switched over to the simcards IP, marked 1 as down and it switched over to the other.
running tracert reports traffic still goes through pfsense, although if i change my gateway on a client to either 1.1 or 1.3 
the traffic doesn't go though pfsense, witch is expected and security flaw i guess?
(lets see how long it would stay like this before telstra disables the sim cards....)

now for some reason after adjusting 192.168.1.3, 192.168.1.1 can't see it as a booster anymore.
192.168.1.1 can only detect 192.168.1.2 that i have not adjusted yet.
maybe it has something to do with the SIM card stuff?

**Comment by seud0nym** [comment]
> although if i change my gateway on a client to either 1.1 or 1.3
> the traffic doesn't go though pfsense, witch is expected and security flaw i guess?

I would expect that, yes. Security flaw? Not really - it is just a network design issue. Can you configure the firewall on pfsense to prevent it?

> now for some reason after adjusting 192.168.1.3, 192.168.1.1 can't see it as a booster anymore.
> 192.168.1.1 can only detect 192.168.1.2 that i have not adjusted yet.
> maybe it has something to do with the SIM card stuff?

Definitely not going to be SIM card related.

Easymesh only works if directly connected - if there is a switch in-between or the packets are routed via another gateway, it doesn't work.

> lets see how long it would stay like this before telstra disables the sim cards....

If you have more than a small amount of traffic, or it is continuous, then it won't take them very long.

**Comment by legend069** [comment]
i'm going to assume
wl0 -wireless 2.4ghz
wl1 -wireless 5ghz
wl1_1 - but what is this one ? would it be the 4g sim card connection?

**Comment by seud0nym** [comment]
The fresh install looks like you haven't run in the `bridged-booster` script - that is what adds the wireless interfaces to the bridge.

wl1_1 is the wireless backhaul for EasyMesh. It is not used by the `bridged_booster` configuration, but if you have a "real" Telstra booster device, it does get used.

**Comment by legend069** [comment]
ok update here and closing issue
after a small hicup with the DJA2031 rebooting midway though installing scripts it auto updated its firmware to type3
(note to self; remove simcard before setting back to factory defaults)
@seud0nym possible to add a warning for user to remove simcard if they reset to factory defaults?

i was able to get it do do what i want by
fresh installing scripts 
running 
./de-telstra -A
./tch-gui-unhide
installed simcard - made sure it was working in this mode.(if you don't install simcard now and get a connection the wifi booster script wont't be able to connect for some reason)
it will need to have the dynamic route added before you continue
![image](https://github.com/seud0nym/tch-gui-unhide/assets/40685552/88acbc30-672c-4f88-be12-3bbdf7aca681)

ran my edited wifi-booster script (just removed the mobile stuff, i did try setting up a new command to enable mobile, but i wasn't able to figure out the coding) https://github.com/legend069/tch-gui-unhide/blob/master/wifi-booster/bridged-boostern
made other changes with ./de-telstra

pfsense still sees it as a gateway and all 3 of my AP's are on load balancing failover whoohoo!
(speed tests reports ~100mbps down, the fact that now all sites services take advantage over multi wan is a little annoying but eh)

now i just need to figure out how to route the traffic properly so it all goes though the pfsense. this is fun 😄
I should also adjust pfsense to disable the main gateway everynow and then too so the simcards will have a lower chance of getting disabled.

**Comment by seud0nym** [comment]
> possible to add a warning for user to remove simcard if they reset to factory defaults?

There are 2 options on reset-to-factory-defaults-with-root to prevent  OTA updates are reboot:

-c Turns off CWMP so it just can't happen.
-d Adds a DNS rewrite so that even if it attempts to download an update, it will fail to resolve the Telstra firmware repository.

But I will think about adding a warning.
