### ISSUE TITLE
opkg update fails, repository possibly unreachable

### ISSUE THREAD

**Issue by sabin458** [seud0nym/tch-gui-unhide#164]
admittedly i'm a bit rusty with linux etc.  but i seem to be cloudfare blocked from the macoers repository.  attempted via de-telstra -o, and with the manual config instructions.  each time i fail, wget returned 8.  

have attempted to manually access the files via the url hoping i might be able to SCP them onto the router, but receive a cloudflare "You've Been Blocked page".  Is this repo down or am I just doing something wrong?

 * opkg_download: Failed to download https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/base/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/packages/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/luci/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/routing/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/telephony/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/target/packages/Packages.gz, wget returned 8.

**Comment by seud0nym** [comment]
A few people have mentioned that they are blocked.

I would recommend sending an email to info@macoers.com with your external IPv4 address and ask why you have been blocked.

**Comment by sabin458** [comment]
Yea i reached out.  Seems they had a lot of suspicious activity from Aus
IPs.  Theyve quickly whitelisted my IP.  Too easy.  I'll give it a test
later tonight to see if issue resolved.  Thanks!

For further info, I'm using Superloop, so fairly certain theyre using
dynamic dns (not sure if using CGNAT) so I may need to pay for their Static
IP at $5/month to keep the whitelist functional.  But they did say if my IP
changes I can reach out again ro be re whitelisted.

**Comment by ECHOSUD** [comment]
I'm currently having the same issue and haven't yet sent an email. I think this issue should be mentioned in the wiki or listed as an open issue.  I struggled to find any information online trying to troubleshoot: opkg_download: Failed to download ... , wget returned 8.
