### ISSUE TITLE
Telstra Smart Modem Gen 3 (VCNT-8) opkg update failed

### ISSUE THREAD

**Issue by audynamo** [seud0nym/tch-gui-unhide#166]
opkg update failed with following:
```
Product: vcnt-8_telstra
Release: TBD (21.4)
Version: 21.4.0372-5940000-20230204002902-5925b7eecdb5538b6f2ceb600510a907cbd9ba2f

Hash config:         5925b7eecdb5538b6f2ceb600510a907cbd9ba2f
Hash openwrt:        6364f563766c06e54e6437305265aac8c3d71349
Hash technicolor:    66080b5d1141ba8197045aef345396441b1a7d3f
Hash broadcom:       fbcffd0b10b3ddc67521faa05c348341f7a3df78
Hash custo:          88f3306524c7f08e65037692ef51570b285d986e
Hash packages:       63e2afb8abfbe4548defb1136cea1a4d4794aa67
Hash routing:        f71d7333926274755fab56d9f2b4f71a5a5126ce
Hash lte:            b7d567b7cf42d73163fd453681152ad1316be19e

Bootloader: 21.4.0372-5940000-20230204002902-5925b7eecdb5538b6f2ceb600510a907cbd9ba2f

root@mymodem:~# opkg update
Downloading http://downloads.openwrt.org/snapshots/targets/brcmbca/bcm963146/packages/Packages.gz
*** Failed to download the package list from http://downloads.openwrt.org/snapshots/targets/brcmbca/bcm963146/packages/Packages.gz

Collected errors:
 * opkg_download: Failed to download http://downloads.openwrt.org/snapshots/targets/brcmbca/bcm963146/packages/Packages.gz, wget returned 8.
```
There is no such `targets/brcmbca/bcm963146` in openwrt

**Comment by seud0nym** [comment]
There are no package repositories available for the Gen 3.

**Comment by audynamo** [comment]
when I install adguardhome, I saw
```
[AdGuard-Home-Setup] Running update-ca-certificates...
rpc.gui.opkg: Downloading https://downloads.openwrt.org/releases/packages-23.05/arm_cortex-a9/base/ca-bundle_20230311-1_all.ipk...
```
is it possible to add this as source list `https://downloads.openwrt.org/releases/packages-23.05/arm_cortex-a9/base/`?

**Comment by seud0nym** [comment]
No. That only works for the CA certificates because there are no executable files in the package. They are all text files. The certificates packages are identical for every hardware variant.

**Comment by audynamo** [comment]
Thanks, I check it is aarch64 architecture, and I can run v2ray-aarch64 binary. Maybe it can dowload aarch64 openwrt lib and install?

**Comment by seud0nym** [comment]
You can try and install aarch64 packages, but you will find at some point that because of the kernel differences between OpenWrt and the Technicolor devices, the binaries will fail to run.

**Comment by audynamo** [comment]
thanks for the explanation, so as it is proprietary software, there is no way to get a public build, right?

**Comment by seud0nym** [comment]
Correct. Some users in Italy were able to obtain the build toolchain for the previous generation devices, which is how the macoers repository was built, but unless that happens again, we are out of luck. Also, the Gen 3 is a completely different approach than  other recent Technicolor devices released in Europe (which contain in much the same way as previous generations), so I doubt we will see a repository any time soon.

**Comment by audynamo** [comment]
Thanks, then I will close this ticket.
