### ISSUE TITLE
Mobile card disappearing band selection

### ISSUE THREAD

**Issue by gingerninja234** [seud0nym/tch-gui-unhide#167]
Hey @seud0nym,

Not sure if it is my setup or modem… but once I change the active bands on the Mobile card the tick boxes disappear resulting me in having to do a full factory reset to get the bands back
 
Tried reinstalling tch-gui-unhide with no luck unfortunately 

Hopefully the screenshot helps

![IMG_0169](https://github.com/seud0nym/tch-gui-unhide/assets/22275247/ef94161c-296e-42f8-bcdf-4540c7a66f09)

**Comment by seud0nym** [comment]
Run the following command in PuTTY (or equivalent) _before_ selecting the bands:
```
transformer-cli get rpc.mobiled.device.@1.capabilities.supported_bands_lte
```

It should return:
```
root@test:~# transformer-cli get rpc.mobiled.device.@1.capabilities.supported_bands_lte
rpc.mobiled.device.@1.capabilities.supported_bands_lte [string] = 3 7 28
```

After you have changed the active bands, run it again.

Post both the before and after results back here.

Thanks.

**Comment by gingerninja234** [comment]
Not sure what's happened but I can't seem to replicate the issue since I did another factory reset, everything seems to be working fine so far. 

Here are the results:

Before change:
`root@mymodem:~# transformer-cli get rpc.mobiled.device.@1.capabilities.supported
_bands_lte
rpc.mobiled.device.@1.capabilities.supported_bands_lte [string] = 3 7 28`

After change (same result):
`root@mymodem:~# transformer-cli get rpc.mobiled.device.@1.capabilities.supported
_bands_lte
rpc.mobiled.device.@1.capabilities.supported_bands_lte [string] = 3 7 28`

**Comment by seud0nym** [comment]
Strange. It should only hide the check boxes if supported bands capability comes back empty. I will do some more research.

**Comment by seud0nym** [comment]
What device and firmware are you using?

Does "VF Web" mean you are using a Vodafone SIM? Can you do a test with the original Telstra SIM?

On my test DJA0230 running 20.3.c.0389, I just connected using the default Telstra SIM. It selected band 7, so I then deselected 7, and saved. The checkboxes were all still there, and it switched over to band 3.

**Comment by gingerninja234** [comment]
Device is a DJA0231 with the latest firmware, 20.3.c.0501-MR22.1-RA

Yes that’s right, using a Vodafone sim as a test. I’ve just popped the Telstra sim back in and unfortunately the tick boxes aren’t showing up, so I can’t enable and disable the bands 

![IMG_0188](https://github.com/seud0nym/tch-gui-unhide/assets/22275247/705a2c05-4ae0-48b2-9f3b-28dfe004a093)

**Comment by seud0nym** [comment]
I think the issue is that the Device Status is "Connecting" in all the screen shots you have provided. You can't configure the bands until the status is "Connected".

**Comment by gingerninja234** [comment]
Hmmm okay, I see what you mean. Hopefully it eventually connects!

I’m in the inner suburbs of Melbourne, so it shouldn’t be an issue I would’ve thought

**Comment by seud0nym** [comment]
What do the Network Status and Service Status show on the Diagnostics tab?

**Comment by gingerninja234** [comment]
So I've given the modem a reboot and the band selection has popped up again. It's showing as connected now after the reboot...

![image](https://github.com/seud0nym/tch-gui-unhide/assets/22275247/a0175199-29fc-432a-94fd-4f2fda5347ac)

**Comment by gingerninja234** [comment]
Okay so I've swapped back to the Vodafone SIM and bands have disappeared again. Also noticed the "Operator" and "Roaming dropdowns have disappeared too. Didn't get a chance to change it back to "Vodafone" so it might not connect

**Comment by gingerninja234** [comment]
Looks like an issue with my modem trying to provision settings. I swapped over with my other booster modem and that one was working fine so I guess there’s no problem.  I’ll close this issue for now since it’s not a problem to solve. Thanks for having a look into it!
