### ISSUE TITLE
Static Lease issues... 

### ISSUE THREAD

**Issue by rkaycom** [seud0nym/tch-gui-unhide#168]
Hello, I have a Technicolor TG800vac, was able to get root and run scripts. Everything seemed to be working but I've notice a pretty major bug, I'm new to all this router hacking so please bare with me.

Essentially the issue is I am unable to set or edit Static Leases with the new GUI. I was on the lastest firmware (17.2.0284-820-RA) and was able to set Leases before running tch-gui-unhide (on rooted device) and they worked correctly, but after running the scripts I can no longer add new Static Leases or view/edit the old ones. It displays on the card that they have been assigned (three in my case) but when going to the settings menu for Static Leases it appears blank and when I try to create new ones it gives me a rather vague error and fails to create new ones.

I have reset the router to defaults (while keeping root) and then immediately runs scripts (without creating Leases with default GUI) and am still not able to create new Leases.

The leases create BEFORE running tch-gui-unhide seem too work correctly before and after scripting. So, it's not game breaking as I just set them before running the script and they continue to work after the script the issue is that if I need to change them I need to reset the router and reconfigure everything, I haven't tried SSH commands as I wouldn't know what commands to run.

I should also note the scripts I run and which order after root are; ./set-optimal-bank-plan, ./de-telstra -A, ./tch-gui-unhide.

I am very keen to get this fixed as the upgrade to the router has been great, but this is a pretty important feature I can't seem to get to work.

Please let me know what I need to do if you need logs or further advise, very keen to help in what ever way I can, just a bit of a novice.

**Comment by rkaycom** [comment]
Sorry, just found this in the closed issues (new to GitHub too, didn't see the closed issues tab);

https://github.com/seud0nym/tch-gui-unhide/issues/118

I think it might be the same thing, I used the same guide and maybe have downloaded an old script version? Will try updating.

**Comment by seud0nym** [comment]
No, I think you are correct - there definitely is an error when saving a new static lease in the latest version.

Good timing - I was just about to put my TG800vac up for sale!

I will have a look.

**Comment by rkaycom** [comment]
> No, I think you are correct - there definitely is an error when saving a new static lease in the latest version.
> 
> Good timing - I was just about to put my TG800vac up for sale!
> 
> I will have a look.

Ah good timing indeed.

**Comment by seud0nym** [comment]
So the long story is that the underlying mechanism for managing static leases changed between firmware 17.2 and 18.1.c (which obviously isn't available for the TG800vac). So I had some code in the tch-gui-unhide installer to fix it so static leases would work in tch-gui-unhide for all firmware versions.

_However_, in release 2023.05.16 I separated out static leases into a separate tab to try and improve the performance of the Local Network card, which was very large and complicated, _But_, I forgot to update the code in the installer to the new tab, which means it is trying to use 18.1.c and later addressing to update static leases, and it just doesn't work.

The good news is that it is a simple fix. I have put a fixed install script which you can apply by running this command:
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```

**Comment by rkaycom** [comment]
> So the long story is that the underlying mechanism for managing static leases changed between firmware 17.2 and 18.1.c (which obviously isn't available for the TG800vac). So I had some code in the tch-gui-unhide installer to fix it so static leases would work in tch-gui-unhide for all firmware versions.
> 
> _However_, in release 2023.05.16 I separated out static leases into a separate tab to try and improve the performance of the Local Network card, which was very large and complicated, _But_, I forgot to update the code in the installer to the new tab, which means it is trying to use 18.1.c and later addressing to update static leases, and it just doesn't work.
> 
> The good news is that it is a simple fix. I have put a fixed install script which you can apply by running this command:
> 
> ```
> ./tch-gui-unhide -u && ./tch-gui-unhide -y
> ```

Cool, I'll try it tonight when I get home from work and let you know. You might want to hold on to that router for a little bit longer. I might have found another issue as well to do with VoIP but didn't want to overwhelm you with submits 🤣

**Comment by rkaycom** [comment]
So updated and problem all fixed, Leases appear, was able to delete and recreate. Would you like me to create separate issues for each different bug I find? I'm obviously fresh to this hack and am tinkering with it a fair bit and have found a couple issues.

**Comment by seud0nym** [comment]
Separate issues for different bugs is much easier to track.
