### ISSUE TITLE
Unable to disable Global Telephony with GUI...

### ISSUE THREAD

**Issue by rkaycom** [seud0nym/tch-gui-unhide#169]
Have a TG800vac running latest version of script. When attempting to disable Telephony under the global tab with GUI there is an error and process fails.

**Comment by seud0nym** [comment]
Fixed now. It was because I do all my testing on a DJA0230 which covers all FW from 17.2 to 20.3.c, but it does have 4G backup, and the bug only manifested if there is no mobile device present. Run the following to apply the latest fix:
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```

**Comment by rkaycom** [comment]
> Fixed now. It was because I do all my testing on a DJA0230 which covers all FW from 17.2 to 20.3.c, but it does have 4G backup, and the bug only manifested if there is no mobile device present. Run the following to apply the latest fix:
> 
> ```
> ./tch-gui-unhide -u && ./tch-gui-unhide -y
> ```

Will update and advise tonight when I get to test. I very much appreciate all your hard work with this. It's amazing what you have been able to accomplish. I'm sorry I'm finding all the broken bits. I had a lot more but it seems doing a restore to defaults fix the majority of them 🤣

**Comment by rkaycom** [comment]
All fixed, working as intended!
