### ISSUE TITLE
Internet access modal not displaying ip addresses

### ISSUE THREAD

**Issue by gsstudios** [seud0nym/tch-gui-unhide#17]
Connection: PPPoE
GUI version: 2020.12.09
Firmware version: 18.1.c.0549

Hi again,
In the internet modal, I've noticed that also the ip, dns and gateway details are missing. 
![image](https://user-images.githubusercontent.com/9124784/101707698-d7f1d400-3adf-11eb-8ece-75a9279aa7be.png)

**Comment by seud0nym** [comment]
I don't understand that all. The only difference between the one that I sent you for testing and the one in the release is that I removed the log messages.

Can you try deploying the test one again (following the instructions in the other issue), and see if the problem persists?

Thanks.

**Comment by gsstudios** [comment]
Whoops, I forgot to mention that I saw the same in the previous releases and also in the test files you prepared previously.

**Comment by seud0nym** [comment]
Oh. Okay.

Do these commands return the correct values (I don't need to know the results, just that the values are correct):
```
transformer-cli get "rpc.network.interface.@wan.ipaddr"
transformer-cli get "rpc.network.interface.@wan.nexthop"
transformer-cli get "rpc.network.interface.@wan.dnsservers"
```

They are all self-explanatory, except `nexthop` which is the gateway address.

**Comment by gsstudios** [comment]
> Oh. Okay.
> 
> Do these commands return the correct values (I don't need to know the results, just that the values are correct):
> 
> ```
> transformer-cli get "rpc.network.interface.@wan.ipaddr"
> transformer-cli get "rpc.network.interface.@wan.nexthop"
> transformer-cli get "rpc.network.interface.@wan.dnsservers"
> ```
> 
> They are all self-explanatory, except `nexthop` which is the gateway address.
I've ran these commands and they seem to be returning the correct values. Cheers

**Comment by seud0nym** [comment]
Sorry you have to be the guinea pig for my changes. Same deal as last time: copy the attached file up to your device, and then execute the following commands from the directory you copied it up to:
```
mv /www/snippets/internet-pppoe-routed.lp /www/snippets/internet-pppoe-routed.lp.old
tar -xzvf internet-pppoe-routed.lp.tar.gz -C /www/snippets/
```

If it doesn't open, it means I have made a typo, so execute this command: `logread | tail -n 20`

Otherwise it should just fix your problem. I check to see if they are missing before displaying them, and re-retrieve them. 

To undo the change, execute the following command:
```
mv /www/snippets/internet-pppoe-routed.lp.old /www/snippets/internet-pppoe-routed.lp
```
Thanks.

[internet-pppoe-routed.lp.tar.gz](https://github.com/seud0nym/tch-gui-unhide/files/5677280/internet-pppoe-routed.lp.tar.gz)

**Comment by gsstudios** [comment]
> 
> 
> Sorry you have to be the guinea pig for my changes. Same deal as last time: copy the attached file up to your device, and then execute the following commands from the directory you copied it up to:
> 
> ```
> mv /www/snippets/internet-pppoe-routed.lp /www/snippets/internet-pppoe-routed.lp.old
> tar -xzvf internet-pppoe-routed.lp.tar.gz -C /www/snippets/
> ```
> 
> If it doesn't open, it means I have made a typo, so execute this command: `logread | tail -n 20`
> 
> Otherwise it should just fix your problem. I check to see if they are missing before displaying them, and re-retrieve them.
> 
> To undo the change, execute the following command:
> 
> ```
> mv /www/snippets/internet-pppoe-routed.lp.old /www/snippets/internet-pppoe-routed.lp
> ```
> 
> Thanks.
> 
> [internet-pppoe-routed.lp.tar.gz](https://github.com/seud0nym/tch-gui-unhide/files/5677280/internet-pppoe-routed.lp.tar.gz)

Unfortunately it didn't open. Here is the log entry:

> Fri Dec 11 19:06:54 2020 daemon.err nginx: 2020/12/11 19:06:53 [error] 32319#0: *104 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #2 to 'format' (string expected, got table) stack traceback: coroutine 0:       [C]: in function 'format' /usr/lib/lua/web/taint.lua:280: in function 'format'     [string "internet-pppoe-routed.lp"]:91: in function 'split'     [string "internet-pppoe-routed.lp"]:357: in function 'content'     /usr/lib/lua/web/lp.lua:171: in function 'include'      [string "/modals/internet-modal.lp"]:82: in function 'content'     /usr/lib/lua/web/web.lua:249: in function 'process'     content_by_lua(nginx.conf:111):4: in function <content_by_lua(nginx.conf:111):1>, client: 192.168.1.101, server: localhost, request: "GET /modals/internet-modal.lp HTTP/1.1", host: "192.168.1.1", referrer: "http://192.168.1.1/gateway.lp"

**Comment by seud0nym** [comment]
Sorry. Here is another try...

[internet-pppoe-routed.lp.tar.gz](https://github.com/seud0nym/tch-gui-unhide/files/5678192/internet-pppoe-routed.lp.tar.gz)

**Comment by gsstudios** [comment]
> 
> 
> Sorry. Here is another try...
> 
> [internet-pppoe-routed.lp.tar.gz](https://github.com/seud0nym/tch-gui-unhide/files/5678192/internet-pppoe-routed.lp.tar.gz)

IPv4 address, gateway and DNS servers are all populating correctly now. Thanks

**Comment by seud0nym** [comment]
Great. I will commit that change to the next release. Thanks for your help as well.
