### ISSUE TITLE
Restoring backup file causing various issues, Including ? disabling firewall...

### ISSUE THREAD

**Issue by rkaycom** [seud0nym/tch-gui-unhide#170]
This might be a big one for you, again using a TG800vac with latest script version, I have also added Adblock and WireGuard. When restoring from fresh backup file it appears that numerous things break. I haven't had the time to fully check things but the most confusing and concerning one is the Firewall settings, when looking at the Firewall card everything appears normal but when opening the card the firewall options display and error stating "invalid parameters" the firewall is also flagged as disabled and set to low security. Has the firewall actually been disabled in this situation or is it a bug with the options menu? I didn't have time to check this morning before work. I am assuming that the cards give accurate information more then the options menus (like with the static lease issue, card displayed correct information and options menu was incorrect)? In anycase, I feel like the restore backup is breaking a lot of things but haven't had the time to check everything.

**Comment by seud0nym** [comment]
Are you talking about importing a configuration file?

Yes, that is a very, very imperfect backup, and I would _strongly_ recommend against using it. It can only restore **configuration** accessible via the OpenWrt `uci` command. It can't restore packages or any other files.

Personally, I never use it.

You can use [mtd-backup](https://github.com/seud0nym/tch-gui-unhide/tree/master/utilities#mtd-backup) and [mtd-restore](https://github.com/seud0nym/tch-gui-unhide/tree/master/utilities#mtd-restore) for bit perfect backup and restore.

You can also use the `--restore-config` option of [reset-to-factory-defaults-with-root](https://github.com/seud0nym/tch-gui-unhide/tree/master/utilities#reset-to-factory-defaults-with-root) as described here: https://github.com/seud0nym/tch-gui-unhide/tree/master/utilities/restore-config#readme. This is better than a config file import, but isn't perfect.

**Comment by rkaycom** [comment]
Yes I am, that's good to know, I will refrain from using that method going forward then. Maybe the configuration file backup option should be disabled by default going forward? Better to not have it then have the option and have it cause issues? I intend on completely resetting the router and reinstalling scripts tonight to verify everything is working correctly and this issue isn't something to do else. I'll then close the issue if it all works out.

**Comment by seud0nym** [comment]
The thing is, it is fine for very simple situations, and some people have simple setups. I would get an outcry from those people, so it is better to have it and just be aware of its limitations.

**Comment by rkaycom** [comment]
Issue not fixed but cause identified.
