### ISSUE TITLE
Restore configuration

### ISSUE THREAD

**Issue by Krazy998** [seud0nym/tch-gui-unhide#174]
Hello!

Just checking that the export and import functionality is supposed to work under the CobraXh card?

When ever I try to import a config backup (export via the same card) I get a import failed error:

![image](https://github.com/seud0nym/tch-gui-unhide/assets/47444724/45a55605-e2ff-4729-8623-cf2fa5c158c9)

In logs I see this message:

Mon Aug 28 07:30:29 2023 daemon.err nginx: 2023/08/28 07:30:29 [error] 13120#0: *384 [lua] gateway-modal.lp"]:163: failed to start receiving file, client: 172.XXX.XXX.XXX, server: localhost, request: "POST /modals/gateway-modal.lp?action=import_config HTTP/1.1", host: "172.XXX.XXX.XXX", referrer: "http://172.XXX.XXX.XXX/?r=1693170410106"
Mon Aug 28 07:30:29 2023 daemon.err nginx[13072]: 2023/08/28 07:30:29 [error] 13120#0: *384 [lua] gateway-modal.lp"]:163: failed to start receiving file, client: 172.XXX.XXX.XXX, server: localhost, request: "POST /modals/gateway-modal.lp?action=import_config HTTP/1.1", host: "172.XXX.XXX.XXX", referrer: "http://172.XXX.XXX.XXX/?r=1693170410106"

Cheers!

**Comment by seud0nym** [comment]
I tried export and import on 21.4.0439, and it worked without error.

What firmware version are you running?

**Comment by Krazy998** [comment]
Hello!

Version I am running: 21.4.0372-MR2-RA

**Comment by seud0nym** [comment]
Very strange. I just loaded up 21.4.0372, made a whole lot of config changes and then exported and imported them, and it worked without error.

Could it be some anti-virus thing blocking the upload of the file?

**Comment by Krazy998** [comment]
OK interesting. Ill do some more testing. I am running a linux desktop and tried both chrome and firefox. Ill test some more when I boot into windows and see if I can reproduce it. For now I think lets close it as It doesnt seem reproducible for you, then I suspect its something on my end.
