### ISSUE TITLE
WAN Static - 4G Failover not working

### ISSUE THREAD

**Issue by mike777z** [seud0nym/tch-gui-unhide#175]
Hi Seud0nym,

I am not too sure if this is an issue with my configuration but was wondering if I could pick your brain.

I have the latest version of tch-gui-unhide on Technicolor DJA0231 running 20.3.c.0389-MR20-RA

I have set static IPs for WAN and set up WWAN with my sim. Sim comes online and works as normal (when i disable WAN) but when WAN is set with static IPs and goes offline I would like it to route to the WWAN sim but testing this, it never routes to WWAN. I have only been successful when I set the WAN to DHCP

**Comment by seud0nym** [comment]
No, I don't think that it is you.

I set up a test with a static IP and Permanent WWAN enabled, and then when I disconnected the WAN cable, I lost connectivity.

When you pull the WAN cable on a DHCP connection, it appears that the default route fully disappears until the cable is reconnected. With a static connection, the default route does not get removed. This is the only difference that I can see.

I will have to have a think and do some research.

**Comment by seud0nym** [comment]
I have pushed up a test release for you to try and see if it fixes your problem. You can apply it with this command:
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```

Please give it a try and let me know how you go.

**Comment by mike777z** [comment]
I updated to the new release and ran some tests, all seems well.  Much appreciated

**Comment by seud0nym** [comment]
Fixed in Release 2023.10.01
