### ISSUE TITLE
Eco Settings inquiry...

### ISSUE THREAD

**Issue by rkaycom** [seud0nym/tch-gui-unhide#176]
This is actually more of a question then an issue but...

With Eco Settings; CPU Frequency Scaling, CPU Wait, Ethernet APD, Energy Efficent Ethernet (sic), AutoGrEEEn and Deep Green Mode.

Can you explain exactly what these feature do or at least point me in the direction to find out, couple of hours of internet searching gave me an idea but not any real detail, so had to say what is and isn't a good idea to enable. What would you recommend?

Oh... And Energy-Efficient Ethernet is misspelled in the Eco Settings tab 🤣

**Comment by seud0nym** [comment]
I will fix the spelling. Thanks.

APD = Auto Power Down. The other ethernet functions are variations on power saving. The CPU ones change the maximum frequency at which the CPU runs.

Best advice is to try changing a setting and then see if you can discern a difference that you find beneficial.

To be honest, I don't find _any_ value in the Eco settings. I never found them to make much difference to throughput or performance. Later firmwares using basically the same CPU and SOC remove the CPU ones.

And there is always a downside to disabling them: without them, the device will use more power and probably run hotter, and hotter electrical components degrade faster.

**Comment by rkaycom** [comment]
Thanks for the insight.
