### ISSUE TITLE
QoS for WWAN?

### ISSUE THREAD

**Issue by gingerninja234** [seud0nym/tch-gui-unhide#177]
Hey @seud0nym,

This is more of a question than a real issue, but does the QoS card apply rules to the WWAN interface as well or is it for the fixed WAN only? 

Thanks again for all the work you are doing!

**Comment by seud0nym** [comment]
The short answer is I don't really know. QoS seems overly-complicated to me, and I tend to leave it alone. I really don't understand how the different configs work together.

Looking at the the interfaces listed on the Egress QoS tab, all LAN interfaces (including Wi-Fi) plus the wired WAN interfaces are listed. But the rules themselves only list interfaces for some rules, which seems to imply that they apply to all interfaces?

Sorry, I just don't know.

**Comment by gingerninja234** [comment]
No worries! Thanks for your reply
It does seem like going down a bit of a rabbit hole! I think you're right that it should apply to everything

Will have a fiddle and see how we go :)
