### ISSUE TITLE
opkg update: wget returned 8

### ISSUE THREAD

**Issue by ECHOSUD** [seud0nym/tch-gui-unhide#178]
I think this issue should be mentioned in the wiki or listed as an open issue. I struggled to find any information online trying to troubleshoot: opkg_download: Failed to download ... , wget returned 8. There is conflicting information online on whether https is allowed through opkg or the ability to update ca-bundle.

_Originally posted by @ECHOSUD in https://github.com/seud0nym/tch-gui-unhide/issues/164#issuecomment-1704521484_

**Comment by seud0nym** [comment]
I will leave this as a pinned open issue.

Troubleshooting steps are:

1. Make sure your CA certificates are up to date by running the [update-ca-certificates](https://github.com/seud0nym/tch-gui-unhide/tree/master/utilities#update-ca-certificates) script.
2. Try and manually download a failed URL through your browser. This should alert you if your IP address has been banned by macoers.com. If that is the case, you should contact [them](https://www.macoers.com/contact) directly and ask to be unblocked.
