### ISSUE TITLE
Telephony card does not display fully and other cards missing

### ISSUE THREAD

**Issue by andrewpthompson** [seud0nym/tch-gui-unhide#18]
I have a problem with only the top part of the Telephony card rendering, and subsequent cards do not display at all, in the advanced page. This is on a DJA0230TLS, firmware 18.1.c.0549-MR17-RB, tch-gui-unhide Version 2020.12.29@16:16:12
![image](https://user-images.githubusercontent.com/25069773/103406959-899a9700-4bac-11eb-8f25-483c880aab71.png)
In the browser console I see `gateway.lp:1 Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING`

This behaviour occurs most of the time but not always. It only occurs when I have telephony enabled. (I have Siptalk configured and working.)

My tch-gui-unhide usage consisted of running these commands on a freshly rooted and factory reset DJA0230:
```
de-telstra -A
tch-gui-unhide -tt
```
and applying the minimum config via the WebUI to get Siptalk working.

I'm still fairly new to tch-gui-unhide so apologies if the problem's on my side or somewhere else. Thanks for all of your brilliant work!

**Comment by seud0nym** [comment]
No, it is definitely a bug.

Yes, it looks like the problem is with the call stats I added to the telephony card. Can you run these commands in PuTTY and post the results?
```
transformer-cli get uci.mmpbxrvsipnet.profile. | grep enabled
transformer-cli get rpc.mmpbx.profilestatistics.
```
Thanks.

**Comment by seud0nym** [comment]
I have found and fixed the problem. There is a new release available new which fixes it.

https://github.com/seud0nym/tch-gui-unhide/releases/tag/2021.01.01

**Comment by andrewpthompson** [comment]
Sorry for the delay in responding - I managed to get VOIP into a non-working state and had to factory reset. I know you've already fixed it but for completeness those commands output:
```
root@DJA0230:~# transformer-cli get uci.mmpbxrvsipnet.profile. | grep enabled
uci.mmpbxrvsipnet.profile.@sip_profile_0.enabled [boolean] = 1
uci.mmpbxrvsipnet.profile.@sip_profile_1.enabled [boolean] = 1
root@DJA0230:~# transformer-cli get rpc.mmpbx.profilestatistics.
rpc.mmpbx.profilestatistics.@sip_profile_0.incomingCallsConnected [string] = 1
rpc.mmpbx.profilestatistics.@sip_profile_0.incomingCalls [string] = 1
rpc.mmpbx.profilestatistics.@sip_profile_0.incomingCallsFailed [string] = 0
rpc.mmpbx.profilestatistics.@sip_profile_0.outgoingCallsConnected [string] = 1
rpc.mmpbx.profilestatistics.@sip_profile_0.profile [string] = sip_profile_0
rpc.mmpbx.profilestatistics.@sip_profile_0.outgoingCallsFailed [string] = 4
rpc.mmpbx.profilestatistics.@sip_profile_0.totalCallDuration [string] = 38
rpc.mmpbx.profilestatistics.@sip_profile_0.droppedCalls [string] = 0
rpc.mmpbx.profilestatistics.@sip_profile_0.outgoingCalls [string] = 5
```
Anyway I've tested the new release and I confirm it fixes the problem. Thanks for this!
