### ISSUE TITLE
Mobile devices cannot connect

### ISSUE THREAD

**Issue by HeyItsJono** [seud0nym/tch-gui-unhide#182]
I have a bit of a strange issue. I've been using tch-gui-unhide with my DJA0231 on 20.3.c for a little over a year now with no issue. A couple of days ago however, a couple of mobile phones in the household began to have connection issues; they would attempt to connect to the network, achieve what seemed like a successful connection, then immediately drop the connection.

If the device was set to autoreconnect it would attempt reconnection and this process would loop causing the phones to overheat. I cannot for some reason get these phones to connect to the wifi network, my laptop and other devices work fine but the phones refuse to connect.

The phones are a Pixel 5 and a Samsung Galaxy 8. I tried forgetting the network, tried randomised MACs, no dice. I tried turning off band steering and connecting individually to either 2.4 or 5GHz, but the issue happens with both. I was on 2023.02.23 and upgraded to 2023.10.01 and the issue persists. Any advice you could offer to troubleshoot this strange issue would be much appreciated.

**Comment by seud0nym** [comment]
It is not going to be an issue with tch-gui-unhide, because it doesn't change anything to do with Wi-Fi. It does add a couple of settings, but apart from that, nothing.

What firmware are you on? Have you updated recently?

The only thing I can think of trying would be to turn on detailed DHCP logging and see if that gives you any info, because if you appear to get a connection then immediately drop, it might by a DHCP issue.

Otherwise, are there any other log messages when you attempt to connect that might give a clue what is going on?

**Comment by HeyItsJono** [comment]
> It is not going to be an issue with tch-gui-unhide, because it doesn't change anything to do with Wi-Fi. It does add a couple of settings, but apart from that, nothing.
> 
> What firmware are you on? Have you updated recently?
> 
> The only thing I can think of trying would be to turn on detailed DHCP logging and see if that gives you any info, because if you appear to get a connection then immediately drop, it might by a DHCP issue.
> 
> Otherwise, are there any other log messages when you attempt to connect that might give a clue what is going on?

Apologies for the delay in response, you were absolutely correct, the issue was my PiHole had silently gone down, and tch-gui-unhide had it set to be the default DNS resolver for the network. Some devices had internal fallbacks built in, but certain mobile devices manifested this issue in simply repeatedly failing to connect to the network. Changing the DNS fixed the issue till I got my PiHole up and running again.
