### ISSUE TITLE
Issue with mobile broadband not recording correct usage

### ISSUE THREAD

**Issue by unclelez** [seud0nym/tch-gui-unhide#183]
Hi again,

I've come across an issue I'm hoping you can help resolve.

I have DJA0321 - 20.3.c.0389-MR20-RA running in Mobile Only mode with a sim from my phone plan. I received a usage alert from Telstra that the sim had used over 800 GB of data but my DJA0231 Mobile Usage History showed only 30 GB of data had been used.

After doing some testing by downloading a 150 MB file, I've noticed the wwan0 interface isn't recording its RX bytes correctly, TX appears fine and tests on my NBN FTTN show usage records are correct.

Any help here to fix this would be great

Mobile Broadband

![image](https://github.com/seud0nym/tch-gui-unhide/assets/112058383/5e34ed7d-838c-42fb-a678-35d035d374b0)

NBN FTTN

![image](https://github.com/seud0nym/tch-gui-unhide/assets/112058383/bbe56434-5be7-4629-b932-298f32d8c79f)

**Comment by seud0nym** [comment]
No, there is nothing that I can do about that.

As you have shown from your analysis, the underlying counters in the operating system just aren't showing the usage. It is probably a similar (although not identical) problem that shows up in the device bandwidth monitor - some usage just appears to get missed by the operating system.

I believe it requires firmware fixes by Technicolor, but that it very unlikely to happen, unless lots and lots of Telstra account holders complain about it.

Sorry.

**Comment by unclelez** [comment]
Thank you for taking the time clarify
