### ISSUE TITLE
Technicolor DJN2130 CWMP Settings tile info doesn't show correct setting

### ISSUE THREAD

**Issue by bravohe** [seud0nym/tch-gui-unhide#185]
Firmware Version | 17.2.0284-820-RA
tch-gui-unhide | 2023.10.01@10:01

![Screenshot 2023-11-24 at 9 20 45 pm](https://github.com/seud0nym/tch-gui-unhide/assets/4607223/d3bba0a1-80c8-429e-9828-90880029b316)
![Screenshot 2023-11-24 at 9 21 33 pm](https://github.com/seud0nym/tch-gui-unhide/assets/4607223/970f8db4-fa10-4925-b83c-ffa2663e3c1f)

**Comment by seud0nym** [comment]
Hi.

Thanks for the report. I believe I have fixed this problem. You can apply the fixed version by running the following command in an SSH session:
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```

Please let me know how it goes.

**Comment by bravohe** [comment]
all good now.
