### ISSUE TITLE
Adguard home installation issue

### ISSUE THREAD

**Issue by AliMickey** [seud0nym/tch-gui-unhide#187]
I am trying to install the AdGuard home add-on following `https://github.com/seud0nym/tch-gui-unhide/tree/master/supplemental/adguard#readme`.

However, I run into this error: `[AdGuard-Home-Setup] ERROR! tch-gui-unhide does not seem to be installed. Aborting...`

I tested on a DJA0230 and DJA0231 with the same issue, both have `tch-gui-unhide` executed multiple times.

If I understood the script correctly, it is due to `rpc.gui.opkg.feeds_configured` not returning a proper value? Although in the GUI:
![image](https://github.com/seud0nym/tch-gui-unhide/assets/60691199/f82bd693-6692-4d14-9911-4d78b048d2f2)

Thanks

**Comment by seud0nym** [comment]
Thanks for finding this bug. I have fixed the `agh-setup` script.

I had to change the way that packages worked in tch-gui-unhide because the macoers repository owner complained about updates happening without any packages being downloaded. However, I forgot that the AdGuard Home setup had a dependency on it.

If you have not already done so, you need to run `de-telstra` with the `-o` option to configure opkg correctly _before_ running `agh-setup`.

**Comment by AliMickey** [comment]
Thank you for the fix, I have re-run `de-telstra` with `-o` and `agh-setup` worked.

There was one error with not much logging as to what it was:

`[hijack-dns] Disabling the cron task
[hijack-dns] Creating/Updating DNS Intereception firewall configuration
[hijack-dns] Configuring IPv4 DNS Hijacking
[hijack-dns] Enabling IPv4 DNS over TLS acceptance for excluded addresses
[hijack-dns] Enabling IPv4 DNS over HTTPS acceptance for excluded addresses
[hijack-dns] Enabling IPv4 DNS over HTTPS IP Set
[hijack-dns] Enabling IPv4 DNS over HTTPS rejection
[hijack-dns] Enabling IPv6 DNS Hijacking
[hijack-dns] Enabling IPv6 DNS over TLS acceptance for excluded addresses
[hijack-dns] Enabling IPv6 DNS over HTTPS acceptance for excluded addresses
[hijack-dns] Enabling IPv6 DNS over HTTPS IP Set
[hijack-dns] Enabling IPv6 DNS over HTTPS rejection
[hijack-dns] Enabling DNS over TLS rejection
[hijack-dns] Enabling script to restore IP Sets on firewall restart
[hijack-dns] Creating scheduled cron task to update DoH IP Sets every Sunday at 3:05
[hijack-dns] Commiting firewall changes
[hijack-dns] Commiting DHCP changes
**Command failed: Not found**
[hijack-dns] Populating ipsets as a background task
[hijack-dns] DONE: DNS hijacking installed
[hijack-dns] Releasing lock on /var/run/hijack-dns.lck...
[AdGuard-Home-Setup] Done. You can now access AdGuard Home on http://10.3.0.1:8008`

**Comment by AliMickey** [comment]
Also, I tested an uninstall and it seems it did not clear the DHCP label:
![image](https://github.com/seud0nym/tch-gui-unhide/assets/60691199/3bff4754-38ba-4d9c-a78a-0891a9eba3d3)

If I click into the local network card I can manage DHCP though, so no issues there. Just a visual bug.

**Comment by seud0nym** [comment]
> [hijack-dns] Commiting DHCP changes
> **Command failed: Not found**

This is okay. It is just because DHCP has been disabled (because AdGuard Home is now managing it).

> Also, I tested an uninstall and it seems it did not clear the DHCP label

I could not reproduce this. 

Did you uninstall with `-r` or `-u`? Are you sure it was still there after you refreshed the screen?

That label should only appear if the following command returns `1`:
```
transformer-cli get rpc.gui.init.files.@AdGuardHome.active
```
If AdGuard Home has been removed, then that command will return `ERROR   invalid instance`

**Comment by AliMickey** [comment]
Sorry, I think I mixed up the steps I performed.

The uninstall works fine, tested now again. But if I run the install script with `-d`, this is when the gui shows AdGuard is performing DHCP when in fact it is not.

![image](https://github.com/seud0nym/tch-gui-unhide/assets/60691199/4d178b06-c906-4d9a-8434-6019ec4f089d)
![image](https://github.com/seud0nym/tch-gui-unhide/assets/60691199/f4b452d2-18a3-43f2-b426-bfbf83eb662e)

**Comment by seud0nym** [comment]
I have also now fixed the LAN card bug. You can apply the fix by running:
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```

**Comment by AliMickey** [comment]
Thank you for that! Appreciate the assistance.
