### ISSUE TITLE
Small bugs

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#19]
Not sure if this is a bug, but thought I'd let you know. Updated to the latest version, and had those weird icon and text close together highlighted in yellow compared to DJA0230 in first box is standard spaced out like it did before with Management and Time of Day.
![Capture](https://user-images.githubusercontent.com/45726972/104116197-379f0180-5362-11eb-94a4-a7b1cc58fb1d.PNG)

**Comment by seud0nym** [comment]
Hmmm... Yes, looks weird. I suppose you tried clearing your cache and refreshing?

**Comment by jmytch** [comment]
Yes I did that "clearing your cache" and "hard reset" then refresh the router page, it still shows the same result as in the picture.

**Comment by seud0nym** [comment]
Which browser are you using? I have tested in both Edge and Firefox and it is working okay...

**Comment by jmytch** [comment]
Strange, and I'm using Edge, on Microsoft Edge is up to date.
Version 87.0.664.75 (Official build) (64-bit)

**Comment by seud0nym** [comment]
I think I have worked it out. It seems to be a problem with the Telstra Classic theme only.

**Comment by jmytch** [comment]
I changed the theme to Telstra Modern, and yes you are correct. The Classic theme only have this weird thing, but all other themes show it correctly. I've set it to modern for now :)

Good find 👍

**Comment by seud0nym** [comment]
Fixed in next release
