### ISSUE TITLE
Feature request: Sort by heading on Static Leases table.

### ISSUE THREAD

**Issue by pencilhead1** [seud0nym/tch-gui-unhide#190]
Hi, 

Would it be possible to have heading sort on Static Leases table.
(Local Network / Static Leases).
ie Be able to sort by MAC Address / Host Name / IP Address.

The Connected Devices table has this functionality 
(Local Network / Connected Devices).

Thanks :)

**Comment by seud0nym** [comment]
Thanks for the suggestion.

The first issue that comes to mind is that static leases take a long time to load for some reason that I have not been able to determine, so sorting will also be slow.

I will have a think about it.

**Comment by seud0nym** [comment]
I have done this and it will be in the next release.

**Comment by seud0nym** [comment]
Added in release 2024.02.29
