### ISSUE TITLE
Your GUI can be used on my technicolor tg789vac v2

### ISSUE THREAD

**Issue by SBH-WEB-DEV** [seud0nym/tch-gui-unhide#193]
Hello 

I have used GUI on ansuel on my technicolor tg789vac v2

Actually i use official software ( i deleted GUI ansuel )

I would like it is possible to use your gui on ly technicolor

Your GUI is diffrent as ansuel or same 

Thanks a lot

**Comment by seud0nym** [comment]
It should work on any Telstra branded device with firmware 17.2 or later.

It has a different way of doing things to the Ansuel GUI. It is less invasive on the device, and targeted at only Telstra devices.

**Comment by SBH-WEB-DEV** [comment]
So i tested it sir on my  technicolor tg789vac v2 VANT 6 or not my Friend

**Comment by seud0nym** [comment]
I just looked in the Firmware repository:
https://hack-technicolor.readthedocs.io/en/stable/Repository/#tg789vac-v2-vant-6

There is no Telstra firmware for this device, so it will _not_ work. Sorry.
