### ISSUE TITLE
Compatibility with DNA0332 CobraXh

### ISSUE THREAD

**Issue by alan665** [seud0nym/tch-gui-unhide#196]
Hi,

I really love the work you have put into tch-gui-unhide, been using it on a DJA0231 for a couple of days now.

Is it compatible with the newer Telstra smart modem 3?

**Comment by pencilhead1** [comment]
Yes, but you need to follow the bootp guide to downgrade. After that you can upgrade/install etc.

**Comment by alan665** [comment]
Thanks very much!
