### ISSUE TITLE
Wireguard tunnel when in bridged mode (DJA0231)

### ISSUE THREAD

**Issue by alan665** [seud0nym/tch-gui-unhide#197]
Hi,

Is it possible to use your userspace wireguard script when the router is in bridged mode?

Cheers,
Al

**Comment by seud0nym** [comment]
Not as far as I am aware.

From my understanding (and I am not a networking expert), bridging happens at what is called Layer 2. Things like firewalls and WireGuard happen at Layer 3, so the WAN packets pass 'beneath' the layer that WireGuard can see.
