### ISSUE TITLE
QoS Card and Theme Colours

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#2]
How do I go on adding the QoS card? I did the de-telstra with your scripts, it seems to work very nicely and remove those telstra air ssid which is a bonus. I'm on FTTN, and would like to have QoS card, how do I do this as there is no instruction on how to add it

**Comment by jmytch** [comment]
![Capture](https://user-images.githubusercontent.com/45726972/93281282-20fef880-f80f-11ea-9f84-bc1ccb3b0496.PNG)
Suggestion, are you able to remove those underscores, if you look at the red boxes, the default ones have underscore compared to unlocking tiles doesnt have underscore. I would prefer to have no underscores in those wording.

**Comment by seud0nym** [comment]
I assume you downloaded release 2020.09.06? 

After running `./de-telstra`, I assume you ran `./tch-gui-unhide`? 

The QoS card should just appear in that release. I am about to do a new release that will only show the QoS card if a WAN interface is defined, but the current release doesn't check that.

Can you please run the following commands and post the output:
```
uci show web.qosqueuemodal
uci show web.qosclassifymodal
```
For the styling issues, maybe you just forgot to clear your browser cache of images and files? You are just running with the default style sheet. Just re-run `./tch-gui-unhide` (or `./tch-gui-unhide -tn` for the night theme, and then clear your browser cache and refresh the screen.

**Comment by jmytch** [comment]
Gotcha, was missing the `./tch-gui-unhide` part, and pressed Y to continue that step. I can now see the QoS card, thanks :) and the styling issues is now looking nice than before XD

For some reason when I use ./tch-gui-unhide -t night, then switch back to ./tch-gui-unhide -t light it doesnt revert back to light theme, even I did clear browser cache

**Comment by jmytch** [comment]
![Capture](https://user-images.githubusercontent.com/45726972/93285404-16952c80-f818-11ea-82d3-53fe77882153.PNG)
Here is the snip after ran that light theme but still applies for night theme as you can see. Pretty sure this will be fixed :-)

**Comment by seud0nym** [comment]
That's strange. I was sure I had tried that multiple times.

Anyway, I have made a lot of changes to theming in the next release: there are 4 night theme colour variations, plus the ability to apply a theme without re-applying all the other changes. I am pretty sure that it switches properly now.

**Comment by jmytch** [comment]
No problem, and looking forward to it. Thanks

**Comment by jmytch** [comment]
Updated to the latest version, tried all the themes and it works nicely 👍  thanks for that.

Other suggestion, you should do the purple, green, orange with the light themes too for those who want light but with purple for example.

**Comment by seud0nym** [comment]
Applying colours to light theme is in next release
