### ISSUE TITLE
Devices card never loads...

### ISSUE THREAD

**Issue by rkaycom** [seud0nym/tch-gui-unhide#201]
As above. Updated to the new version to fix
 Issue 199. But now device card never loads. Just spirals forever.

Technicolor TG800vac
Software Version 17.2
Firmware Version 17.2.0284-820-RA
tch-gui-unhide Version 2024.06.03

**Comment by seud0nym** [comment]
Thanks for the report.

It should be fixed now. Run this command to apply the fix:
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```

**Comment by seud0nym** [comment]
Fixed in release 2024.10.10.
