### ISSUE TITLE
Wifi Devices List under Devices Card don't show any wifi devices but wireless client monitor under Wifi Card show many clients

### ISSUE THREAD

**Issue by bravohe** [seud0nym/tch-gui-unhide#202]
![Screenshot 2024-06-17 at 11 52 45 PM](https://github.com/seud0nym/tch-gui-unhide/assets/4607223/9998263e-3cd4-4462-8cdf-2c4955a6b30a)
![Screenshot 2024-06-18 at 12 04 56 AM](https://github.com/seud0nym/tch-gui-unhide/assets/4607223/5bfa66ff-065e-4c78-a668-ab3553d18d47)

> transformer-cli get rpc.wireless.ap.|grep station |grep  state

![Screenshot 2024-06-18 at 12 10 12 AM](https://github.com/seud0nym/tch-gui-unhide/assets/4607223/8da1d2ef-9874-4510-901b-23f4a5cd3746)

**Comment by seud0nym** [comment]
Which firmware version?

**Comment by bravohe** [comment]
Technicolor DJA0231
firmware:20.3.c.0389-MR20-RA

"I have found the WiFi device card it will check 'transformer-cli get sys.hosts.host.' first, and then check 'transformer-cli get rpc.wireless.ap.'. Since my SMG2 is only an access point, there is no record on 'sys.hosts.host.' for the SMG2, and therefore no result."
