### ISSUE TITLE
Devices card never loads when the number of Booster Wi-Fi device is greater than 0

### ISSUE THREAD

**Issue by bravohe** [seud0nym/tch-gui-unhide#203]
Technicolor DJA0231
Firmware Version 20.3.c.0501-MR22.1-RA
tch-gui-unhide Version 2024.06.05@15:30

Device card never  load when  the number of Booster Wi-Fi device is greater than 0

![Screenshot 2024-06-28 at 11 20 47 PM](https://github.com/seud0nym/tch-gui-unhide/assets/4607223/774715c9-bccb-47fe-8846-72f08f73fa50)

log error msg as below:
Fri Jun 28 21:05:00 2024 daemon.err nginx: 2024/06/28 21:05:00 [error] 10668#0: *20 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #3 to 'format' (no value) stack traceback: coroutine 0: 	[C]: in function 'format' 	/usr/lib/lua/web/taint.lua:280: in function 'format' 	/www/lua/devices_helper.lua:186: in function 'getWiFi' 	[string "/modals/device-modal.lp"]:71: in function 'content' 	/usr/lib/lua/web/web.lua:249: in function 'process' 	content_by_lua(nginx.conf:128):4: in function <content_by_lua(nginx.conf:128):1>, client: 192.168.1.9, server: localhost, request: "GET /modals/device-modal.lp?dev=1 HTTP/1.1", host: "192.168.1.54", referrer: "http://192.168.1.54/gateway.lp"
Fri Jun 28 21:05:00 2024 daemon.err nginx[10652]: 	/usr/lib/lua/web/web.lua:249: in function 'process'

I have checked file /www/lua/devices_helper.lua and I only can see line 179 variable mac didn't be declared.
Don't know is it relative?

**Comment by seud0nym** [comment]
I have made a few changes to Devices since 2024.06.05.

I have uploaded a new testing release. Please give it a try and see if the problem is still there.
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```

Let me know how you go.

**Comment by bravohe** [comment]
I have updated to 2024.06.29@09:55 but the log file still show error msg as below:

Sat Jun 29 16:28:49 2024 daemon.err nginx: 2024/06/29 16:28:48 [error] 17765#0: *3 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #3 to 'format' (no value) stack traceback: coroutine 0: 	[C]: in function 'format' 	/usr/lib/lua/web/taint.lua:280: in function 'format' 	/www/lua/devices_helper.lua:257: in function 'getWiFi' 	[string "/modals/device-modal.lp"]:71: in function 'content' 	/usr/lib/lua/web/web.lua:249: in function 'process' 	content_by_lua(nginx.conf:129):4: in function <content_by_lua(nginx.conf:129):1>, client: 192.168.1.9, server: localhost, request: "GET /modals/device-modal.lp?dev=1 HTTP/1.1", host: "192.168.1.54", referrer: "http://192.168.1.54/gateway.lp?r=1719633443193"
Sat Jun 29 16:28:49 2024 daemon.err nginx[17717]: 	/usr/lib/lua/web/web.lua:249: in function 'process'

**Comment by seud0nym** [comment]
Well, that is disappointing :-(

Can you post the output of:
```
transformer-cli get Device.Services.X_TELSTRA_MultiAP.Agent. | sort
``

Thanks.

**Comment by bravohe** [comment]
okay.

`Device.Services.X_TELSTRA_MultiAP.Agent.1.UpTime [unsignedInt] = 
Device.Services.X_TELSTRA_MultiAP.Agent.1.IEEE1905Id [string] = D6:35:1D:AF:11:5D
Device.Services.X_TELSTRA_MultiAP.Agent.1.TotalMemory [unsignedInt] = 
Device.Services.X_TELSTRA_MultiAP.Agent.1.BSSID2GHZ [string] = D4:35:1D:AF:11:5D
Device.Services.X_TELSTRA_MultiAP.Agent.1.LED [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.1.AssociatedDeviceNumberOfEntries [unsignedInt] = 1
Device.Services.X_TELSTRA_MultiAP.Agent.1.BSSID5GHZ [string] = D6:35:1D:AF:11:65
Device.Services.X_TELSTRA_MultiAP.Agent.1.MaxAssociatedDevices [unsignedInt] = 32
Device.Services.X_TELSTRA_MultiAP.Agent.1.Alias [string] = Telstra-AF115D
Device.Services.X_TELSTRA_MultiAP.Agent.1.ManufacturerName [string] = Technicolor
Device.Services.X_TELSTRA_MultiAP.Agent.1.BSSID2GHZ_Backhaul [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.1.ModelNumber [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.1.SerialNumber [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.1.SignalStrength [int] = -127
Device.Services.X_TELSTRA_MultiAP.Agent.1.IPAddress [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.1.LEDColor [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.1.ParentAccessPoint [string] = A4:91:B1:76:BF:AD
Device.Services.X_TELSTRA_MultiAP.Agent.1.LastDataLinkRate [unsignedInt] = 1000
Device.Services.X_TELSTRA_MultiAP.Agent.1.MACAddress [string] = D4:35:1D:AF:11:5C
Device.Services.X_TELSTRA_MultiAP.Agent.1.ConnectionType [string] = Ethernet
Device.Services.X_TELSTRA_MultiAP.Agent.1.SoftwareVersion [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.1.HardwareVersion [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.1.FactoryResetTime [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.1.PowerOnTime [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.1.FreeMemory [unsignedInt] = 
Device.Services.X_TELSTRA_MultiAP.Agent.1.BSSID5GHZ_Backhaul [string] = D6:35:1D:AF:11:66
Device.Services.X_TELSTRA_MultiAP.Agent.1.STA.5.SignalStrength [int] = -37
Device.Services.X_TELSTRA_MultiAP.Agent.1.STA.5.OperatingStandard [string] = n
Device.Services.X_TELSTRA_MultiAP.Agent.1.STA.5.MACAddress [string] = B4:18:D1:C7:B5:24
Device.Services.X_TELSTRA_MultiAP.Agent.1.STA.5.BSSID [string] = D6:35:1D:AF:11:65
Device.Services.X_TELSTRA_MultiAP.Agent.1.STA.5.Active [boolean] = 1
Device.Services.X_TELSTRA_MultiAP.Agent.1.STA.5.LastDataUplinkRate [unsignedInt] = 24000
Device.Services.X_TELSTRA_MultiAP.Agent.1.STA.5.AuthenticationState [boolean] = 1
Device.Services.X_TELSTRA_MultiAP.Agent.1.STA.5.Retransmissions [unsignedInt] = 0
Device.Services.X_TELSTRA_MultiAP.Agent.1.STA.5.LastDataDownlinkRate [unsignedInt] = 270000
Device.Services.X_TELSTRA_MultiAP.Agent.1.STA.5.Stats.BytesReceived [unsignedLong] = 807394
Device.Services.X_TELSTRA_MultiAP.Agent.1.STA.5.Stats.PacketsSent [unsignedLong] = 6148
Device.Services.X_TELSTRA_MultiAP.Agent.1.STA.5.Stats.BytesSent [unsignedLong] = 2491320
Device.Services.X_TELSTRA_MultiAP.Agent.1.STA.5.Stats.PacketsReceived [unsignedLong] = 12231
Device.Services.X_TELSTRA_MultiAP.Agent.1.STA.5.Stats.RetransCount [unsignedInt] = 0
Device.Services.X_TELSTRA_MultiAP.Agent.1.STA.5.Stats.ErrorsSent [unsignedInt] = 0
Device.Services.X_TELSTRA_MultiAP.Agent.2.UpTime [unsignedInt] = 
Device.Services.X_TELSTRA_MultiAP.Agent.2.IEEE1905Id [string] = A6:91:B1:AB:B5:DB
Device.Services.X_TELSTRA_MultiAP.Agent.2.TotalMemory [unsignedInt] = 
Device.Services.X_TELSTRA_MultiAP.Agent.2.BSSID2GHZ [string] = A4:91:B1:AB:B5:DB
Device.Services.X_TELSTRA_MultiAP.Agent.2.LED [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.2.AssociatedDeviceNumberOfEntries [unsignedInt] = 3
Device.Services.X_TELSTRA_MultiAP.Agent.2.BSSID5GHZ [string] = A6:91:B1:AB:B5:E3
Device.Services.X_TELSTRA_MultiAP.Agent.2.MaxAssociatedDevices [unsignedInt] = 32
Device.Services.X_TELSTRA_MultiAP.Agent.2.Alias [string] = Telstra-ABB5DB
Device.Services.X_TELSTRA_MultiAP.Agent.2.ManufacturerName [string] = Technicolor
Device.Services.X_TELSTRA_MultiAP.Agent.2.BSSID2GHZ_Backhaul [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.2.ModelNumber [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.2.SerialNumber [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.2.SignalStrength [int] = -127
Device.Services.X_TELSTRA_MultiAP.Agent.2.IPAddress [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.2.LEDColor [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.2.ParentAccessPoint [string] = A4:91:B1:76:BF:AD
Device.Services.X_TELSTRA_MultiAP.Agent.2.LastDataLinkRate [unsignedInt] = 1000
Device.Services.X_TELSTRA_MultiAP.Agent.2.MACAddress [string] = A4:91:B1:AB:B5:DA
Device.Services.X_TELSTRA_MultiAP.Agent.2.ConnectionType [string] = Ethernet
Device.Services.X_TELSTRA_MultiAP.Agent.2.SoftwareVersion [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.2.HardwareVersion [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.2.FactoryResetTime [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.2.PowerOnTime [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.2.FreeMemory [unsignedInt] = 
Device.Services.X_TELSTRA_MultiAP.Agent.2.BSSID5GHZ_Backhaul [string] = A6:91:B1:AB:B5:E4
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.1.SignalStrength [int] = -59
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.1.OperatingStandard [string] = ac
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.1.MACAddress [string] = C8:99:B2:A8:97:4D
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.1.BSSID [string] = A6:91:B1:AB:B5:E4
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.1.Active [boolean] = 1
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.1.LastDataUplinkRate [unsignedInt] = 1300000
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.1.AuthenticationState [boolean] = 1
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.1.Retransmissions [unsignedInt] = 0
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.1.LastDataDownlinkRate [unsignedInt] = 1170000
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.1.Stats.BytesReceived [unsignedLong] = 106747037
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.1.Stats.PacketsSent [unsignedLong] = 434378
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.1.Stats.BytesSent [unsignedLong] = 172244056
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.1.Stats.PacketsReceived [unsignedLong] = 355863
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.1.Stats.RetransCount [unsignedInt] = 0
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.1.Stats.ErrorsSent [unsignedInt] = 0
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.3.SignalStrength [int] = -63
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.3.OperatingStandard [string] = n
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.3.MACAddress [string] = 34:3E:A4:6C:AD:E0
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.3.BSSID [string] = A4:91:B1:AB:B5:DB
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.3.Active [boolean] = 1
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.3.LastDataUplinkRate [unsignedInt] = 72000
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.3.AuthenticationState [boolean] = 1
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.3.Retransmissions [unsignedInt] = 0
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.3.LastDataDownlinkRate [unsignedInt] = 65000
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.3.Stats.BytesReceived [unsignedLong] = 196667236
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.3.Stats.PacketsSent [unsignedLong] = 95598
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.3.Stats.BytesSent [unsignedLong] = 12873750
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.3.Stats.PacketsReceived [unsignedLong] = 163371
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.3.Stats.RetransCount [unsignedInt] = 0
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.3.Stats.ErrorsSent [unsignedInt] = 0
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.4.SignalStrength [int] = -57
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.4.OperatingStandard [string] = ac
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.4.MACAddress [string] = 3A:D9:5D:9A:50:5F
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.4.BSSID [string] = A6:91:B1:AB:B5:E3
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.4.Active [boolean] = 1
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.4.LastDataUplinkRate [unsignedInt] = 866000
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.4.AuthenticationState [boolean] = 1
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.4.Retransmissions [unsignedInt] = 0
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.4.LastDataDownlinkRate [unsignedInt] = 866000
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.4.Stats.BytesReceived [unsignedLong] = 6068948
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.4.Stats.PacketsSent [unsignedLong] = 44895
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.4.Stats.BytesSent [unsignedLong] = 75210108
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.4.Stats.PacketsReceived [unsignedLong] = 21960
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.4.Stats.RetransCount [unsignedInt] = 0
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.4.Stats.ErrorsSent [unsignedInt] = 0
Device.Services.X_TELSTRA_MultiAP.Agent.3.UpTime [unsignedInt] = 90105
Device.Services.X_TELSTRA_MultiAP.Agent.3.IEEE1905Id [string] = CA:99:B2:A8:97:4C
Device.Services.X_TELSTRA_MultiAP.Agent.3.TotalMemory [unsignedInt] = 508068
Device.Services.X_TELSTRA_MultiAP.Agent.3.BSSID2GHZ [string] = 6A:99:B2:A8:97:4F
Device.Services.X_TELSTRA_MultiAP.Agent.3.LED [string] = Normal
Device.Services.X_TELSTRA_MultiAP.Agent.3.AssociatedDeviceNumberOfEntries [unsignedInt] = 1
Device.Services.X_TELSTRA_MultiAP.Agent.3.BSSID5GHZ [string] = 72:99:B2:A8:97:40
Device.Services.X_TELSTRA_MultiAP.Agent.3.MaxAssociatedDevices [unsignedInt] = 32
Device.Services.X_TELSTRA_MultiAP.Agent.3.Alias [string] = Telstra-A8974C
Device.Services.X_TELSTRA_MultiAP.Agent.3.ManufacturerName [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.3.BSSID2GHZ_Backhaul [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.3.ModelNumber [string] = WE7202242-TA
Device.Services.X_TELSTRA_MultiAP.Agent.3.SerialNumber [string] = MAP2221167472
Device.Services.X_TELSTRA_MultiAP.Agent.3.SignalStrength [int] = -61
Device.Services.X_TELSTRA_MultiAP.Agent.3.IPAddress [string] = 192.168.3.251
Device.Services.X_TELSTRA_MultiAP.Agent.3.LEDColor [string] = Blue
Device.Services.X_TELSTRA_MultiAP.Agent.3.ParentAccessPoint [string] = A6:91:B1:AB:B5:E4
Device.Services.X_TELSTRA_MultiAP.Agent.3.LastDataLinkRate [unsignedInt] = 55888
Device.Services.X_TELSTRA_MultiAP.Agent.3.MACAddress [string] = C8:99:B2:A8:97:4D
Device.Services.X_TELSTRA_MultiAP.Agent.3.ConnectionType [string] = Unknown
Device.Services.X_TELSTRA_MultiAP.Agent.3.SoftwareVersion [string] = 3.00.07_01
Device.Services.X_TELSTRA_MultiAP.Agent.3.HardwareVersion [string] = R01
Device.Services.X_TELSTRA_MultiAP.Agent.3.FactoryResetTime [string] = 2024-06-13 15:10:07
Device.Services.X_TELSTRA_MultiAP.Agent.3.PowerOnTime [string] = 2024-06-28 22:16:23
Device.Services.X_TELSTRA_MultiAP.Agent.3.FreeMemory [unsignedInt] = 296308
Device.Services.X_TELSTRA_MultiAP.Agent.3.BSSID5GHZ_Backhaul [string] = 62:99:B2:A8:97:48
Device.Services.X_TELSTRA_MultiAP.Agent.3.STA.1.SignalStrength [int] = -57
Device.Services.X_TELSTRA_MultiAP.Agent.3.STA.1.OperatingStandard [string] = n
Device.Services.X_TELSTRA_MultiAP.Agent.3.STA.1.MACAddress [string] = 38:86:F7:DB:FD:13
Device.Services.X_TELSTRA_MultiAP.Agent.3.STA.1.BSSID [string] = 6A:99:B2:A8:97:4F
Device.Services.X_TELSTRA_MultiAP.Agent.3.STA.1.Active [boolean] = 1
Device.Services.X_TELSTRA_MultiAP.Agent.3.STA.1.LastDataUplinkRate [unsignedInt] = 65000
Device.Services.X_TELSTRA_MultiAP.Agent.3.STA.1.AuthenticationState [boolean] = 1
Device.Services.X_TELSTRA_MultiAP.Agent.3.STA.1.Retransmissions [unsignedInt] = 19266
Device.Services.X_TELSTRA_MultiAP.Agent.3.STA.1.LastDataDownlinkRate [unsignedInt] = 1000
Device.Services.X_TELSTRA_MultiAP.Agent.3.STA.1.Stats.BytesReceived [unsignedLong] = 51417433
Device.Services.X_TELSTRA_MultiAP.Agent.3.STA.1.Stats.PacketsSent [unsignedLong] = 81505
Device.Services.X_TELSTRA_MultiAP.Agent.3.STA.1.Stats.BytesSent [unsignedLong] = 140266241
Device.Services.X_TELSTRA_MultiAP.Agent.3.STA.1.Stats.PacketsReceived [unsignedLong] = 90692
Device.Services.X_TELSTRA_MultiAP.Agent.3.STA.1.Stats.RetransCount [unsignedInt] = 19266
Device.Services.X_TELSTRA_MultiAP.Agent.3.STA.1.Stats.ErrorsSent [unsignedInt] = 0
Device.Services.X_TELSTRA_MultiAP.Agent.4.UpTime [unsignedInt] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.IEEE1905Id [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.TotalMemory [unsignedInt] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.BSSID2GHZ [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.LED [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.AssociatedDeviceNumberOfEntries [unsignedInt] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.BSSID5GHZ [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.MaxAssociatedDevices [unsignedInt] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.Alias [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.ManufacturerName [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.BSSID2GHZ_Backhaul [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.ModelNumber [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.SerialNumber [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.SignalStrength [int] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.IPAddress [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.LEDColor [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.ParentAccessPoint [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.LastDataLinkRate [unsignedInt] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.MACAddress [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.ConnectionType [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.SoftwareVersion [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.HardwareVersion [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.FactoryResetTime [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.PowerOnTime [string] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.FreeMemory [unsignedInt] = 
Device.Services.X_TELSTRA_MultiAP.Agent.4.BSSID5GHZ_Backhaul [string] = `

**Comment by seud0nym** [comment]
Thanks. Still can't see what is causing it, and I can't reproduce in my test environment.

So, I have added some code to prevent it falling over when it fits that particular situation, plus it will log a message containing the MAC  and path of the actual device which is causing the error.

Please update to the latest test release with:
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```

Can you then look at the log when/after opening the Devices screen, and look for an error message that starts with: `Could not determine frequency band`. The error message will contain `path=`something; could you then execute this command, substituting in something for the path:
```
transformer-cli get path
```
Thanks.

**Comment by bravohe** [comment]
After upgrade to tch-gui-unhide version 2024.06.30@14:28 teh Devices card could show devices and the log error msg is 

`Mon Jul  1 08:47:48 2024 daemon.err nginx[12413]: 2024/07/01 08:47:48 [error] 12468#0: *3 [lua] devices_helper.lua:261: getWiFi(): Could not determine frequency band for C8:99:B2:A8:97:4D path=Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7., client: 192.168.1.9, server: localhost, request: "GET /modals/device-modal.lp?dev=1 HTTP/1.1", host: "192.168.1.54", referrer: "http://192.168.1.54/gateway.lp?r=1719787380110"
`

transformer-cli get Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7. result is
`Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7.SignalStrength [int] = -58
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7.OperatingStandard [string] = ac
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7.MACAddress [string] = C8:99:B2:A8:97:4D
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7.BSSID [string] = A6:91:B1:AB:B5:E4
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7.Active [boolean] = 1
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7.LastDataUplinkRate [unsignedInt] = 1170000
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7.AuthenticationState [boolean] = 1
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7.Retransmissions [unsignedInt] = 0
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7.LastDataDownlinkRate [unsignedInt] = 1053000
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7.Stats.BytesReceived [unsignedLong] = 1317108329
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7.Stats.PacketsSent [unsignedLong] = 603640
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7.Stats.BytesSent [unsignedLong] = 145069423
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7.Stats.PacketsReceived [unsignedLong] = 1340060
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7.Stats.RetransCount [unsignedInt] = 0
Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7.Stats.ErrorsSent [unsignedInt] = 0`

Please note: Device.Services.X_TELSTRA_MultiAP.Agent.2.STA.7. device is 'Telstra Smart Booster 3'

**Comment by seud0nym** [comment]
Excellent! Thank you.

So, the issue is that when I try and find the frequency band to which the STA device is connected, I was not looking at the backhaul SSIDs, which is why the Gen 3 booster was the problem.

Please update to the latest test release with:
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```

You should no longer see the error message in the log, and the frequency band for the booster in the Interface column should be suffixed with `(BH)`.

**Comment by bravohe** [comment]
All good now.
