### ISSUE TITLE
Wireguard card fails

### ISSUE THREAD

**Issue by nroach44** [seud0nym/tch-gui-unhide#204]
Hi, thanks for your work on this!

I'm trying to use the wireguard client with my DJA0231 (on 20.3), but at some point (typically after a reboot) the wireguard connection won't come up, and the card will bring up a spinner and never load when clicked.

The following shows in `logread -f` at the time:

```
Thu Jun 27 20:39:45 2024 daemon.err nginx: 2024/06/27 20:39:45 [error] 7681#0: *117 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #2 to 'format' (string expected, got nil) stack traceback: coroutine 0: 	[C]: in function 'format' 	/usr/lib/lua/web/taint.lua:280: in function 'format' 	[string "/modals/wireguard-modal.lp"]:297: in function 'content' 	/usr/lib/lua/web/web.lua:249: in function 'process' 	content_by_lua(nginx.conf:128):4: in function <content_by_lua(nginx.conf:128):1>, client: <<CLIENT>>, server: localhost, request: "GET /modals/wireguard-modal.lp HTTP/1.1", host: "<<DJA0231>>", referrer: "http://<<DJA0231>>/gateway.lp"
Thu Jun 27 20:39:45 2024 daemon.err nginx[7549]: 2024/06/27 20:39:45 [error] 7681#0: *117 lua entry thread aborted: runtime error: /usr/lib/lua/web/taint.lua:280: bad argument #2 to 'format' (string expected, got nil)
Thu Jun 27 20:39:45 2024 daemon.err nginx[7549]: stack traceback:
Thu Jun 27 20:39:45 2024 daemon.err nginx[7549]: coroutine 0:
Thu Jun 27 20:39:45 2024 daemon.err nginx[7549]: 	[C]: in function 'format'
Thu Jun 27 20:39:45 2024 daemon.err nginx[7549]: 	/usr/lib/lua/web/taint.lua:280: in function 'format'
Thu Jun 27 20:39:45 2024 daemon.err nginx[7549]: 	[string "/modals/wireguard-modal.lp"]:297: in function 'content'
Thu Jun 27 20:39:45 2024 daemon.err nginx[7549]: 	/usr/lib/lua/web/web.lua:249: in function 'process'
Thu Jun 27 20:39:45 2024 daemon.err nginx[7549]: 	content_by_lua(nginx.conf:128):4: in function <content_by_lua(nginx.conf:128):1>, client: <<CLIENT>>, server: localhost, request: "GET /modals/wireguard-modal.lp HTTP/1.1", host: "<<DJA0231>>", referrer: "http://<<DJA0231>>/gateway.lp"
```

So far I've only managed to fix this by factory resetting the device.

So far I have tried

* Rebooting the unit
* Removing the config file in `/var/wireguard`
* Uninstalling the `wireguard` package, uninstalling the extra, and re-installing

**Comment by nroach44** [comment]
After inspecting the source ( extras/src/wireguard/www/docroot/modals/wireguard-modal.lp#L297 ) I messed around with DDNS settings.

Setting up a placeholder no-ip account fixed it. I imagine that having the fixed WAN connected (prior) with a working reverse IP satisfied this requirement originally..?

**Comment by seud0nym** [comment]
Did you delete all the Dynamic DNS entries at some time? 

That is the only thing I can think of that would cause what you are seeing. 

The way DDNS is setup in the stock firmware is that there are always 2 and only 2 DDNS entries (one each for IPV4 and one for IPV6). However, I recently changed it so that you can define as many as you want. I changed the Wireguard extra to find a DDNS WAN entry, but I haven't allowed for there to be _NO_ DDNS entries. 

You could have fixed it by just re-adding a disabled DDNS entry with a domain of yourhost.example.com, which is the Telstra default when there are none defined. 

I will have to add a check to deal with none being found, in which case it will do the default thing and use the current WAN address. Although, unless you have a static WAN IP,  you are better off with a domain and DDNS anyway.

**Comment by nroach44** [comment]
Up until I fixed it earlier today, I don't think I'd ever been in that menu.

I did clear the two placeholder entries **after** it broke, to no avail.

I suspect I might be triggering this issue as I'm using the DJA0231 purely as a travel 4G router, and it only gets a normal WAN connection when it's at home testing.

**Comment by seud0nym** [comment]
Pity. The logged error in your first comment is definitely caused by the absence of the DDNS entries, so the actual problem you were having may be lost.

I will try and reproduce it using Wireguard when running on a SIM (but not tonight :-).

**Comment by nroach44** [comment]
It was definitely the same message, I was pretty disappointed that I didn't get some other variant.

Just a heads up, my unit had been running for a few reboots this time before I triggered it, so it might take a few to kick it off.

**Comment by seud0nym** [comment]
Couldn't reproduce it (but I may not have been patient enough).

I have put up a new version of the extra script which will better handle the situation where there is no WAN IP and no Dynamic DNS entries.

Please give it a try and let me know how you go.

**Comment by nroach44** [comment]
Just putting this here to stop the bot, I'm testing it now...

**Comment by nroach44** [comment]
Okay, can confirm that the moment I deleted the dyndns entry, the wg card failed.
I replaced the file you changed in that commit and it instantly fixed it, without re-installing or even rebooting.
