### ISSUE TITLE
17,1 

### ISSUE THREAD

**Issue by kwstasch** [seud0nym/tch-gui-unhide#208]
Hello how can i install your script on 17.1 version;

**Comment by kwstasch** [comment]
Product: vant-6
Release: Gold (17.1)
Version: 17.1.8049-0001009-20200121114631-559df4882772ac0572ccc3536671901d62896c14

**Comment by seud0nym** [comment]
TG789vac v2 is not a Telstra branded device, and I do not support non-Telstra devices, nor do I support firmware prior to 17.2.

You should try https://github.com/Ansuel/tch-nginx-gui. That mod supports a lot of older devices.
