### ISSUE TITLE
Minification breaks 'wi-fi' card in 2024.08.04

### ISSUE THREAD

**Issue by browntownington** [seud0nym/tch-gui-unhide#209]
After some tinkering today, enabling minification on 2024.08.04 I notified I get transparent overlay (no spinning wheel) when I click the wi-fi card, until I click and am return to the cards view.

This may be similar to:
https://github.com/seud0nym/tch-gui-unhide/issues/201
https://github.com/seud0nym/tch-gui-unhide/issues/206

I have another device running 2024.05.31 and seems it's similar issue except it gets the spinning wheel before going to the transparent overlay.

**Comment by seud0nym** [comment]
Which devices?

**Comment by seud0nym** [comment]
Never mind. It only seems to affect the Gen 3 on firmware 21.4.

You can apply the fix with this command:
```
./tch-gui-unhide -u && ./tch-gui-unhide -y
```

**Comment by browntownington** [comment]
Oops yep should have mentioned Cobra's.

That fixed it many thanks!

**Comment by seud0nym** [comment]
Fixed in release 2024.10.10.
