### ISSUE TITLE
DSL bug

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#21]
Upon disabling DSL in the Broadband card and saved. Then went back inside it, the DSL status remain to say up even it is disabled.
When disable DSL it should say DSL status down 
![Capture](https://user-images.githubusercontent.com/45726972/106463101-afd09100-64e2-11eb-8685-9493860cd178.PNG)

**Comment by seud0nym** [comment]
That is a bit weird. That code is a straight import from the Ansuel tch-nginx-gui. The only change I made was to remove some code that prevented you from turning it on/off unless you had a user role that the Telstra devices don't have, and that change was 4 months ago!

Has it just started happening?

**Comment by jmytch** [comment]
Oh, DSL Enabled was on by default but I was turning that button to Off for DSL Enabled so it could say DSL Status to go Down but that is not the case, it would still display as "Up" while DSL Enabled are set to off.

Was doing this to test the 4G Backup, and yeah had to go in the internet card to turn off the internet access. If the broadband card DSL are down as indicated then 4G Backup would get connectivity?

**Comment by seud0nym** [comment]
I would have expected it to turn off DSL, as you would.

I have checked the stock GUI and it does exactly the same thing as the Ansuel code I imported (in relation to enabling/disabling).

You can run this command to see what the current status is (1 = enabled, 0 = disabled)

``` 
transformer-cli get sys.class.xdsl.@line0.Enable
```

You can test your 4G backup my going to the Mobile Configuration screen and turning on Mobile Mode Only. That disconnects the normal WAN (Ethernet in my case) and swaps over to 4G.

**Comment by jmytch** [comment]
Ran that command in putty, but the thing is when DSL Enabled is disabled, it should say Status down with red light rather than the green saying its Up.

![Capture](https://user-images.githubusercontent.com/45726972/106843431-bc770400-66f1-11eb-93f8-643df80a464a.PNG)

**Comment by seud0nym** [comment]
I don't disagree, but the status light comes from a different source:
```
transformer-cli get sys.class.xdsl.@line0.Status
transformer-cli get sys.class.xdsl.@line1.Status
```

If either of those reports Up then it is shows as enabled.

When you turn DSL off, do you lose internet connectivity?

What I can probably do is change the light to red (or maybe orange since it really is still up), and the message to something like "Up but Disabled"?

**Comment by jmytch** [comment]
When turning DSL off, it didn't lose internet connectivity as I was still able to browse for some reason. Setting DSL to off should lose internet connectivity but not in this case on my end.

Yeah could do something like that and as well lose internet connectivity when setting to Off as it should be.

**Comment by seud0nym** [comment]
The thing is, if you don't lose connectivity, then the switch is pointless.

There is no equivalent switch on the ethernet or ADSL screens:

![image](https://user-images.githubusercontent.com/41851175/106845890-fa7b2480-66ff-11eb-8162-b3cbd2d8b3d2.png)

Maybe the correct solution is to remove the switch that doesn't do anything?

**Comment by seud0nym** [comment]
I just had another thought:

After you disable it, can you run the following command:
```
/etc/init.d/xdsl restart
```
And then see if you have internet connectivity?

If you do, then run this command next:
```
/etc/init.d/network reload
```
And then check internet connectivity again.

**Comment by jmytch** [comment]
This command didn't work and report back as Not found as seen in pic
`/etc/init.d/xdsl restart`

However the second command network reload does work, and had no internet connectivity but DSL Enabled was switched to On by itself

![Capture](https://user-images.githubusercontent.com/45726972/106848307-6bb8d880-66fc-11eb-9bfb-18b711273bf7.PNG)

Guess theres nothing to fix this, cos when the router is not rooted and using Telstra as default, turning DSL to off would give no connectivity.

**Comment by seud0nym** [comment]
Sorry, but you said that after you did the network reload, you had NO internet connectivity, but the switch went back to ON? Is that correct? How did you get connectivity back?

I don't understand why it doesn't work. The modified GUI changes exactly the same setting (sys.class.xdsl.@line0.Enable) that the unmodified stock GUI does.

**Comment by jmytch** [comment]
Yes correct, had no internet connectivity while switch went back to ON.

Had to reboot modem to get connectivity back. I'm thinking about doing all over again with the root in case something glitched out. Anyway will close this in the mean time :)
