### ISSUE TITLE
Support for latest adblock 4.2.2-5

### ISSUE THREAD

**Issue by Fybre** [seud0nym/tch-gui-unhide#212]
When running `sh tch-gui-unhide-xtra.adblock setup`
The following error is shown:
```
>> Determining installed and current versions of required packages...
>> Latest adblock version is 4.2.2-5 but only version 4.1 is supported - unable to complete setup
```
Using:
BLD/125: Built for firmware version 20.3.c - Release 2024.05.31

**Comment by seud0nym** [comment]
Thanks for the report.

Should be fixed now is you get the latest version of the extras script.

**Comment by Fybre** [comment]
Thank you! All working now
