### ISSUE TITLE
VLAN Help

### ISSUE THREAD

**Issue by HeyItsJono** [seud0nym/tch-gui-unhide#213]
So this isn't an issue or a bug, but I'm unsure where else to ask for advice since there isn't a heap of documentation about this particular router mod out there. I have a couple of IOT devices that I'd like to isolate on my network. I'd like to block their access to the internet whilst maintaining communication with a local Home Assistant instance running on an RPi in my network. My understanding from reading around is that I'd need to have two VLANs, one 'main' one where all my usual devices (including my RPi) live and can access the internet, and another 'iot' one where devices on it can only talk to my RPi. Unfortunately I'm struggling to actually get this set up in tch-gui-unhide.  I've made a VLAN and then gone and made another LAN interface for it to keep my IOT devices on a different subnet, but I don't know how to link the VLAN to the LAN interface, or how to only allow communication from IOT -> main. Any help you could offer would be much appreciated, thank you!

![image](https://github.com/user-attachments/assets/75b4e53a-385c-40c5-ac5c-6761e3d5922f)

**Comment by seud0nym** [comment]
Are your IoT devices Wi-Fi or ethernet connected?

Is your rPI connected via Wi-Fi or ethernet?

**Comment by HeyItsJono** [comment]
> Are your IoT devices Wi-Fi or ethernet connected?
> 
> Is your rPI connected via Wi-Fi or ethernet?

IOT: Wifi
RPi: Both, but primarily ethernet

**Comment by seud0nym** [comment]
Okay.

So the way that I do this is to use the Guest Wi-Fi network for IoT devices. There isn't an easy way to add another Wi-Fi SSID for your IoT devices to connect to, so using the Guest network is the easiest way. 

If you have removed the Guest networks and SSIDs, then you can try using the [guest-restore](https://github.com/seud0nym/tch-gui-unhide/tree/master/utilities#guest-restore) script, but personally I would [reset-to-factory-defaults-with-root](https://github.com/seud0nym/tch-gui-unhide/tree/master/utilities#reset-to-factory-defaults-with-root) unless you have a lot to set up again.

I would stick to using the 2.4GHz band for your IoT devices. Make sure you have Band Steering turned off for the Guest SSIDs.

Under VLAN Filtering, set all the ports for VLAN 102 to disabled _except_ for the port that your rPi is connected to. That port should be set to **Tagged**.

Under Interfaces, select the Guest1 interface and tick the rPi port on the VLAN 102 row.

You will then need to add an additional ethernet network interface to your rPi that uses the same ethernet port (obviously) but listens for the 102 VLAN tag. (Sorry, I can't tell you how to do that, because it is dependant on what OS you are running on the rPi, and which network configuration tools it uses.) You can use either DHCP or a static IP. If you use static (probably best), it will need to be in the range allocated to the Guest1 interface on your DJA0231.  The aim is the end up with your rPi having _three_ IP addreses: main ethernet, wi-fi, and the VLANed ethernet.

Then you should be good to go. Connect your IoT devices to your Guest SSID, and they will be isolated from your main network, but Home Assistant on the rPi will still be able to access them because of the extra network interface you added.

**Comment by pencilhead1** [comment]
Would "Time of Day" work?
Block mac address 24x7 every day.

**Comment by HeyItsJono** [comment]
> Okay.
> 
> So the way that I do this is to use the Guest Wi-Fi network for IoT devices. There isn't an easy way to add another Wi-Fi SSID for your IoT devices to connect to, so using the Guest network is the easiest way.
> -snip-

Thank you so much for the detailed writeup! I have managed to get this working in some regard, but it appears as though it's broken the ability for my Pi to see other ethernet devices on my network.

My RPi 4B is running the latest RPi OS release, which is based on Debian bookworm and uses Network Manager.
I've set up the following:

VLAN Filtering:
![image](https://github.com/user-attachments/assets/6f0a01af-8aa2-41be-af4c-8440f14b8cca)

`lan` interface:
![image](https://github.com/user-attachments/assets/0f6c3fe5-2442-4de0-b247-c81756f337fb)

`Guest1` interface:
![image](https://github.com/user-attachments/assets/10f82151-bcc6-4c4e-9ded-039f71784f11)

RPi Ethernet is plugged into ethernet port 2 on the router.
On eth0 it's assigned a static IP `192.168.0.77` on my main lan. IPs are in the range of 192.168.0.2 to 192.168.0.254.
On iot (vlan -> eth0) it's assigned a static IP `192.168.2.77` and tagged with vlan ID 700. IPs are in the range of 192.168.2.2 to 192.168.2.254.
My Guest 2.4GHz network I've renamed to IOT.
My phone can connect to IOT, access the internet, be assigned a dynamic `192.168.2.27` LAN IP, and can ping my Pi at `192.168.2.77`.
My Pi can ping my phone at `192.168.2.27`.
My Pi can also ping my laptop (which is connected via Wifi) on my lan at `192.168.0.10`, and my laptop can ping my Pi at `192.168.0.77`, but not `192.168.2.77`, all of which is expected.

Strangely though, my Pi cannot see my NAS (which is connected to the router via a diff ethernet port). Trying to ping it gives the following:
```
> ping 192.168.0.50
PING 192.168.0.50 (192.168.0.50) 56(84) bytes of data.
From 192.168.0.77 icmp_seq=38 Destination Host Unreachable
From 192.168.0.77 icmp_seq=39 Destination Host Unreachable
From 192.168.0.77 icmp_seq=40 Destination Host Unreachable
From 192.168.0.77 icmp_seq=41 Destination Host Unreachable
ping: sendmsg: No route to host
```

Similarly, my NAS can't see my Pi:
```
> ping 192.168.0.77
PING 192.168.0.77 (192.168.0.77) 56(84) bytes of data.
From 192.168.0.50 icmp_seq=1 Destination Host Unreachable
From 192.168.0.50 icmp_seq=2 Destination Host Unreachable
From 192.168.0.50 icmp_seq=3 Destination Host Unreachable
^C
--- 192.168.0.77 ping statistics ---
4 packets transmitted, 0 received, +3 errors, 100% packet loss, time 3002ms
```

Even if I try to have my NAS ping the Pi's Wifi IP (which is on Pi interface `wlan0`) it still fails.

The same thing happens between my Pi and another ethernet device plugged into a diff. ethernet port. My other lan devices, like my laptop connected via wifi, can ping these other ethernet devices just fine, and they all still work fine in that they can access the internet.

I'm not sure why, but something about this process has caused a rift in communication specifically between the Pi and any other device connected by ethernet to my router, while still allowing communication between the Pi and any other device connected by Wifi, or just between any Wifi connected device and any ethernet connected device. Is there any chance you might know what is going on? Specifically, the issue seemed to occur as soon as I tagged Port 2 with the vlan ID 700 in the VLAN filtering section of the Router settings.

**Comment by seud0nym** [comment]
> No route to host

I use DIetPi on my rPi, so I have no experience with NetworkManager, but that just looks a routing issue. My Home Assistant instance runs in a Proxmox VM (I run it as a supervised install) and does use NetworkManager, but I configure the VLAN in Proxmox, so it  just presents to the VM as a second ethernet interface.

What does the routing table look like?
```
ip route show
```

My Home Assistant VM routing table shows:
```
default via 192.168.192.1 dev ens19 proto dhcp src 192.168.192.163 metric 100
default via 10.20.30.1 dev ens18 proto dhcp src 10.20.30.212 metric 101
10.20.30.0/24 dev ens18 proto kernel scope link src 10.20.30.212 metric 101
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
172.30.32.0/23 dev hassio proto kernel scope link src 172.30.32.1
192.168.192.0/24 dev ens19 proto kernel scope link src 192.168.192.163 metric 100
```

The ens18 interface is my main network, and ens19 is the Guest network.

I hadn't noticed before that ens19 has a lower metric, which means it has higher priority and outbound packets will use it first. I have not used NetworkManager before, but I will have to work out how to fix that.

**Comment by seud0nym** [comment]
> Another strange side effect is under Port Forwarding, it's forced all my old Port Forwards that would normally forward to my Pi's ethernet IP to now port forward to my Pi's Wifi IP.

Very strange. Internally, port forwards use MAC addresses, not IP addresses...

**Comment by HeyItsJono** [comment]
> > No route to host
> 
> I use DIetPi on my rPi, so I have no experience with NetworkManager, but that just looks a routing issue. My Home Assistant instance runs in a Proxmox VM (I run it as a supervised install) and does use NetworkManager, but I configure the VLAN in Proxmox, so it just presents to the VM as a second ethernet interface.
> 
> What does the routing table look like?

With VLAN disabled (and communication between Pi & ethernet devices working):
```
> ip route show
default via 192.168.0.1 dev eth0 proto static metric 100
default via 192.168.1.1 dev iot proto static metric 400
default via 192.168.0.1 dev wlan0 proto dhcp src 192.168.0.177 metric 600
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
172.18.0.0/16 dev br-6a1e9de9cfc7 proto kernel scope link src 172.18.0.1 linkdown
172.19.0.0/16 dev br-e40f2f6cdadd proto kernel scope link src 172.19.0.1
192.168.0.0/24 dev eth0 proto kernel scope link src 192.168.0.77 metric 100
192.168.0.0/24 dev wlan0 proto kernel scope link src 192.168.0.177 metric 600
192.168.1.0/24 dev iot proto kernel scope link src 192.168.1.77 metric 400
```

With VLAN enabled, RPi Port 2 tagged to ID 700 (corresponding to `iot` vlan on my Pi):
```
> ip route show
default via 192.168.0.1 dev eth0 proto static metric 100
default via 192.168.1.1 dev iot proto static metric 400
default via 192.168.0.1 dev wlan0 proto dhcp src 192.168.0.177 metric 600
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1
172.18.0.0/16 dev br-6a1e9de9cfc7 proto kernel scope link src 172.18.0.1 linkdown
172.19.0.0/16 dev br-e40f2f6cdadd proto kernel scope link src 172.19.0.1
192.168.0.0/24 dev eth0 proto kernel scope link src 192.168.0.77 metric 100
192.168.0.0/24 dev wlan0 proto kernel scope link src 192.168.0.177 metric 600
192.168.1.0/24 dev iot proto kernel scope link src 192.168.1.77 metric 400
``` 

They seem to be identical. (For what it's worth I changed the Guest1 subnet from 192.168.2.x to 192.168.1.x hence the difference between my last post and this.)



> > Another strange side effect is under Port Forwarding, it's forced all my old Port Forwards that would normally forward to my Pi's ethernet IP to now port forward to my Pi's Wifi IP.
> 
> Very strange. Internally, port forwards use MAC addresses, not IP addresses...

Humm I checked my Router's ARP table and it seems to have the same MAC for my Pi's wlan0 and eth0 connections (despite the wlan0 interface having a diff. MAC address in my Pi's settings). Maybe that's why?

**Comment by seud0nym** [comment]
I think I have exhausted my expertise about the networking side. It would seem to me that the rPi network config isn't right, given the ARP table issue. It would seem to me that eth0 and wlan0 are actually pointing to the same physical interface and are acting as aliases rather than separate interfaces.

**Comment by HeyItsJono** [comment]
RE: the lack of communication between the Pi & other ethernet devices, I think this has something to do with VLAN on the router, since it only occurs when the 2nd router port is tagged to the Guest1 interface. Even if I leave the Pi's `iot` vlan interface up and running, if I disable VLAN on the router, or untag the Port to disassociate it with Guest1 then I get connectivity between the Pi & ethernet devices back.

As far as the config on the Pi itself goes, I've included pics below which show the details of each interface, they all seem correctly configured to me. The eth0 and wlan0 interfaces each present different MAC addresses, I'm unsure why the router is seeing them as one MAC address. This wasn't the case before trying to get VLAN to work, prior to that I was able to portforward explicitly to the Pi's eth0 interface and its associated static IP, and I could separately portforward to its wlan0 interface and associated static IP.

As an aside, if I can't get VLAN working, an alternative would be just to have the Pi connect via ethernet to the main lan, and connect via Wifi to the Guest1 network and just can the VLAN ethernet tagging altogether, however when I try to disable VLAN on the router it also for some reason disables the Guest1 interface. The SSID still gets broadcast but nothing can connect until VLAN is re-enabled and Port 2 is tagged again.

eth0:
![image](https://github.com/user-attachments/assets/42f64559-cb7e-4e5b-b943-44b17341692c)

wlan0:
![image](https://github.com/user-attachments/assets/a9d0e36a-7388-4e2d-948b-83774894d10a)

iot:
![image](https://github.com/user-attachments/assets/183de39b-3db5-4202-8902-c4765caa147c)

**Comment by HeyItsJono** [comment]
I've deleted the VLAN and given up on that avenue, I'm now just trying to have a separate Guest SSID (IOT) that puts devices on a different subnet (`192.168.1.x`) on the Guest1 lan interface. I've got my RPi successfully connected to this SSID via Wifi, and connected to my main lan via ethernet. I've fixed the ARP/MAC issues with the RPi eth0 and wlan0 interfaces by manually clearing the ARP entries on the router and rebooting the router; now they're appropriately recognised as 2 different devices as far as my router is concerned.

Annoyingly now devices on the Guest1 lan interface can't communicate with each other. They can all access the router login page just fine at its address at `192.168.1.1`, but trying to ping eachother just gives the frustrating Destination Host Unreachable issue again. This isn't isolated just to my RPi, this happens even between two different phones on the Guest SSID/interface. I've tried delving into the firewall to make sure that's not the issue and implemented a couple of custom rules which I figure should allow communication between local devices on the Guest1 interface but to no avail. Any chance you have any thoughts?

![image](https://github.com/user-attachments/assets/1b070cda-439b-4190-b6bb-98d28ac40b4d)
![image](https://github.com/user-attachments/assets/abd7f585-e9f1-4726-b1be-209d752ba7ab)

**Comment by seud0nym** [comment]
The Guest SSID has a feature called AP Isolation that prevents Wi-Fi clients accessing each other. It isn't a firewall setting, and you should remove those custom rules.

You can turn it off by running these commands:
```
uci set wireless.ap1.ap_isolation='0'
uci commit wireless
/etc/init.d/hostapd reload
ubus send config "{'reload':'wireless'}"
```

**Comment by HeyItsJono** [comment]
> The Guest SSID has a feature called AP Isolation that prevents Wi-Fi clients accessing each other. It isn't a firewall setting, and you should remove those custom rules.
> 
> You can turn it off by running these commands:
> 
> ```
> uci set wireless.ap1.ap_isolation='0'
> uci commit wireless
> /etc/init.d/hostapd reload
> ubus send config "{'reload':'wireless'}"
> ```

Thank you, that has indeed fixed the issue! The final step would be to deny WAN access on the Guest network, and also only allow  incoming/outgoing LAN communication between a device and the RPi (to isolate devices from communicating with each-other). Is this something I'd achieve via user firewall rules, or is that something to use uci for?

**Comment by seud0nym** [comment]
> deny WAN access on the Guest network

Probably the simplest way is to delete the Zone Forwarding Traffic Control Rule for the Guest network. That should do it.

> only allow incoming/outgoing LAN communication between a device and the RPi (to isolate devices from communicating with each-other)

That is what AP Isolation does, but since your rPi is also on WiFi, you can't use it. Pity you couldn't get VLAN working in your environment - it would solve that problem easily. I can't imagine the shape of a firewall rule to do what you want. It would be easier to swap the rPi WiFi to your primary LAN, and use wired connection for the Guest, and then re-enable AP Isolation.

**Comment by HeyItsJono** [comment]
> > deny WAN access on the Guest network
> 
> Probably the simplest way is to delete the Zone Forwarding Traffic Control Rule for the Guest network. That should do it.
> 
> > only allow incoming/outgoing LAN communication between a device and the RPi (to isolate devices from communicating with each-other)
> 
> That is what AP Isolation does, but since your rPi is also on WiFi, you can't use it. Pity you couldn't get VLAN working in your environment - it would solve that problem easily. I can't imagine the shape of a firewall rule to do what you want. It would be easier to swap the rPi WiFi to your primary LAN, and use wired connection for the Guest, and then re-enable AP Isolation.

No worries, maybe I'll tackle it again some day in the future, I'm not sure what the problem was there! Is tch-gui-unhide based on some other similar open-source router/modem firmware under the hood where in the future I might also be able to go as an avenue for help? 

In any case I have a current solution I'm pretty satisfied with, so thank you so much for all your help (and this wonderful mod)!

**Comment by seud0nym** [comment]
The Technicolor firmware is based on OpenWrt, although they use their own or third party implementations for things like Wi-Fi and EasyMesh. Networking stuff should be pretty similar.

**Comment by HeyItsJono** [comment]
Cheers, thanks again for taking the time to help me out, I'll close the issue for now :)
