### ISSUE TITLE
CWMPD

### ISSUE THREAD

**Issue by juzman** [seud0nym/tch-gui-unhide#22]
I create my gen2 and ran latest de-telstsra and unhide script.

Everything worked well, but even though on main page it shows CWMPD is disabled, under management > init, CWMPD is still enabled. So I set it to disabled, and stopped the process.

Not sure if a bug, or it's meant to be enabled under init management still?

**Comment by seud0nym** [comment]
I just ran through a complete reset/de-telstra/tch-gui-unhide on my test DJA0231, and it removed cwmpd. The card does not appear, and there is no init script.

What options did you use on de-telstra? There are options (added a couple of months ago) that can optionally retain cwmpd (-kc or -kT).

**Comment by juzman** [comment]
I ran: ./de-telstra -M -hd -no. I didn't use -k at all.

**Comment by seud0nym** [comment]
So, I did another reset and ran your command:
```
root@mymodem:/tmp/run/mountd/sda1#  ./de-telstra -M -hd -no
[de-telstra]: Applying default hardening rules...
[de-telstra]: - Disabling CWMP
[de-telstra]: - Disabling Telstra monitoring
[de-telstra]: - Removing Telstra Air
[de-telstra]: - Removing SSID wl0_2 (AP=ap4)
[de-telstra]: - Removing SSID wl0_3 (AP=ap5)
[de-telstra]: - Removing SSID wl1_3 (AP=ap7)
[de-telstra]: - Removing Telstra Air Band Steering configuration
[de-telstra]: - Deleting Telstra AIR firewall entries
[de-telstra]: - Removing Telstra NTP server chronos.ntp.telstra.net
[de-telstra]: - Removing Telstra NTP server chronos1.ntp.telstra.net
[de-telstra]: - Disabling lotagent (Telstra logging?)
[de-telstra]: - bulkdata collection already disabled
[de-telstra]: - Removing bulkdata cron job
[de-telstra]: - Found authorized_keys - replacing /etc/dropbear/authorized_keys
[de-telstra]: SSH access correctly configured
[de-telstra]: Setting the host name to DJA0231
[de-telstra]: Re-adding telstra.wifi hostname for EasyMesh
[de-telstra]: Changing DLNAD friendly name from Telstra Modem to DJA0231
[de-telstra]: Changing SAMBA host name from Telstra-Modem to DJA0231
[de-telstra]: Domain name unchanged [modem]
[de-telstra]: Ignoring ISP defined DNS Servers
[de-telstra]: DNS Servers changed [ 208.67.222.222 208.67.220.220 ]
[de-telstra]: Content sharing Disabled
[de-telstra]: Printer sharing Disabled
[de-telstra]: File sharing Disabled
[de-telstra]: Telephony Disabled
[de-telstra]: Enabling VoLTE backup voice service and SMS reception
[de-telstra]: DECT Emission Mode Disabled
[de-telstra]: WPS State on SSID Telstra7E5F7A Disabled
[de-telstra]: WPS State on SSID Telstra7E5F7A Disabled
[de-telstra]: FTP ALG Disabled
[de-telstra]: TFTP ALG Disabled
[de-telstra]: SNMP ALG Disabled
[de-telstra]: PPTP ALG Disabled
[de-telstra]: SIP ALG Disabled
[de-telstra]: IRC ALG Disabled
[de-telstra]: AMANDA ALG Disabled
[de-telstra]: RTSP ALG Disabled
[de-telstra]: UPnP Disabled
[de-telstra]: DumaOS unchanged [Disabled]
[de-telstra]: MultiAP Disabled
[de-telstra]: Power saving settings unchanged [Enabled]
[de-telstra]: Applying required service changes...
[de-telstra]: Removing packages that are no longer required ( conf-cwmpd cwmpd libbcmairiq conf-airiq autoreset-tch tls-thor wifi-doctor-agent conf-wifi-doctor-agent hotspotd webui-fon)
Removing package conf-cwmpd from root...
Removing package cwmpd from root...
Removing package lighttpd-mod-auth-thor from root...
Removing package tls-thor-web from root...
Removing package tls-thor from root...
Stopping ProcessManager
Removing package airiq-controller from root...
Removing package bcmairiq from root...
Removing package libbcmairiq from root...
Removing package conf-airiq from root...
Removing package autoreset-tch from root...
Removing package wifi-services-agent from root...
Removing package conf-wifi-doctor-agent from root...
Removing package conf-hotspotd from root...
Removing package hotspotd from root...
Removing package webui-fon from root...
Collected errors:
 * opkg_remove_cmd: Package tls-thor is not installed.
[de-telstra]: Cleaning up broken links in /etc/rc.d
[de-telstra]: Done!
[de-telstra]: NOTE: If you haven't changed the root password, you should do it now...
root@DJA0231:/tmp/run/mountd/sda1# ll /etc/init.d/cwmpd
ls: /etc/init.d/cwmpd: No such file or directory
root@DJA0231:/tmp/run/mountd/sda1#
```

cwmp was uninstalled, and the init script no longer exists.

Can you try running the script again, and check the output for errors?

**Comment by juzman** [comment]
I ran the script, when I login to the modem and go to Management > Init, I still have cwmpd, although not enabled as I disabled it already.

Here's the output (although I got similar to yours originally).

`root@mymodem:~# ./de-telstra -M -hd -no
[de-telstra]: Applying default hardening rules...
[de-telstra]: - CWMP already Disabled
[de-telstra]: - Telstra monitoring already Disabled
[de-telstra]: - Telstra AIR already removed
[de-telstra]: - Telstra AIR firewall entries already removed
[de-telstra]: - Telstra NTP servers already removed
[de-telstra]: - lotagent already Disabled
[de-telstra]: - bulkdata collection already disabled
[de-telstra]: - Removing bulkdata cron job
[de-telstra]: - All public keys already removed from /etc/dropbear/authorized_keys
[de-telstra]: SSH access already correctly configured
[de-telstra]: Setting the host name to DJA0231
[de-telstra]: Changing DLNAD friendly name from Telstra Modem to DJA0231
[de-telstra]: Changing SAMBA host name from Telstra-Modem to DJA0231
[de-telstra]: Domain name unchanged [modem]
[de-telstra]: ISP peer DNS unchanged [Disabled]
[de-telstra]: DNS Servers unchanged [ 208.67.222.222 208.67.220.220 ]
[de-telstra]: Content sharing unchanged [Disabled]
[de-telstra]: Printer sharing unchanged [Disabled]
[de-telstra]: File sharing unchanged [Disabled]
[de-telstra]: Telephony unchanged [Disabled]
[de-telstra]: VoLTE already Enabled
[de-telstra]: DECT Emission Mode unchanged [Disabled]
[de-telstra]: WPS State unchanged on SSID 2GLoading... [Disabled]
[de-telstra]: WPS State unchanged on SSID Loading... [Disabled]
[de-telstra]: FTP ALG unchanged [Disabled]
[de-telstra]: TFTP ALG unchanged [Disabled]
[de-telstra]: SNMP ALG unchanged [Disabled]
[de-telstra]: PPTP ALG unchanged [Disabled]
[de-telstra]: SIP ALG unchanged [Disabled]
[de-telstra]: IRC ALG unchanged [Disabled]
[de-telstra]: AMANDA ALG unchanged [Disabled]
[de-telstra]: RTSP ALG unchanged [Disabled]
[de-telstra]: UPnP unchanged [UPnP: Disabled NAT-PMP: Disabled]
[de-telstra]: DumaOS unchanged [Disabled]
[de-telstra]: MultiAP unchanged [Controller: Disabled Agent: Disabled BackHaul SSID: Disabled]
[de-telstra]: Power saving settings unchanged [Disabled]
[de-telstra]: Applying required service changes...
[de-telstra]: Cleaning up broken links in /etc/rc.d
[de-telstra]: Done!
[de-telstra]: NOTE: If you haven't changed the root password, you should do it now...
root@DJA0231:~#`

![Screenshot_20210228-185329_Chrome](https://user-images.githubusercontent.com/40587757/109412874-3b601380-79f6-11eb-9d1c-a6892b825f1a.png)

**Comment by seud0nym** [comment]
Try this:
```
uci set cwmpd.cwmpd_config.state='1'
uci commit cwmpd
```
Then re-run your:
```
./de-telstra -M -hd -no
```
After you have run de-telstra and it (hopefully) removes cwmp, you will then have to re-run `tch-gui-unhide` to clean up the GUI and remove the card.

If it doesn't remove the cwmpd package, please post the output again. Thanks.

**Comment by juzman** [comment]
That seemed to have worked. Removed the CWMP card too. The init isn't there either. ☺️

**Comment by seud0nym** [comment]
Excellent. I cannot explain what happened, but I will add a couple of extra checks to make sure it does always remove it.
