### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#25]
What does Output Power Adjustment do in the WiFi section?

![Capture](https://user-images.githubusercontent.com/45726972/117957052-fe50bf80-b35c-11eb-8e05-7eef8b353f92.PNG)

![Capture2](https://user-images.githubusercontent.com/45726972/117957365-5a1b4880-b35d-11eb-9616-e64af4d1dea6.PNG)
**Any chance of adding the question mark button next to that to explain what it does like you did with IPv6 in red box**

**Comment by seud0nym** [comment]
It allows you to increase or decrease the Wi-Fi output transmission power. The stock GUI only allows you to decrease it.

It was something that tch-nginx-gui offers, and a couple of people asked for it, so I added it, but I don't recommend increasing transmission power. It will cause more interference in neighboring channels, and reduce component lifetime by increasing the heat generated.

I guess I could add the help text. I already change the description (the stock GUI just calls it "Output Power", which isn't correct). I will have a look.

**Comment by jmytch** [comment]
Oh right thanks for the explanation, guess I will leave it alone.
