### ISSUE TITLE
Help with Permission Denied

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#29]
I was doing the 20.3c upgrade, and when it successfully flashed. Downloaded the pre-release of tch-gui-unhide, and store them in /root folder, however when running any CL, it just says permission denied. 

Also with the url you mentioned, it didn't work for me as I don't know why. 
![Capture](https://user-images.githubusercontent.com/45726972/122855162-2702a680-d358-11eb-9209-278f52a096a2.PNG)

**Comment by seud0nym** [comment]
If you uploaded them manually from your PC, then the execution flag isn't set. Run this command:

```
chmod +x de-telstra intercept-dns mtd-* reboot-on-coredump reset-to-factory-defaults-with-root set-* show-bank-plan tch-gui-* unpack-rbi update-ca-certificates
```

Then you should be able to run them.

You have a DJA0230, correct? Unfortunately, I bricked mine last week and the replacement I bought hasn't arrived yet...

A couple of things to try... 

What does the following command return:
```
uci get version.@version[0].marketing_version
```

Run the following command and see if it downloads correctly:
```
curl -kL https://github.com/seud0nym/tch-gui-unhide/releases/download/2021.06.21/20.3.c.pre-release.tar.gz -o 20.3.c.pre-release.tar.gz
```

If it does, then run:
```
tar -xzvf 20.3.c.pre-release.tar.gz
```
to make sure it unpacks correctly.

The ```ll``` (or ```ls -l```) command will list the files and show their permissions. Mine looks like this on a clean DJA0231 after running the normal setup curl command:
```
root@mymodem:~# ll
drwxr-xr-x    1 root     root             0 Jun 22 13:24 ./
drwxr-xr-x    1 root     root             0 Jun 22 13:09 ../
-rwxr-xr-x    1 root     root         42269 Jun 19 19:58 de-telstra*
-rwxr-xr-x    1 root     root         11181 Jun 15 17:15 intercept-dns*
drwxr-xr-x    2 root     root             0 Jun 22 13:06 log/
drwxr-xr-x    2 root     root             0 Jun 22 13:07 lot/
-rwxr-xr-x    1 root     root          9333 Jun 21 11:49 mtd-backup*
-rwxr-xr-x    1 root     root          5453 Jun 21 12:45 mtd-restore*
-rwxr-xr-x    1 root     root          1171 May 16 17:27 reboot-on-coredump*
-rwxr-xr-x    1 root     root          8277 Jun 18 14:36 reset-to-factory-defaults-with-root*
-rwxr-xr-x    1 root     root          2166 May 16 17:27 set-optimal-bank-plan*
-rwxr-xr-x    1 root     root           593 May 16 17:27 set-web-admin-password*
-rwxr-xr-x    1 root     root          1380 May 16 17:27 show-bank-plan*
-rwxr-xr-x    1 root     root          1048 Jun 15 15:26 tch-gui-unhide*
-rwxr-xr-x    1 root     root        365378 Jun 21 17:20 tch-gui-unhide-20.3.c*
-rwxr-xr-x    1 root     root         12474 Jun 21 15:08 tch-gui-unhide-cards*
drwxr-xr-x    3 root     root             0 Jun 22 13:26 trafficmon/
-rwxr-xr-x    1 root     root          1299 May 16 17:27 unpack-rbi*
-rwxr-xr-x    1 root     root          2260 Jun 19 12:40 update-ca-certificates*
```

**Comment by jmytch** [comment]
Ah yeah that explains the permission part lol, I should had known that part when it comes to uploading from the PC manually.  Yes that is correct I'm on the DJA0230.

uci get version.@version[0].marketing_version returned as `20.3.c`

Also what is the difference between `./tch-gui-unhide` and `./tch-gui-unhide-20.3.c`?

Should I run both or should I only run the 20.3.c one?

**Comment by seud0nym** [comment]
```./tch-gui-unhide``` is just a wrapper around the actual platform script. It gets the version and calls the right script (in this case ```./tch-gui-unhide-20.3.c```. It also has the ```-U``` option to download the latest release tar file, which the platform script doesn't have.

Just use ```./tch-gui-unhide```. It will call ```./tch-gui-unhide-20.3.c```. You don't need to run both. It is a convenience thing mostly for my benefit, because I will have multiple platform scripts on a USB script, and ```./tch-gui-unhide``` picks the right one for the firmware version I am running it on.

Did you work out if it was the download or the unpacking that was failing for you?

**Comment by jmytch** [comment]
Thanks for the explanation, and yes it is working after allowing the permission to execute 👍 

Everything seems to be working so far, except for one thing that it is missing xDSL Config card in the latest update but not that important for me. Just thought I'd let you know.

**Comment by seud0nym** [comment]
Good to hear. 

I can see why the xDSL card is missing. They have disabled it if you are using the default user (i.e. if you don't log in to the GUI). I will fix it.

**Comment by jmytch** [comment]
I'm logged in as admin, it still not showing. I think they have broke something in the latest version XD 

I always require log in as I dont allow anyone to mess around with the router lol, anyway that screenshot is all the cards I see while logged in. Yes I did use the `tch-gui-unhide-cards` to check and it is not hidden at all. 

![Capture](https://user-images.githubusercontent.com/45726972/122865160-3b9b6a80-d369-11eb-8435-c5f15036242f.PNG)

**Comment by seud0nym** [comment]
Okay. Thanks. I will double check what is going on.

**Comment by seud0nym** [comment]
I found the missing card problem. They have changed something I look for on the card, and I hadn't noticed. It will be fixed in the next pre-release.

Thanks.
