### ISSUE TITLE
WiFi Card

### ISSUE THREAD

**Issue by juzman** [seud0nym/tch-gui-unhide#3]
Loving the updates!

Was wondering if you could add in the WiFi signal strength section from Ansuel GUI where you can increase the WiFI output?

https://github.com/Ansuel/tch-nginx-gui/blob/master/decompressed/gui_file/www/docroot/modals/wireless-modal.lp

**Comment by seud0nym** [comment]
I have just done a compare on that modal and the stock one, and I can't see anything other than the output power slider, which is already there?

**Comment by juzman** [comment]
Oh, maybe I was looking at the wrong thing, on AnsuelGUI there was a slider where you could increase wifi output +2/+4/+6dB

**Comment by seud0nym** [comment]
I loaded up the Ansuel GUI on my old TG800 to see what it does. They both adjust the radio tx_power_adjust value, but the stock GUI only goes from -6 to 0, where Ansuel goes from -6 to +6.

I will have a think. Stability is my big concern.

**Comment by juzman** [comment]
Yeah, that's the one. I was running it at +4dB fine, and if I can remember correctly I found some info on Technicolor forums in Europe or wherever it was saying they've been running +6dB fine too.

I do know on an older model Telstra cable modem back in the day the firmware enabled up to +10dB I think it was.

**Comment by driva5** [comment]
This would be great if it were added. And if the slider is currently like the stock firmware where the power slider moves by a 25% increment, it would be nice if this could be changed so that you can set the slider to any number within the power range for the sake of control.

**Comment by driva5** [comment]
Also is there a way to force a 40 MHz channel width on the 2.4GHz band? Setting channel width to "Auto (20/40MHz)" on the stock Telstra firmware produces the same result as setting the channel width to 20MHz. 

`root@mygateway# wlctl 2g_rate	
Force a fixed rate for data frames in the 2.4G band:
Either "auto", or a simple CCK/DSSS/OFDM rate value:
	1 2 5.5 11 6 9 12 18 24 36 48 54
Or options to specify legacy, HT, or VHT rate:
	-r R, --rate=R        : legacy rate (CCK, DSSS, OFDM)
	-h M, --ht=M          : HT MCS index [0-23]
	-v M[xS], --vht=M[xS] : VHT MCS index M [0-9],
	                      : and optionally Nss S [1-8], eg. 5x2 is MCS=5, Nss=2
	-c cM[sS]             : VHT (c notation) MCS index M [0-9],
	                      : and optionally Nss S [1-8], eg. c5s2 is MCS=5, Nss=2
	-s S, --ss=S          : VHT Nss [1-8], number of spatial streams, default 1.
	                      : Only used with -v/--vht when MxS format is not used
	-x T, --exp=T         : Tx Expansion, number of tx chains (NTx) beyond the minimum
	                      : required for the space-time-streams, exp = NTx – Nsts
	--stbc                : Use STBC expansion, otherwise no STBC
	-l, --ldpc            : Use LDPC encoding, otherwise no LDPC
	-g, --sgi             : SGI, Short Guard Interval, otherwise standard GI
	-b, --bandwidth       : transmit bandwidth MHz; 20, 40, 80
`

**Comment by seud0nym** [comment]
According to my research, it will use 40MHz only if the adjoining channels are free, to avoid interference on those channels. So forcing it would be a bad idea.

**Comment by driva5** [comment]
I see. I have a crappy Linksys router that I believe follows the same principle as I have to set both the channel width and channel to auto in order for it to utilise 40MHz. But it doesn't seem to have an issue choosing a 40MHz channel as shown in the screenshots below. Interestingly, I detected a Telstra Arcadyan (I'm assuming this is the LH1000) with a max rate of 450Mbps whereas my Technicolor maxes out at 405 Mbps. Makes me wonder if they have better wifi.

https://i.ibb.co/sRFZcK1/11.png

https://i.ibb.co/Px5n1YK/22.png

**Comment by seud0nym** [comment]
I have just done a new release to add Wi-Fi output power adjustment up to +6dBm.

**Comment by seud0nym** [comment]
> Would it be possible to add an option to select the wifi type like so:

I had a look at selecting the WiFi type. Both the Ansuel and stock GUI use the same list of codes (bg/bgn for 2.4GHz and an/anac for 5GHz). There is little documentation around on OpenWRT with Broadcom wireless, so I don't want to start guessing at codes that may not even be supported.

> I have to set both the channel width and channel to auto in order for it to utilise 40MHz.

Have you tried doing that?

**Comment by juzman** [comment]
> I have just done a new release to add Wi-Fi output power adjustment up to +6dBm.

Worked beautifully mate! Thanks for the quick addition!

**Comment by driva5** [comment]
> Have you tried doing that?

I have to no effect.

Thanks for the update.
