### ISSUE TITLE
pwrctl config --dgm to be added

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#31]
Just noticed there is new `Deep Green Mode` for Ethernet section.

You might want to add it to your "Power Saving" setting to `./de-telstra`

`pwrctl config --dgm off`

![Capture](https://user-images.githubusercontent.com/45726972/123497325-3e9ba100-d670-11eb-9466-85e9c942dc27.PNG)

**Comment by seud0nym** [comment]
It has actually always been there, but I missed it in `de-tesltra`. You can set it through the GUI after running `tch-gui-unhide`.

Thanks for noticing.

**Comment by jmytch** [comment]
Yeah I know that I can turn it off via GUI, it would be much easier with `./de-telstra` when running the options all at once as it just quicker that way lol. But thanks for adding it.

**Comment by jmytch** [comment]
Could you please add (?) where we can hover over to as to what it does for `Network Device Down` and `PHY Power Down` please?

I enabled Network Device Down, not knowing what this does, and it cut my ethernet out as couldn't revert it back so had to use my mobile to get on PuTTY (alternative app) on Android to disable it. 

Tried enabling PHY Power Down, same result as above, I don't know what they are as it seems new to me as never seen them before. Tried searching up the `Network Device Down Ethernet` and it doesn't say anything about it? It's abit strange.
