### ISSUE TITLE
Mobile - Can't change mobile provider

### ISSUE THREAD

**Issue by RHSteven** [seud0nym/tch-gui-unhide#33]
Hi, tried adding "Network operator" & "Profile" for Optus but still doesn't work on the Optus sim.

Is there a function to search or how could I resolve this to use other provider's sim other than telstra.

**Comment by seud0nym** [comment]
This is more a question for the Whirlpool forum. See this post and the ones following it: https://whrl.pl/RgdhZ8

If you can't get it working, maybe post your question there.

Sorry.
