### ISSUE TITLE
New theme idea

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#36]
I don't know if this is possible, so it might be worth asking.

First of all, our router have current time, nor at network time zone. I was thinking something like this.

- At 6**am** till 5:59pm, theme changes to `Light`
- At 6**pm** till 5:59am, theme changes to `Night (Dark)`

So for example, setting the `Light Blue` at that time and then from 6pm it automatic change to `Night Blue`. Most of the time I keep switching theme during the day, and then at night I use Night theme. I'm sure there is something to execute it automatically at specific time etc.

**Comment by seud0nym** [comment]
Any easy one at last :-)

Run this in your PuTTY session:
```
echo '0 6 * * * transformer-cli set rpc.gui.theme.THEME light'>>/etc/crontabs/root
echo '0 18 * * * transformer-cli set rpc.gui.theme.THEME night'>>/etc/crontabs/root
/etc/init.d/cron restart
```

**Comment by jmytch** [comment]
Awesome, thanks for that 👍🏼 

Just would be nice if it was a option in the theme selection with a drop down menu calling it 

**_Base Theme_** - `Appearance Schedule`
**_Schedule_** - `Sunset to Sunrise` or `Custom Schedule` (where they can input specific time themselves)
**_Theme Colour_** - `Telstra (Modern)`, `Blue`, `Green`, `Orange`, `Purple`, `Red`, `Yellow`, `Monochrome`
**_Card Icons_** - `Visible` or `Hidden or Invisible`

With a choice of the colour themes they want to use. Pretty simple so if one selects Green, then it will automatically have `Light Green` and `Night Green` combo.

**Comment by seud0nym** [comment]
Added to next release.
