### ISSUE TITLE
The new feature

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#38]
![Capture](https://user-images.githubusercontent.com/45726972/128324210-e1cdedee-6fc3-4cd8-8c1e-309833937024.PNG)

As in today update of the version you released, the CPU is abit hard to see in the Night/Dark themes. Possible to match the colour of the icons for the CPU might be ideal for dark themes.

![Capture2](https://user-images.githubusercontent.com/45726972/128324506-c2a70333-c90d-403a-9833-bdb6c3de2239.PNG)
Those cyan looking icons, and title background might be suitable for the CPU and it's graph?

Other than that, nice update, really like it.

**Comment by seud0nym** [comment]
Yes, I agree. It is a bit hard to read in the night theme. I have changed it to a lighter blue (the second blue in the technicolor logo):

![image](https://user-images.githubusercontent.com/41851175/128445057-5c1ab41c-c77f-44cf-8104-9c5d6573f5e2.png)

**Comment by jmytch** [comment]
That looks better for sure, big difference to see it. 

RAM is kind of ok, it still readable. Maybe you could try orange and see if that helps? Or Monochrome for RAM? ;-) or leave it as is lol
