### ISSUE TITLE
Whats the CL for 4G Band

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#39]
Accidently unticked band 3 and 27, and now its stuck on band 7. Doesn't show option to tick it again as it literally disappeared :( 
Any command line I can put in putty to bring back the band 3 and 27?

**Comment by seud0nym** [comment]
This should reset to the default:
```
transformer-cli set uci.mobiled.device.@1.lte_bands ""
```

It seems to disappear if it goes off the air. I will have a look into that.

**Comment by jmytch** [comment]
Thank you, that fixes it 👍🏼
