### ISSUE TITLE
What folder

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#4]
`Alternatively, you can download the release for your firmware version to your computer and then upload it up to your device using WinSCP or equivalent. Run the tar -xzvf <filename> command to extract the release files.`

I'm going to do the rooting again later on since the 4G service shows "connecting, and says no service" but was fine yesterday. However the question is, when I download the release, where do I put them in the WinSCP, should it be in the `./tmp` folder then run the `tar -xzvf <filename>`?

**Comment by seud0nym** [comment]
/tmp is fine. I have a USB stick in all of mine, so I just use that. 

If you want to just have them immediately available after you log in, you could put them in /root (the root user home directory). Then you don't have to change directory after you log in. And in terms of filesystem usage, /tmp and /root are in the same partition.
