### ISSUE TITLE
Silly idea might help

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#40]
I was editing all of this in **MSPaint** 😂

To tidy up and lessen the clutter, maybe a silly idea would help? 😏
That would go on the left next to DJA0230/DJA0231 card

![Capture2](https://user-images.githubusercontent.com/45726972/130309960-4d78fa65-9dc2-4e57-aa8d-d25c6a0947f5.JPG)

![Capture](https://user-images.githubusercontent.com/45726972/130309891-de4f7f71-2a98-4f78-b944-e058d3dc99af.png)

**Comment by seud0nym** [comment]
It is not a silly idea/ I did consider it, but there are complexities. The chart cards rely on the data feeds to the DJA0230/1 card and the Broadband card. So, if one (or both) of those is hidden (which you can do either through tch-gui-unhide-cards or the Management Theme tab), then the associated chart cards have to be hidden as well. Much more difficult and complex than having separate cards.

I may consider it for a future release.

**Comment by jmytch** [comment]
Well I don't see why DJA0230/1 card and the broadband card would be hidden by anyone as they are must have to be displayed for people to know. Maybe you could remove the hidden ability for the DJA0230/1 and Broadband so that way nobody can mess with those two cards as they have to stay there, no matter what people say since it is a requirement across NBN and modem.

If one decides to churn to another provider then they will still need the broadband card to configure it with their new provider so those card have to stay permanently imho.  However, System Info card may be hidden if people don't want that to be displayed. That's my opinion 😏

**Comment by seud0nym** [comment]
Unless the device is in bridge mode...

**Comment by jmytch** [comment]
If they are in bridge mode, then maybe don't allow nor hide System Info card along with DJA2030/1 & Broadband cards 🤔

**Comment by seud0nym** [comment]
Leaving a header (System Info in your example) made the charts too skinny. This is what it will look like:

![image](https://user-images.githubusercontent.com/41851175/131303704-77c4ec6c-3e50-40db-b7c2-3cdc10f94599.png)

It is optional. There is a new parameter when running tch-gui-unhide (-Cs) to only show the summary card. The setting is remembered for  the next update, so you only have to specify it the first time.

**Comment by jmytch** [comment]
I'm curious with the idea I have in my mind, what I was thinking is that if you put WAN down and WAN up together but split the graph in half, would that give you more room for a header? See picture of what I meant, it could or could not work. You could try it on your end to see if it helps? I really appreciate it for this as I think 4 cards are unnecessary for myself, but for others maybe not :)

![131303704-77c4ec6c-3e50-40db-b7c2-3cdc10f94599](https://user-images.githubusercontent.com/45726972/131428203-e18b445e-332e-4dfb-bfad-e85c91f0ee8b.png)

**Comment by seud0nym** [comment]
Positioning those charts was onerous. I think it is fine the way it is. You still can choose one card with 4 charts. 

I also want to distinguish the chart cards from the 'standard' cards where clicking on that card header opens another screen. That doesn't happen with chart cards.
