### ISSUE TITLE
TCP and SRTP on VoIP?

### ISSUE THREAD

**Issue by stewielives** [seud0nym/tch-gui-unhide#43]
Kudos to the creator of these mods.
I hate e-waste, and these mods give otherwise solid hardware a new life.

Not sure if this is possible, but is there any chance of allowing the VoIP ports to connect over TCP?
Also, any chance of allowing SRTP authentication?

**Comment by seud0nym** [comment]
I can't see anything in the mmpbx configuration for either of those things, but it might be better to ask on the Whirlpool forum - some people may have more knowledge about mmpbx than I do.

You could consider trying to run asterisk which I am sure would give you more options to do what you want. Not sure what the state of the asterisk packages are, though. I do remember a post where one of the European device users said they had it running on their variant, but I don't remember RAM/storage/processor capability.
