### ISSUE TITLE
SSL certificate has expired?

### ISSUE THREAD

**Issue by SmartBoy84** [seud0nym/tch-gui-unhide#45]
Certificate for "https://repository.macoers.com" seems to have expired?

`ERROR: cannot verify repository.macoers.com's certificate, issued by 'CN=R3,O=Let\'s Encrypt,C=US':
  Issued certificate has expired.`

For now, I am able to update/install by appending "--no-check-certificate" to the opkg commands.

**Comment by seud0nym** [comment]
The repository is outside of my control, but I have just checked and they seem to have applied a new certificate now.

**Comment by SmartBoy84** [comment]
Man, there's no need to close my issues for me. If you want to prevent unnoticed issues then give the user a grace period of a couple of days before deleting it, maybe the issue persists?
In any case, it does. "Opkg update" still returns wget and manually running wget reports that it's the same issue. Yes, I have run the "update-ca-certificates' script and am able to wget other files.

So now what do I do? Wait for you to repoen the issue or make another issue?

**Comment by seud0nym** [comment]
I apologise.  

What device and firmware version are you using?

I tested it by running `opkg update` from my main router (DJA0231 on 20.3.c firmware), and I also went to the web site and checked the certificate details through the browser.

I did not get an error from opkg, and the certificate is valid from 25/08/2021 to 23/11/2021:

![image](https://user-images.githubusercontent.com/41851175/137807887-b951f7f7-69e8-43ed-adbe-2675311bc849.png)

You could try changing to http:
```
sed -e 's/https:/http:/' -i /etc/opkg/customfeeds.conf
opkg update
```

They may do automatic redirection to https, but this also works from my DJA0231.

You can change it back if it makes no difference using:
```
sed -e 's/http:/https:/' -i /etc/opkg/customfeeds.conf
```

Is `update-ca-certificates` actually working? Try running it with the -v option to make sure.

**Comment by SmartBoy84** [comment]
Yes the update script seems to be working all right:

```rpc.gui.opkg: Downloading https://downloads.openwrt.org/releases/packages-21.02/arm_cortex-a9/base//ca-bundle_20210119-1_all.ipk...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  113k  100  113k    0     0  58358      0  0:00:02  0:00:02 --:--:-- 47952
rpc.gui.opkg: Package ca-bundle (20210119-1) installed in root is up to date.
rpc.gui.opkg: Downloading https://downloads.openwrt.org/releases/packages-21.02/arm_cortex-a9/base//ca-certificates_20210119-1_all.ipk...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  123k  100  123k    0     0  63175      0  0:00:02  0:00:02 --:--:-- 52318
rpc.gui.opkg: Package ca-certificates (20210119-1) installed in root is up to date.
rpc.gui.opkg: Updating ca-certificates.crt from https://curl.se/ca/cacert.pem if changed...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0```

Are my repos correctly configured? This is the full output when I run '''opkg update'''
'''Collected errors:
 * opkg_download: Failed to download https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/base/Packages.gz, wget returned 5.
 * opkg_download: Failed to download https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/packages/Packages.gz, wget returned 5.
 * opkg_download: Failed to download https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/luci/Packages.gz, wget returned 5.
 * opkg_download: Failed to download https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/routing/Packages.gz, wget returned 5.
 * opkg_download: Failed to download https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/telephony/Packages.gz, wget returned 5.
 * opkg_download: Failed to download https://repository.macoers.com/homeware/18/brcm63xx-tch/VANTW/target/packages/Packages.gz, wget returned 5.```

Thanks

**Comment by seud0nym** [comment]
Yes, if it works when you add "--no-check-certificate" to the opkg commands, then your repositories are configured correctly.

I have occasionally had what you are seeing. It seems like both wget (which isn't really wget - it is actually uclient-fetch) and curl fail to find the CA certificates. I haven't been able to reproduce it reliably or work out what causes it.

Did you try changing the repository URLs to http: as described in my last response?

What device do you have and what firmware are you running?

What modifications have you applied? (e.g. did you run de-telstra and what options did you use?)
