### ISSUE TITLE
Continual memory increase after running tch-gui-unhide

### ISSUE THREAD

**Issue by willat8** [seud0nym/tch-gui-unhide#46]
I'm on DJA0230 and 20.3 and the latest version of tch-gui-unhide.

I've noticed after running tch-gui-unhide with any switches will cause my DJA0230 memory usage to slowly increase over days until the device crashes.

I can reliably reproduce this, but it takes 4-5 days for the memory usage to reach 100% and cause the reboot.

The options I applied when initially setting up the device are:

./set-optimal-bank-plan
./de-telstra -M -G -nc -hd -dl -wn -sn
 ./tch-gui-unhide -dy -fn -vy -hd -in -tl -Cs

I'm otherwise running all the defaults and haven't installed anything extra.

**Comment by willat8** [comment]
Thanks, I'll run that and get back to you.

To clarify, after it crashes and reboots the memory usage is steady around 74% long-term. Until I run tch-gui-unhide again for whatever reason, then it starts increasing to 100% over the next few days again.

**Comment by seud0nym** [comment]
Do you mean that you re-run the tch-gui-unhide script, or that you just access the GUI with the browser?

**Comment by seud0nym** [comment]
Okay, but there haven't been updates to tch-gui-unhide since 27 September...

Anyway, do whatever you have to do to make it happen, and then the monitoring will hopefully tell us what is happening.

**Comment by willat8** [comment]
Have been experiencing this a little more. Could it be due to changing the DNS server that's handed out to DHCP clients to my custom value that's specified in *ipv4-DNS-Servers*?

**Comment by seud0nym** [comment]
No, the IP address that is handed out can't really make a difference.

I did have an issue on my 2 DJA0231 where the log process increased in size by a factor of 10. It took my main router from 80% to 93% memory used.

Try running this command (I now run it every day via cron):
```
/etc/init.d/log restart
```

You can also run these commands, which flush the in-memory page cache back to disk:
```
sync
echo 1 > /proc/sys/vm/drop_caches
```

Apart from that, have you been running the cron job  abovce (https://github.com/seud0nym/tch-gui-unhide/issues/46#issuecomment-949108139)? If so, can you see what processes are using the most memory?

**Comment by willat8** [comment]
Thanks @seud0nym, I ran the from job for a week but the memory increase wasn't happening anymore so I stopped it. Will try restarting the log daemon and dropping the memory cache next time this happens.

**Comment by willat8** [comment]
Have run into this again. The cron script above is showing the memory usage for /use/bin/nqnd increasing every day. Is that part of nqe SMB implementation?

**Comment by seud0nym** [comment]
Yes, I think it is.

You could try restarting nqe every day/week, maybe running the drop caches in between the stop/start?

**Comment by willat8** [comment]
Thanks. I've just swapped to vsftpd instead from the opkg repositories and said good bye to NQE..
