### ISSUE TITLE
WiFi Booster on DJA0230?

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#5]
Is it normal to see WiFi Booster on DJA0230? I had never see that card before in the older firmware which you can see in the screenshots.

![wb](https://user-images.githubusercontent.com/45726972/94270148-fd604e80-ff82-11ea-9033-533f8f301db0.PNG)

Used firmware 18.1c for DJA0230
![fw](https://user-images.githubusercontent.com/45726972/94270157-ffc2a880-ff82-11ea-9acd-0f947178d24b.PNG)

**Comment by seud0nym** [comment]
Wi-Fi Boosters is a custom card that I added, not something that is standard, so you would never have seen it in the Telstra firmware or earlier versions of tch-gui-unhide.

It looks to see if there is a multiap configuration (/etc/config/multiap) and the card is enabled if it is there. So you must have that configuration file. It also found the wireless backhaul SSID in the wireless configuration.

Do you see WiFi Boosters as a tab on the Home screen in the basic view?

**Comment by seud0nym** [comment]
You probably have "Boost your Wi-Fi" tab in Basic view, that takes you to the Telstra Web Site. And I had a look - the DJA0230 is compatible with the Telstra Wi-Fi Boosters (they call the DJA0230 the Smart Modem 1.1)

https://www.telstra.com.au/internet/extras/wifi-extender#specs
