### ISSUE TITLE
feature request: wifi QR code generator

### ISSUE THREAD

**Issue by bones-was-here** [seud0nym/tch-gui-unhide#50]
FreshTomato has this feature https://wiki.freshtomato.org/doku.php/wifi_qr_codes it can generate a somewhat customisable, printable/PDFable page for easily connecting to the wifi.  

IMO this is better than NFC, because the pages can be taken to parts of the building where there's no physical access to the router.  

Also NFC is kinda heavy on CPU (even when not in use... WTF?)

Relatedly, disabling NFC using the NFC card does not stop `nfcd` which continues to burn CPU.

**Comment by seud0nym** [comment]
There actually is a screen already in the stock GUI for showing wireless QR codes. I looked at way back when I started working on tch-gui-unhide, but I couldn't get it to work then, so I just abandoned it. However, I do know a lot more now, so I will revisit it.

Does stopping and disabling the `nfcd` service help?
```
/etc/init.d/nfcd stop
/etc/init.d/nfcd disable
```

de-telstra will do that when you run it with the minimum memory mode flag (-M).

**Comment by bones-was-here** [comment]
Yes, stopping and disabling the service works fine, just that (at least on my device) that didn't happen when switching off NFC in the GUI NFC card.

**Comment by seud0nym** [comment]
I have added a button underneath the password:
<img width="457" alt="image" src="https://user-images.githubusercontent.com/41851175/144399796-dfdcfbc6-b290-4610-ad06-a0b4350f1a5c.png">


And it takes you this screen:
<img width="864" alt="image" src="https://user-images.githubusercontent.com/41851175/144399539-4db07079-4eb6-4195-a962-2adac75f0882.png">

That is a real QR code: you can scan it with your phone.

You can hide the logo, SSID and/or password before printing. Example of print dialog, with password turned off:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/41851175/144400701-b9a47fe3-f64b-44a5-952b-243b0a35b95f.png">

**Comment by bones-was-here** [comment]
Looks Good To Me :)

**Comment by seud0nym** [comment]
In latest release (2021.12.06) available now.
