### ISSUE TITLE
IPv6 Internet Card

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#51]
For some reason the WAN IP address is not showing on the internet card, but can confirm ipv6 works. Just not showing the ip address on internet access when it supposed to.

Maybe it just missing the "framed" ipv6 or something?

![Screenshot 2021-12-02 111157](https://user-images.githubusercontent.com/45726972/144339943-31ac55c5-673d-4ea4-b379-4ff36aedb125.png)

**Comment by bones-was-here** [comment]
My v6 address (and prefix) are displayed there, but I have a different model (DJN2130)

**Comment by seud0nym** [comment]
Does the Internet Access screen (i.e. after you click on the card) show the correct IP addresses?

What does this command return?
```
transformer-cli get rpc.network.interface.@wan6.
```

The IPv6 address that is show on the card is in `rpc.network.interface.@wan6.ip6addr`.

**Comment by jmytch** [comment]
root@mymodem:~# transformer-cli get rpc.network.interface.@wan6.
rpc.network.interface.@wan6.ipmask [string] =
rpc.network.interface.@wan6.ifname [string] = pppoe-wan
rpc.network.interface.@wan6.ipaddr [string] =
rpc.network.interface.@wan6.name [string] =
rpc.network.interface.@wan6.default_gateway_ping [string] = None
rpc.network.interface.@wan6.nexthop [string] =
rpc.network.interface.@wan6.ipv6defaultgateway [string] = fe80::6600:f1ff:fe68:1200
rpc.network.interface.@wan6.dnsserver2_query [string] = None
rpc.network.interface.@wan6.dnsserver1_query [string] = None
rpc.network.interface.@wan6.ipv6uniqueglobaladdr [string] = 2XXX:XXXX:XXX:XXX:XXXX:XXXX:XXXX:bba0/64
rpc.network.interface.@wan6.ip6prefix [string] =
rpc.network.interface.@wan6.ip6addr [string] =
rpc.network.interface.@wan6.dnsserver2_ping [string] = None
rpc.network.interface.@wan6.dnsservers [string] =
rpc.network.interface.@wan6.ipv6dhcpaddresspool [string] =
rpc.network.interface.@wan6.ipv6uniquelocaladdr [string] = 2XXX:XXXX:XXX:XXX:XXXX:XXXX:XXXX:bba0/64
rpc.network.interface.@wan6.status_ping_test [string] = Done
rpc.network.interface.@wan6.subnet_addr [string] =
rpc.network.interface.@wan6.type [string] = wan
rpc.network.interface.@wan6.up [boolean] = 0
rpc.network.interface.@wan6.proto [string] = pppoe
rpc.network.interface.@wan6.static_dns_servers [string] =
rpc.network.interface.@wan6.rx_bytes [unsignedInt] = 0
rpc.network.interface.@wan6.tx_bytes [unsignedInt] = 0
rpc.network.interface.@wan6.available [boolean] = 1
rpc.network.interface.@wan6.ip6prefix_assignment [string] =
rpc.network.interface.@wan6.uptime [unsignedInt] =
rpc.network.interface.@wan6.ipv6linklocaladdr [string] = fe80::98a8:f580:6ef2:bba0
rpc.network.interface.@wan6.dnsserver1_ping [string] = None
rpc.network.interface.@wan6.nexthop_ping [string] = None
rpc.network.interface.@wan6.NTPServers [string] =
rpc.network.interface.@wan6.dnscheck [boolean] = 0
rpc.network.interface.@wan6.ppp.state [string] =
rpc.network.interface.@wan6.ppp.uptime [string] =
rpc.network.interface.@wan6.ppp.ll_intf [string] = pppoe-wan
rpc.network.interface.@wan6.ppp.error [string] =
rpc.network.interface.@wan6.ppp.ll_dev [string] = pppoe-wan

Had to remove the ipv6 ip into X's.

**Comment by jmytch** [comment]
Yeah like you said should have IPv6 in that `rpc.network.interface.@wan6.ip6addr` section however doesnt display anything there. But IPv6 still working on internet, and ipv6 test which is odd.

**Comment by seud0nym** [comment]
What I was expecting to see was that rpc.network.interface.@wan6.ip6prefix matched the :503::/64 shown on your ISP site.

And I definitely wasn't expecting to see a /64 on the unique local/global addresses. I am no networking expert, but a unique IPv6 address should end with /128 as far as I am aware.

I assume that it was working but you have now churned to a new ISP. Is that correct?

Try changing the "IPv6 Address Request" config under Internet Access from "Force" to "Try". An Exetel user had to do that.

You could also try changing the the "IPv6 Prefix Request" to match the range shown on your ISP page (/64).

And maybe turn off "IPv6 Force Prefix".

Or combinations of the above three suggestions... :-)

Also, it looks like your IPv6 address was ending with 16b7 from your initial images. Does that change? 

Does this return anything?
```
transformer-cli get rpc.network.interface. | grep -i 16b7
```
(If the 16b7 has changed, substitute in the new ending.)

**Comment by seud0nym** [comment]
Were you able to try any of my suggestions? Is it now working?
