### ISSUE TITLE
Four top line graphs now missing

### ISSUE THREAD

**Issue by stewielives** [seud0nym/tch-gui-unhide#53]
Just updated to 6 December release.
The four graphs along the top (CPU, RAM, DL and UL) are gone.
Using a DJA0230. Everything was right before the update.
Are these options hidden in a menu?
I tried doing a fresh install of tch-gui-unhide and they're still gone.
CPU and RAM are still reporting inside the DJA0230 tile.
Thanks.

**Comment by willat8** [comment]
Same thing happened to me, I went back and re-ran tch-gui-unhide with the original switches I used and the graphs came back.

**Comment by stewielives** [comment]
I tried re running it. No luck.

What do you mean by original switches?

**Comment by seud0nym** [comment]
Sounds like the previous settings detection isn't working properly. Strange. I didn't make any changes in that area.

It can happen if you run, then  Ctrl-C to interrupt, then re-run.

Re-run with:
```
./tch-gui-unhide -Ci -y
```
and they should come back.

I will have a look at why

**Comment by stewielives** [comment]
That worked. Thanks.

**Comment by seud0nym** [comment]
I can't see why it wouldn't have picked up the previous settings. I have tried it a couple of times, and it seems to work correctly.

**Comment by willat8** [comment]
FWIW I used `./tch-gui-unhide -U` to do the upgrade and this happened to me, didn't do any Ctrl-C now or in the past. I have the four graphs on a single tile. No other setting got missed.

**Comment by seud0nym** [comment]
Very strange. I also tried `./tch-gui-unhide -U` in one of my tests, and it worked as expected. 
I hate things that aren't reproducible :-(

**Comment by stewielives** [comment]
If it helps, I did the update from the browser when the update notification came through.

**Comment by seud0nym** [comment]
I still haven't been able to reproduce this, so I have changed the way the chart cards are processed during installation. Prior to this change, unused chart cards were deleted, so they were unavailable in the Management Theme tab to show or hide. This change keeps all chart cards, so if they do go away, you can at least redisplay them through the GUI.

Fixed in next release.
