### ISSUE TITLE
Run an NTP Server

### ISSUE THREAD

**Issue by willat8** [seud0nym/tch-gui-unhide#54]
In the latest update with the "DJA0230 as NTP Server" in the GUI, I can see that sets DHCP option 42. Very handy- thanks. Is it also meant to turn on the NTP server in /etc/config/system?

    uci set system.ntp.enable_server="1"

I'm not sure if this was a problem with my config file or not because I still had to do that manually to get the NTP server working.

**Comment by seud0nym** [comment]
I think it might be a problem with your config. I just checked ` /etc/config/system` in .rbi files for the following releases:
```
vant-y_17.2.0284-820-RA/etc/config/system:15:           option enable_server '1'

vbnt-v_17.2.0288-820-RA/etc/config/system:15:           option enable_server '1'
vbnt-v_17.2.0468-820-RA/etc/config/system:15:           option enable_server '1'
vbnt-v_18.1.c.0462-950-RA/etc/config/system:15:         option enable_server '1'
vbnt-v_18.1.c.0549-MR17-RB/etc/config/system:15:        option enable_server '1'
vbnt-v_20.3.c.0329-MR19-RB/etc/config/system:15:        option enable_server '1'
vbnt-v_20.3.c.0389-MR20-RA/etc/config/system:15:        option enable_server '1'

vcnt-a_18.1.c.0462-950-RB/etc/config/system:15:         option enable_server '1'
vcnt-a_18.1.c.0514-950-RB/etc/config/system:15:         option enable_server '1'
vcnt-a_18.1.c.0543-950-RA/etc/config/system:15:         option enable_server '1'
vcnt-a_18.1.c.0585-MR7.1-RA/etc/config/system:15:       option enable_server '1'
vcnt-a_20.3.c.0329-MR19-RB/etc/config/system:15:        option enable_server '1'
vcnt-a_20.3.c.0389-MR20-RA/etc/config/system:15:        option enable_server '1'
```

The defaults are all '1'...

**Comment by willat8** [comment]
Excellent, thanks.

**Comment by seud0nym** [comment]
I have added (in the next release) an option to enable or disable the NTP server, and if it is disabled, the option to send the device as the NTP server via DHCP will not show.
