### ISSUE TITLE
Custom DNS option request

### ISSUE THREAD

**Issue by gyCfjSnO** [seud0nym/tch-gui-unhide#55]
When setting the Primary & Secondary DNS under Custom DHCP Options (Local Network tile) can we please have ability to use Custom DNS and not have to pick from the current drop down list?

I currently get around this limitation by modifying the dhcp under /etc/config/

Thank you 😀

**Comment by seud0nym** [comment]
You can add DNS Servers to the drop down lists using files named ipv4-DNS-Servers and/or ipv6-DNS-Servers, as described in https://github.com/seud0nym/tch-gui-unhide#lan-client-dns-servers.

**Comment by seud0nym** [comment]
The next release will allow you to add a custom IPv4 DNS server address IP into the LAN screen.
