### ISSUE TITLE
DNS Intercept & Local Network

### ISSUE THREAD

**Issue by gyCfjSnO** [seud0nym/tch-gui-unhide#58]
IPv4 Primary DNS in the Local Network tab keeps reverting back to DJA0231 on reboot and the following error message displays ```DNS Intercept is enabled, so IPv4 Primary DNS should be set to '192.168.0.2'.``` BUT the DHCP is still giving out 192.168.0.2 to clients so unsure what is going on, thought you may want to look into it?

**DHCP shows correct DNS -**
```
config dhcp 'lan'
	option instance 'main'
	option interface 'lan'
	option start '2'
	option limit '253'
	option leasetime '1d'
	option force '1'
	option ra_management '0'
	option ra_mininterval '200'
	option ra_maxinterval '600'
	option ra_lifetime '1800'
	option ra_hoplimit '64'
	option dhcpv6 'disabled'
	option ra 'disabled'
	option dhcpv4 'server'
	list dhcp_option '6,192.168.0.2'
```

**GUI shows DJA0231 -**
<img width="857" alt="image" src="https://user-images.githubusercontent.com/49738152/147854440-6b989ac1-bb0c-4d72-b7e8-53853c38ccde.png">

**Intercept Settings -**
<img width="852" alt="image" src="https://user-images.githubusercontent.com/49738152/147854462-9db5a624-6821-41ab-bd64-8724e66a7133.png">

**Intercept Status -**
<img width="675" alt="image" src="https://user-images.githubusercontent.com/49738152/147854473-62e815c1-81f8-40da-ba5e-4987bdc5188d.png">

**Comment by seud0nym** [comment]
Hmm. 

What is your firmware version?
Is 192.168.0.2 in your ipv4-DNS-Servers file, or did you add it as a Custom IP address, or neither?

**Comment by willat8** [comment]
I've also noticed after the 2022.01.01 update, specifying a custom DNS server in the UI
![image](https://user-images.githubusercontent.com/2316013/147871405-3e128f52-31b2-482c-bbc2-b6368de63fba.png)
keeps getting reset back to DJA0230 for me. However it seems to be a cosmetic issue, the correct DNS server is handed out to DHCP clients.

**Comment by gyCfjSnO** [comment]
> Hmm.
> 
> What is your firmware version? Is 192.168.0.2 in your ipv4-DNS-Servers file, or did you add it as a Custom IP address, or neither?

I have been able to have it show via the GUI if I rerun the unhide script with the DNS server file.

I had set 192.168.0.2 initially via the GUI using the new custom IP option.

```Firmware Version	20.3.c.0329-MR19-RA
tch-gui-unhide	2022.01.01@14:55```

**Comment by seud0nym** [comment]
Okay, I think I found it. It should be fixed in the next release.

**Comment by gyCfjSnO** [comment]
> Okay, I think I found it. It should be fixed in the next release.

Let me know if you want me to test

**Comment by seud0nym** [comment]
If you want to test, then download and save the updated file:
```
curl -skL -o /www/docroot/modals/ethernet-modal.lp https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/build/lua/additional/common/lan/www/docroot/modals/ethernet-modal.lp
```
You should just be able to refresh your browser window and try accessing the Local Network screen again. Error message should not appear.
```

**Comment by gyCfjSnO** [comment]
> If you want to test, then download and save the updated file:
> 
> ```
> curl -skL -o /www/docroot/modals/ethernet-modal.lp https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/build/lua/additional/common/lan/www/docroot/modals/ethernet-modal.lp
> ```
> 
> You should just be able to refresh your browser window and try accessing the Local Network screen again. Error message should not appear.

Thank you, that's fixed it 👍
