### ISSUE TITLE
RAM Usage wrong units

### ISSUE THREAD

**Issue by Krazy998** [seud0nym/tch-gui-unhide#6]
Hi,

The new RAM usage seems to be in the wrong units. I believe the memory free shown should be in MB instead of KB.

 RAM: 87.02KB Free [420.14KB]

While I can use the free -k specifically I believe it makes sense.

[free]
             total         used         free       shared      buffers
Mem:        430228       364532        65696            0        23236
-/+ buffers:             341296        88932

**Comment by seud0nym** [comment]
Duh! I had the value in KB originally, but it took up too much space, so I changed it to MB, but didn't change the label!

Thanks for pointing it out.

**Comment by Krazy998** [comment]
Easy as - Thanks so much for all your work on this!
