### ISSUE TITLE
Experimental minification and Samba users

### ISSUE THREAD

**Issue by willat8** [seud0nym/tch-gui-unhide#60]
I've noticed that running `tch-gui-unhide` with the `-my` option causes my users defined on the file sharing screen to not be listed anymore. Re-running with `-mn` causes them to reappear.

**Comment by seud0nym** [comment]
Overly aggressive space removal... I will fix for the next release.

Re-run with the `-my` option then apply this fix:
```
sed -e 's/User(\[\^:\]\*):(/User%s([^:]*):%s(/' -i /www/docroot/modals/contentsharing-modal.lp
```

Did you notice any improvement in performance when running with minified code?

**Comment by willat8** [comment]
Thanks for that, the fix works.

Subjectively it seems snappier after minifying.

I've just noticed the Wifi modal isn't loading too.

**Comment by seud0nym** [comment]
Ahh, I think I see the problem with WiFi. I tested my fix for that on 20.3.c.0389, but it looks like it isn't working on FW before that (e.g. 20.3.c.0329). I assume you haven't upgraded to 20.3.c.0389 yet? Anyway, this should fix it:
```
sed -e 's/\(if(bandLockState\)/;\1/' -i /www/docroot/modals/wireless-modal.lp
```

**Comment by willat8** [comment]
Yep, I'm on 0329. Thanks for the heads up, will upgrade.

**Comment by seud0nym** [comment]
Sorry, I wasn't suggesting that you had to upgrade. I have checked in a fix that will work for all firmware.
