### ISSUE TITLE
PLEASE add support for dant-o_CRF685-16.1.7565-580-RC Thankyou!

### ISSUE THREAD

**Issue by acejr1337** [seud0nym/tch-gui-unhide#62]
Please add support for dant-o_CRF685-16.1.7565-580-RC

So I can run the script on my Telstra TG797n v3 

Thanks.

**Comment by seud0nym** [comment]
I am sorry, but I will not be supporting firmware versions less than 17.2

I suggest you try https://github.com/Ansuel/tch-nginx-gui
