### ISSUE TITLE
Request de-telstra utility have -y confirmation options

### ISSUE THREAD

**Issue by bravohe** [seud0nym/tch-gui-unhide#63]
Request de-telstra utility have confirmation change option as sometime I just ./de-telstra -G to remove Guest wifi network but it will remove default Telstra  configuration. Or

How do I restore CWMP service manually?

**Comment by seud0nym** [comment]
What I do is use the `--save-defaults` option. So, if you want to keep the Telstra configuration, run:
```
./de-telstra -kT --save-defaults
```
This doesn't actually run the command: it creates a file called .defaults.de-telstra, which it then re-reads every time you run the command and applies your personal defaults. You can see your default options with:
```
./de-telstra --show-defaults
```
Command line options always override saved defaults, unless you use the `--no-defaults` option.

> How do I restore CWMP service manually?

I have never tried it, but this should fix most of it:
```
cp /rom/usr/lib/opkg/info/cwmpd.* /usr/lib/opkg/info/
cp /rom/usr/lib/opkg/info/conf-cwmpd.* /usr/lib/opkg/info/
for f in $(cat /usr/lib/opkg/info/*cwmpd*.list); do [ ! -f "$f" ] && cp "/rom$f" "$f"; done
/rom/etc/uci-defaults/tch_0090-cwmpd
cp /rom/etc/boards/$(uci get env.rip.board_mnemonic)/config/usr/lib/lua/wansensingfw/failoverhelper.lua /usr/lib/lua/wansensingfw/failoverhelper.lua
uci add iqos rule
uci set iqos.@rule[-1].target='cwmpd'
uci set iqos.@rule[-1].destports='7547,51007'
uci commit iqos
/etc/init.d/iqos restart
/etc/init.d/cwmpd enable
/etc/init.d/cwmpd start
```

**Comment by willat8** [comment]
To piggy-back on this, is it possible to override parts of the `-M` switch, say with `-fy`?

**Comment by seud0nym** [comment]
> To piggy-back on this, is it possible to override parts of the `-M` switch, say with `-fy`?

You can already do this now. Just specify `-M` first, then specify your override switches (in your case `-M -fy`).

**Comment by seud0nym** [comment]
I have updated de-telstra with a confirmation prompt. You can download the updated version now:
```
./de-tesltra -U
```

**Comment by bravohe** [comment]
The newest version de-telstra looks great and tidy. Thank you.

**Comment by bravohe** [comment]
I try to use the latest de-telstra version and it have some error as below:
root@mygateway:~/tch-gui-unhide-2022.01.01/utilities# ./de-telstra -G
  Keep Telstra AIR enabled                 -ka         No
  Keep CWMP installed                      -kc         Yes
  Keep default public authorized keys      -kk         No
  Keep Telstra APN check                   -kl         No
  Keep Telstra monitoring/data collection  -km         Yes
  Keep Telstra NTP servers                 -kn         No
  Keep Telstra QoS VoWiFi reclassify rules -kq         No
  Keep noexec on filesystems               -kx         No
  Host name                                -hu         Unchanged
  Domain name                              -du         Unchanged
  DNS servers                              -nu         Unchanged
  NAT ALG Helpers                          -au         Unchanged
  Content Sharing                          -cu         Unchanged
  DECT Emission Mode                       -eu         Unchanged
  File Sharing                             -fu         Unchanged
  Power Saving                             -pu         Unchanged
  NFC                                      -qu         Unchanged
  Printer Sharing                          -ru         Unchanged
  Telephony                                -tu         Unchanged
  UPnP                                     -uu         Unchanged
  WPS                                      -wu         Unchanged
  RTFD root protection                     -Fu         Unchanged
  Minimum memory mode                      -M          No
  Remove Guest Wi-Fi                       -G          Yes
  Configure opkg                           -o          No
   - opkg repository                       -O17        17
[de-telstra]: Apply changes? Enter y to confirm otherwise just [Enter] to exit: y
./de-telstra: line 341: flock: not found
[de-telstra]: ERROR! Already running!

Firmware: 17.2.0284-820-RA

**Comment by seud0nym** [comment]
Sorry about that. It should be fixed now. Try downloading it again.

**Comment by bravohe** [comment]
Thank you. It works perfectly.
