### ISSUE TITLE
[Cosmetic] Missing variant in de-telstra help text

### ISSUE THREAD

**Issue by willat8** [seud0nym/tch-gui-unhide#67]
I did a firmware upgrade on my DJA0230 to 20.3.c.0389-MR20-RA, and then re-ran `de-telstra` from scratch. I noticed in the help text

    -h u|d|s|<hostname>
       where u            Leave hostname unchanged
             d            Set the hostname to $VARIANT
             s            Set the hostname to $VARIANT-$MAC_HEX

That `$VARIANT` and `$MAC_HEX` were coming through as blank.

P.S. Thanks for all the recent new features

**Comment by seud0nym** [comment]
Thanks for reporting this. I tidied the code and didn't notice it. Fixed now, if you want to `./de-telstra -U` to download the latest version.
