### ISSUE TITLE
tch-gui-unhide -U broken

### ISSUE THREAD

**Issue by willat8** [seud0nym/tch-gui-unhide#69]
I'm trying to upgrade from 2022.02.02 and getting the following

    root@DJA0230:~# ./tch-gui-unhide -U
    19:48:31: Attempting to download latest release for FW 20.3.c from GitHub...
    19:48:31: ERROR! No latest release found on GitHub for FW 20.3.c

Upgrading via the web UI worked and `./de-telstra -U` also worked fine.

**Comment by seud0nym** [comment]
Well, that is embarrassing. I attached the wrong files to the release! (I attached the scripts rather than tar files.)

Thanks for letting me know. It is fixed now.
