### ISSUE TITLE
icons color to match the theme?

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#7]
currently I have light + purple theme but the icons looks abit off as it showing blue icons. maybe when setting to color specific theme, it should change the color of the icons? 

![Untitled](https://user-images.githubusercontent.com/45726972/95045642-c974ee00-0725-11eb-8354-a9a9aaa88a57.png)

**Comment by seud0nym** [comment]
I will never please everybody with colors! How about I make those status icons match the theme color, like this:
![image](https://user-images.githubusercontent.com/41851175/95048113-fe3b7200-0732-11eb-8b4d-753aaea684c4.png)

**Comment by jmytch** [comment]
That looks good, if you dont want to do those purple I guess black/grey would look fine on the light theme like the one from Diagnostics those black icons are fine. It abit odd having blue along with the purple just saying lol.
