### ISSUE TITLE
Devices screen broken for me on 2022.02.13

### ISSUE THREAD

**Issue by willat8** [seud0nym/tch-gui-unhide#70]
After upgrading from 02.02 to 02.13 using the web UI, I can't access the Devices screen any more. It shows the green spinner but never loads. I have minification enabled.

**Comment by seud0nym** [comment]
Can you please run this, and post back the results?
```
grep nginx /root/log/messages.log
```

**Comment by willat8** [comment]
Sure

    Sun Feb 13 18:42:16 2022 daemon.warn nginx: 2022/02/13 18:42:16 [warn] 6128#0: *144 [lua] session.lua:367: new(): new session for admin, client: 192.168.0.189, server: localhost, request: "GET / HTTP/1.1", host: "dja0230"

**Comment by seud0nym** [comment]
Well, that is unexpected. Do you know how to use the Developer console in Chrome/Edge/Firefox? Open it with `Ctrl-Shift-I` and then click on the Devices card to open it. The console should show an error.

I haven't been able to reproduce this on my DJA0231 running 20.3.c.0389. You seem to have a DJA0230 - what firmware version?

Also, can you re-run `./tch-gui-unhide -mn -y` to see if still happens?

**Comment by willat8** [comment]
The XHR request to device-modal.lp is returning HTTP 500, but the response body is just the generic nginx error page.

The behaviour is the same after disabling minification.

**Comment by seud0nym** [comment]
> The XHR request to device-modal.lp is returning HTTP 500, but the response body is just the generic nginx error page.

I would have expected that there would be a log message with 500 error code. Are there _any_ error messages in the log?

**Comment by seud0nym** [comment]
> Happening to me as well.

Do _you_ have any errors in your log?

> Should I reboot?

Try this first. The only thing that has changed in Devices is client bandwidth monitoring, which is off by default. What does this return:
```
transformer-cli get rpc.gui.bwstats.enabled
transformer-cli get rpc.gui.bwstats.show_in_device_list
```

**Comment by willat8** [comment]
root@DJA0230:~# transformer-cli get rpc.gui.bwstats.enabled
    rpc.gui.bwstats.enabled [boolean] = 0
    root@DJA0230:~# transformer-cli get rpc.gui.bwstats.show_in_device
_list
    rpc.gui.bwstats.show_in_device_list [boolean] = 0

**Comment by seud0nym** [comment]
The only thing I can suggest without a log to diagnose the issue is to remove tch-gui-unhide and then re-apply it.
```
./tch-gui-unhide -r
./tch-gui-unhide -y
```
(Add your options like -h and -m after the -y, because removing it means it won't be able to auto-detect existing settings.)

**Comment by seud0nym** [comment]
Sorry - brain rushing ahead. Those transformer-cli results look normal. A reboot may also be helpful - sometimes I have noticed weird issues with 20.3.c.0389 that only a reboot fixes....

**Comment by willat8** [comment]
A reboot made the logs start working again, here's the error

    Mon Feb 14 11:55:54 2022 daemon.err nginx[5965]: 2022/02/14 11:55:53 [error] 6100#0: *56 lua entry thread aborted: runtime error: [string "/modals/device-modal.lp"]:129: attempt to index local 'I' (a nil value)
    Mon Feb 14 11:55:54 2022 daemon.err nginx[5965]: stack traceback:
    Mon Feb 14 11:55:54 2022 daemon.err nginx[5965]: coroutine 0:
    Mon Feb 14 11:55:54 2022 daemon.err nginx[5965]:        [string "/modals/device-modal.lp"]:129: in function 'content'
    Mon Feb 14 11:55:54 2022 daemon.err nginx[5965]:        /usr/lib/lua/web/web.lua:249: in function 'process'
    Mon Feb 14 11:55:54 2022 daemon.err nginx[5965]:        content_by_lua(nginx.conf:128):4: in function <content_by_lua(nginx.conf:128):1>, client: 192.168.0.132, server: localhost, request: "GET /modals/device-modal.lp HTTP/1.1", host: "dja0230", referrer: "http://dja0230/gateway.lp"

**Comment by seud0nym** [comment]
Excellent! I think I see the issue.

Try this:
```
sed -e 's/\(show_in_device_list"),\)nil,nil/\1{},{}/' -i /www/docroot/modals/device-modal.lp
/etc/init.d/nginx restart
```

and let me know how you go.

**Comment by gyCfjSnO** [comment]
`root@mymodem:~# grep nginx /root/log/messages.log`
`root@mymodem:~# transformer-cli get rpc.gui.bwstats.enabled`
`rpc.gui.bwstats.enabled [boolean] = 0`
`root@mymodem:~# transformer-cli get rpc.gui.bwstats.show_in_device_list`
`rpc.gui.bwstats.show_in_device_list [boolean] = 0`

**Comment by seud0nym** [comment]
> GET http://192.168.0.1/modals/device-modal.lp 500 (Internal Server Error)

Thanks. If you want, you can try the following fix:
```
sed -e 's/\(show_in_device_list"),\)nil,nil/\1{},{}/' -i /www/docroot/modals/device-modal.lp
/etc/init.d/nginx restart
```

**Comment by willat8** [comment]
Working a treat now, thanks!

**Comment by seud0nym** [comment]
Good news. Thanks for your help in troubleshooting.
