### ISSUE TITLE
Cosmetic Request - Icon Overhaul

### ISSUE THREAD

**Issue by gyCfjSnO** [seud0nym/tch-gui-unhide#73]
Any chance that all icons could be overhauled with using something like [Font Awesome](https://fontawesome.com/search?m=free&s=solid%2Cregular%2Cbrands)

**Comment by seud0nym** [comment]
They are already FontAwesome icons (albeit quite old).

This would be a very big job. Icons are referenced in a lot of places, some as CSS classes and in other places by the glyph character.

I will think about it, but tackling it doesn't excite me.

**Comment by seud0nym** [comment]
Sorry - I don't think I am going to do this one.
