### ISSUE TITLE
Two ideas in mind

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#78]
May, or may not be a good idea but here it is :-)

First idea, I would like to see the WiFi Channels on the WiFi card something like this;

If the Channel is set to '**Auto**' then display Current Channel beside it in (Brackets), the brackets would be the Current Channel from the inside the WiFi card as example seen below
![example-of-auto-channels](https://user-images.githubusercontent.com/45726972/157213606-a0eebc1a-4ed5-470d-ab33-c423710df5dc.png)

If the Channel have set to specific channel like 11 then what it would look like below;
![example-of-fixed-channels](https://user-images.githubusercontent.com/45726972/157213636-c9b3324f-3b34-45e2-8b4e-da5065727fc5.png)

What it currently looks like inside the WiFi card;
![Screenshot 2022-03-08 182449](https://user-images.githubusercontent.com/45726972/157213277-45068abe-aee9-4382-9890-c653e4c20ea9.png)

-----
Second idea, maybe add icons on the left to the Titles? See example;
![Screenshot 2022-03-08 185956](https://user-images.githubusercontent.com/45726972/157213992-e60357af-cc2a-4f08-a0cf-2a1dd623a4c6.png)

Dark (night) mode;
![Screenshot 2022-03-08 201025](https://user-images.githubusercontent.com/45726972/157218440-ba20dd8a-3d69-4f91-a2a6-54482b6a8b26.png)

Btw, maybe to have setting like the Card Icons in the Management, under Theme section.
**Card Icons**: 
- Visible ☑️
- Not Visible 

**Title Icons:**
- Visible
- Not Visible ☑️

However they like the icons to be shown, maybe one dont want card icons but want icons beside a title? :-)

EDIT: Had to edit those screenshot to cover the info and reupload them.
EDIT2: Those icons are all 24x24 if you were wondering. I only did them in the photoshop and borrowed the white icons from [https://icons8.com/icons/set/world--white](https://icons8.com/icons/set/world--white) so all credits goes to them.

**Comment by seud0nym** [comment]
There isn't enough space on the card for the channel info with your layout if the Guest SSIDs aren't deleted, and the channel information would be duplicated (because the channel is based on the radio, not the SSID). So, I have changed it around and it now looks like this:

<img width="221" alt="image" src="https://user-images.githubusercontent.com/41851175/157802972-8e461ab3-94be-47c7-866e-8c88ef957403.png">

I didn't add that the channel (or channel width) selection was automatic. I don't think it adds any value.

Not sure about the title icons. I don't mind the card background icons, but I am not a big fan of them next to the card title. I am not sure that it really adds anything.

**Comment by jmytch** [comment]
Alright thanks for checking. Thought that you could add it manually to show (Auto) and then show the channels.

**Comment by seud0nym** [comment]
I could, but it takes up space without adding any useful information (IMO).

**Comment by jmytch** [comment]
Not sure if this was to use light greyish in the latest update? Was a bit hard to read in the light themes lol. 

<img width="283" alt="Screen Shot 2022-03-20 at 3 23 08 pm" src="https://user-images.githubusercontent.com/45726972/159149435-7fea43dd-96cf-411e-b002-09e10ca226a6.png">

Also can't you put the Channel, and its current channel along channel width underneath the WiFi name which would make sense or are you trying to save some spaces on the WiFi card? 

![157213606-a0eebc1a-4ed5-470d-ab33-c423710df5dc](https://user-images.githubusercontent.com/45726972/159149521-8075cb59-c2e1-47d2-bd96-7b1522c236c7.png)

**Comment by seud0nym** [comment]
Yes, it is a space issue. Whilst your layout works when you have 2 SSIDs, if you still have the Guest SSIDs enabled they don't all fit on the card. Plus, because the SSIDs share the same channel, the information is redundantly duplicated.

Yes, the light grey was a mistake that I thought I had fixed. I have now uploaded a fixed release. Use `./tch-gui-unhide -U` to update. Sorry about that.

**Comment by jmytch** [comment]
Oh all good, I've updated and it is fixed 👍🏼 

Maybe this one will give you better idea of the card?

Guest Disabled;
![1](https://user-images.githubusercontent.com/45726972/159150805-c773b5eb-0bc7-429a-8874-5405b1b896c3.png)

Guest Enabled;
![Screenshot 2022-03-20 160832](https://user-images.githubusercontent.com/45726972/159150703-286297a1-42fd-450d-ba77-41c5384e0533.png)

Now with the Guest network part which I forgotten about and I don't know how important it is needed to have current channel and it's bandwidth width for the guest as most people out there would just focus on the primary WiFi that shows it. But having guest disabled nor enabled is a good way for them to know which is good enough?

**Comment by seud0nym** [comment]
But that doesn't show the Guest SSIDs, which are configurable. They don't have to be called Guest. In fact, when I had mine enabled, they weren't. 

And the radios themselves can be turned off, and the new display shows that, whereas your alternate display doesn't allow that.

**Comment by jmytch** [comment]
Oh ignore the middle line beside the WiFi SSID lol. Yeah I don't think the radios are necessary beside the Current Channels however maybe just put a bullets if they allow it. If not then without it is fine as long there is some space underneath it.

This might be pointless of alternative idea for the guest wifi ssid where it would display it after the "enabled". That the longest WiFi name I could think of lol.

![12](https://user-images.githubusercontent.com/45726972/159151426-d0823e54-fd85-4056-ac80-c4e26f9b4897.png)

----
Other than that, "if" we disabled band steering, then hide that by default and show Guest WiFi SSID underneath "Guest Enabled" part? 

If one person has both enabled, then the picture above might do the little trick showing the guest ssid in (brackets), however if it doesn't allow the (brackets), then maybe use the wifi icon instead of the brackets.

![123](https://user-images.githubusercontent.com/45726972/159151729-530be07b-049b-4680-9c06-f9129620d368.png)

**Comment by seud0nym** [comment]
If the Guest 2.4GHz and 5GHz SSIDs are different (which they would be if band steering was disabled), it doesn't fit, even if you hide the band steering indicator.

And I like it the way it is now...
