### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#8]
With the themes, I was thinking about this lately. From what I see in the readme txt on here, there is green, orange, purple, blue, monochrome as I feel like you are trying to match the color from the logo? I thought that is pretty cool, maybe to add more theme colors such as red, cyan, light purple?, lime etc

Don't know if yellow, red would be suitable on light theme but for sure it suits the night theme. For light theme I would assume dark yellow, dark red and so on? 

![Technicolor_logo svg](https://user-images.githubusercontent.com/45726972/95068424-a0198980-0748-11eb-9389-dcc0a5f469d0.png)

**Comment by jmytch** [comment]
Also maybe start adding "Theme" cards where people can adjust to their liking, something like this;

Dark Mode: (toggle on), or (toggle off) for light
Theme: selection to pick from Telstra to specific colors to their liking

Apply / Cancel, after hitting apply it would take them back to log in again?

**Comment by seud0nym** [comment]
The way the theme changes are implemented at the moment is by editing files. That isn't as simple to do or apply via the GUI.

I will have to think about it.

**Comment by seud0nym** [comment]
I have just pushed up a major re-work of the way that themes are handled. It also includes the ability to change the theme from within the GUI (it will be on the System Extras screen).

I also added a red variation.

I need to do some more testing, but it will be in the next release.
