### ISSUE TITLE
Smokeping

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#80]
Is it possible to add smokeping? Would be nice to have in our 0230 / 0231 modems. Not sure if OpenWRT or router would work with it. From simple googling - https://michele.blog/openwrt-followup-improved-latency-ping/ and then again it was on the Linksys modem so yeah I thought of this if it possible.

https://forum.openwrt.org/t/network-latency-monitoring/77303

**Comment by gyCfjSnO** [comment]
+1

**Comment by seud0nym** [comment]
Honestly, this is unlikely. It looks like stock OpenWrt has inbuilt support collecting stats and RRDTool in LuCI, which makes adding these sorts of graphs simpler. Technicolor devices just don't have that support.

I will think about it, though.

**Comment by seud0nym** [comment]
I don't think I am going to do this. Sorry.
