### ISSUE TITLE
17.2 Issue when disabling power saving

### ISSUE THREAD

**Issue by ilium007** [seud0nym/tch-gui-unhide#83]
Output below when specifying `-pn`

```
[de-telstra]: Disabling power saving...
pwrctl: too many options
Usage: pwrctl start
       pwrctl stop
       pwrctl config ...
                 [--cpuspeed <0|1|2|4|8|256>]: 1-8 -> sets speed @ 1/1, 1/2, 1/4 or 1/8th of fullspeed in ASYNC mode.
                                               0   -> 1/1 in SYNC mode
                                               256 -> 1/8 ASYNC when entering wait, 1/1 SYNC otherwise.
                 [--wait on|off]             : keeps CPU in sleep state without spinning
                 [--sr on|off]               : DRAM Self Refresh Mode Enable (requires Wait enabled)
                 [--ethapd on|off]           : Ethernet Auto Power Down Enable
                 [--eee on|off]              : Energy Efficient Ethernet Enable
                 [--autogreeen on|off]       : AutoGreeen Enable
                 [--avs on|off|stopped|deep] : Adaptive Voltage Scaling Enable
                                               on      -> to enable AVS while guaranteeing best performance
                                               stopped -> for testing only, to hold the voltage to its current setting
                                               deep    -> for more savings, with possible impact on WiFi data rates
                                                          (The deep option only makes a difference on some chips)
       pwrctl show
       pwrctl help
```

**Comment by seud0nym** [comment]
Well, that's no good :-( 

I did recently make a change to that area, so I will load up 17.2 on my test box and fix it. Thanks for the issue.

**Comment by ilium007** [comment]
I noticed that this setting remains green:

<img width="284" alt="image" src="https://user-images.githubusercontent.com/732766/167055534-a71016bc-f331-41e5-931f-ae12c6e1c2e4.png">

**Comment by seud0nym** [comment]
So it looks like your TG799vac doesn't support Deep Green Mode, which is why you got that de-telstra error. I have uploaded a fix. You can try it by executing:
```
./de-telstra -U
```
which will download the updated version of the script, and then you can run it again with `-pn` option to test it.

I will also have to make a change to tch-gui-unhide to remove Deep Green Mode for your device. I will let you know when you can try that.

**Comment by ilium007** [comment]
This is a bridged modem with no route to internet, I'll have to download and SCP to run it again. I'll let you know the outcome.

**Comment by ilium007** [comment]
The script downloads from https://github.com/seud0nym/tch-gui-unhide/releases/latest and a new release hasn't been built yet. I'll test once there is a build.

**Comment by seud0nym** [comment]
You can manually download the fixed version:
https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/utilities/de-telstra

**Comment by seud0nym** [comment]
Yes, you can, but it doesn't actually do anything.

**Comment by seud0nym** [comment]
Fixed in latest release.
