### ISSUE TITLE
tch-gui-unhide - transformer-cli: Permission denied

### ISSUE THREAD

**Issue by ilium007** [seud0nym/tch-gui-unhide#84]
Noticed this one as well:

```
900@17:03:04: Waiting for transformer service to finish loading...
./tch-gui-unhide-17.2: line 24339: transformer-cli: Permission denied
```

**Comment by seud0nym** [comment]
Hmm. This is a bit weird. I definitely set the execute flag on the file when I copy it to /usr/bin.

I will do some more testing.

**Comment by seud0nym** [comment]
I couldn't reproduce this, but I have added an extra check to make sure that it is executable (the error indicates it is not)

**Comment by seud0nym** [comment]
Fixed in latest release.
