### ISSUE TITLE
17.2 Can't enable bridge mode

### ISSUE THREAD

**Issue by ilium007** [seud0nym/tch-gui-unhide#87]
vant-f_CRF915-17.2.0284-820-RA.rbi

I have run:

`./de-telstra -A -tn -pn -mn -en -nc -h TG799vac -G -M`

and

`./tch-gui-unhide -dy -hn -ln -tl -Cn -vn`

- disabled IPv6
- disabled DHCP, firewall, wifi etc

I go back to the Broadband tab, disable WAN sensing, enable VDSL and save. I then try to enable bridge mode, I get the warning:

<img width="613" alt="image" src="https://user-images.githubusercontent.com/732766/167132657-bc1e7ebf-87f1-44e2-8a63-a0e74920b649.png">

I click confirm but nothing happens, no reboot, no bridge mode.

**Comment by seud0nym** [comment]
I need to see the log from when you clicked the confirm button. Click it again and then run this command in SSH:
```
logread -e nginx
```

**Comment by ilium007** [comment]
I have gone back to 17.2.0188 using sysupgrade and everything is working now including bridge mode.

Just one question, I have enabled the xDSL card but its not showing in the UI. Do I need to wait to have it connected to a VDSL line to show this card?

**Comment by seud0nym** [comment]
The xDSL card currently only displays when the WAN interface is DSL, so it doesn't show when in bridge mode (because there is no WAN interface in bridged mode - everything is on the LANB bridge). This is probably wrong. I will have a look at making it visible in bridged mode.

**Comment by ilium007** [comment]
Ok- so in the meantime is there a way to modify xDSL settings in a VDSL bridge config?

**Comment by seud0nym** [comment]
You can copy back the original card using the following command:
```
cp /rom/www/cards/093_xdsl.lp /www/cards/
```
The refresh your browser. The card will be there and that will give you access to the screen.

**Comment by ilium007** [comment]
That worked - thanks

**Comment by seud0nym** [comment]
I have found that there **is** a problem switching between routed and bridged mode (and/or vice-versa). I have to work out what is causing it.

**Comment by seud0nym** [comment]
Fixed in latest release
