### ISSUE TITLE
17.2 - scheduled tasks can't be toggled off in the UI

### ISSUE THREAD

**Issue by ilium007** [seud0nym/tch-gui-unhide#89]
These green toggle buttons do nothing. I have had to disable in the console `crontab -e`

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/732766/167252708-84891aec-7df9-4e1a-8b7f-7f66326a1cb2.png">

**Comment by seud0nym** [comment]
You have to click the edit button (<img width="17" alt="image" src="https://user-images.githubusercontent.com/41851175/167278427-b5625df1-97de-4d66-9cce-89edb25b0a72.png">) first before you can change the Enabled state.

**Comment by ilium007** [comment]
Ok! Strange UI!

**Comment by seud0nym** [comment]
Yeah, unfortunately it is the way the user interface framework handles rows/records.
