### ISSUE TITLE
SMG3

### ISSUE THREAD

**Issue by scotty03** [seud0nym/tch-gui-unhide#90]
Playing with a LH1000 they do TFTP differently than the Technicolor but it made me think that maybe the SMG3 is doing it this way as well. To get into TFTP mode on the LH1000 you hold down the reset button and plug router in and hold for a few seconds then release the reset button and with your network card set to a fixed ip of 192.168.0.2 or higher and 255.255.255.0 then fire up a browser and goto 192.168.0.1 and see if you have a mini gui that allows to load the firmware.

**Comment by ilium007** [comment]
I'll take a look. That's how I do the HG659's.

**Comment by seud0nym** [comment]
I have tried this a couple of times with no luck.

**Comment by scotty03** [comment]
Oh well was worth a try at least.
