### ISSUE TITLE
Post-upgrade widgets get stuck

### ISSUE THREAD

**Issue by willat8** [seud0nym/tch-gui-unhide#91]
I've noticed sometimes when I perform an upgrade to a new version of tch-gui-unhide, the DJA0230 widget and the CPU/mem/bandwidth widgets refuse to show any more data (they will show 0 for everything except uptime and bandwidth, which shoes 0.01). I had to reboot the router to get it working properly again.

Anyone else experienced this?
Has happened for the most recent release and occasionally prior.

**Comment by seud0nym** [comment]
Did you do your upgrade through the GUI, or a manual upgrade?

**Comment by willat8** [comment]
I did it through the GUI.
I then did it manually as well (before rebooting), but that didn't fix it.

**Comment by seud0nym** [comment]
It is very strange. The stats are only maintained within the web server (nginx), and that is of course stopped/started during the install. If the GUI is working, then that should also be working. If it happens again, try:
```
/etc/init.d/nginx restart
```
and see if that fixes it.

**Comment by willat8** [comment]
Thank you, I'll try that
