### ISSUE TITLE
Log Viewer

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#93]
Weird spam of those kernel on the SMG3, is that normal? 

Yes I'm on PPPoE with a provider
[log.txt](https://github.com/seud0nym/tch-gui-unhide/files/8810349/log.txt)

**Comment by jmytch** [comment]
![Screenshot 2022-06-01 113130](https://user-images.githubusercontent.com/45726972/171310229-ddccbf52-b1a5-4ed0-b088-01f1a369ee8f.png)
![Screenshot 2022-06-01 113151](https://user-images.githubusercontent.com/45726972/171310234-18cbd0cf-409e-4110-977a-0a8e2925f535.png)

**Comment by seud0nym** [comment]
My SMG3s are connected via Ethernet to my LAN, and I am on HFC/IPoE with my RSP, so I wouldn't know what is normal for vDSL/PPPoE.

Seems to be a disconnect/reconnect early on (11:12:17 - 11:12:57), but then no others.

Does your RSP provide IPv6? It is constantly trying to bring up wan6 and wan_6_4. Maybe disable IPv6 if you don't have it.

I can't see how this can be a tch-gui-unhide thing. Might be better to ask on the Whirlpool forum...
