### ISSUE TITLE
DSL bug - SMG3

### ISSUE THREAD

**Issue by jmytch** [seud0nym/tch-gui-unhide#94]
Think something wrong with the broadband on the SMG3 inside the page it indicates as orange led (connecting?) when it supposed to be green? Yes my internet is currently up and am browsing the internet, downloading and watching netflix. Bit odd that it shows orange, when it should show green like on the broadband card.

![Screenshot 2022-06-01 113606](https://user-images.githubusercontent.com/45726972/171310675-a50d5165-8b72-4943-a3bc-67b43acffb81.png)
![Screenshot 2022-06-01 113627](https://user-images.githubusercontent.com/45726972/171310682-f2298ad6-b8e7-49db-ade1-d6b366ae9f8b.png)

**Comment by seud0nym** [comment]
I had a look and the status is determined from the same source for both the card and the screen. So I don't think it is a tch-gui-unhide issue.

I wonder if this is connected to your issue #93? If the connection is dropping out and immediately reconnecting, then it could show green on the card and then orange on the Configuration tab. Seems unlikely that you wouldn't notice an interruption to Netflix or a download, though.

**Comment by jmytch** [comment]
Umm, does ./reset-to-factory-defaults-with-root still works on SMG3? If so I'll give it ago and install tch gui unhide again see why it showing that. Because it the first install with tch gui unhide on the SMG3. I know bank plans are changed on the SMG3, just want to narrow down to why it showing that on SMG3. Dont have that issues on SMG2 and SMG1 for some reason, it just SMG3

**Comment by seud0nym** [comment]
Yes, it does. There are fewer options though - I haven't been able to get the advanced options to work because of the different file system and I can't use the methods that worked in previous generations. But it will RTFD and retain root. I have done it a few times without issue.

**Comment by seud0nym** [comment]
Maybe don't install tch-gui-unhide and see if the log messages re-occur?

**Comment by seud0nym** [comment]
I have just put up a release of tch-gui-unhide. `reset-to-factory-defaults-with-root` also now supports most options on the SMG3.

Please re-open if problem persists.
