### ISSUE TITLE
AdGuard "unknown unit "d" in duration "90d"

### ISSUE THREAD

**Issue by djgrazzy** [seud0nym/tch-gui-unhide#97]
I have ben enjoying tch-gui-unhide for a few years as a router and dumb AP/Booster and thoroughly appreciate all the work.
I grabbled another DJA0231 to play with specifically to give AdGuard a try.
First time logging and issue and not sure if AdGuard issue or script copying the current settings?

© Technicolor 2021 [tch-gui-unhide Release 2022.06.01 for Firmware 20.3.c.0389-MR20-RA (Egyptian Blue)]

"2022/06/10 19:53:43.739475 [error] parsing configuration file: unmarshaling duration: time: unknown unit "d" in duration "90d""

cmd run post error
root@DJA0231:~# cat /mnt/usb/USB-A1/AdGuardHome/AdGuardHome.yaml  | grep 90
  querylog_interval: 90d
  
 install log 
 root@DJA0231:~# curl -skL https://raw.githubusercontent.com/seud0nym/tch-gui-unhide/master/adguard/agh-setup | sh -s -- -e
[AdGuard-Home-Setup] Downloading latest version of update-ca-certificates...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2909  100  2909    0     0   7026      0 --:--:-- --:--:-- --:--:--  7009
[AdGuard-Home-Setup] Successfully downloaded update-ca-certificates.
[AdGuard-Home-Setup] Running update-ca-certificates...
rpc.gui.opkg: Downloading https://downloads.openwrt.org/releases/packages-22.03/arm_cortex-a9/base/ca-bundle_20211016-1_all.ipk...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  111k  100  111k    0     0  42585      0  0:00:02  0:00:02 --:--:-- 42585
rpc.gui.opkg: Package ca-bundle (20211016-1) installed in root is up to date.
rpc.gui.opkg: Downloading https://downloads.openwrt.org/releases/packages-22.03/arm_cortex-a9/base/ca-certificates_20211016-1_all.ipk...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  120k  100  120k    0     0  45899      0  0:00:02  0:00:02 --:--:-- 45882
rpc.gui.opkg: Package ca-certificates (20211016-1) installed in root is up to date.
rpc.gui.opkg: Updating ca-certificates.crt from https://curl.se/ca/cacert.pem if changed...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[AdGuard-Home-Setup] Downlading latest version of hijack-dns...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27031  100 27031    0     0  31763      0 --:--:-- --:--:-- --:--:-- 31726
[AdGuard-Home-Setup] Successfully downloaded hijack-dns.
[AdGuard-Home-Setup] Downloading latest release of AdGuard Home...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.0M  100 10.0M    0     0  2513k      0  0:00:04  0:00:04 --:--:-- 2513k
[AdGuard-Home-Setup] Disabling dnsmasq to free up RAM and port 53...
[AdGuard-Home-Setup] Configuring IPv4 WAN DNS...
[AdGuard-Home-Setup] Configuring IPv6 DNS...
[AdGuard-Home-Setup] Applying network changes...
[AdGuard-Home-Setup] Configuring dnsmasq...
[AdGuard-Home-Setup] dnsmasq disabled and stopped
[AdGuard-Home-Setup] Freeing port 443...
[AdGuard-Home-Setup] Reported Free RAM = 133440KB
[AdGuard-Home-Setup] Extracting IP addresses from current configuration...
[AdGuard-Home-Setup] Existing AdGuard Home configuration NOT overwritten
[AdGuard-Home-Setup] Checking AdGuard Home configuration...
2022/06/10 19:53:43.729604 [info] AdGuard Home, version v0.107.7
2022/06/10 19:53:43.739475 [error] parsing configuration file: unmarshaling duration: time: unknown unit "d" in duration "90d"
[AdGuard-Home-Setup] Configuration error? Restoring dnsmasq...
[AdGuard-Home-Setup] Configuring IPv4 WAN DNS...
[AdGuard-Home-Setup] Configuring IPv6 DNS...
[AdGuard-Home-Setup] Applying network changes...
[AdGuard-Home-Setup] Configuring dnsmasq...
Command failed: Not found
[AdGuard-Home-Setup] dnsmasq enabled and restarted
[AdGuard-Home-Setup] Re-allocating port 443 back to nginx...
[AdGuard-Home-Setup] Aborting...
root@DJA0231:~#

**Comment by seud0nym** [comment]
Well, that is annoying. I updated the set-up script to cater for changes in the latest version, and I missed that one. 

It needs all occurs of 90d to be replaced with 2160h.

I will change it as soon as I can.

**Comment by seud0nym** [comment]
I have pushed up a new version that contains the fix. Please give it a try and let me know how you go.

**Comment by djgrazzy** [comment]
Wow that was quick thanks. I'll likely have time to retest tomorrow afternoon will report back then.
Cheers

**Comment by seud0nym** [comment]
You may need to delete AdGuardHome.yaml if it already exists. The setup won't replace it if it is already there.

**Comment by djgrazzy** [comment]
> You may need to delete AdGuardHome.yaml if it already exists. The setup won't replace it if it is already there.

Noted thanks, I was intending on to delete all files first and also try a few different file formats (ext4 exfat) once/if successful with fat32.

**Comment by djgrazzy** [comment]
Can confirm install issue resolved(fat32), thanks legend. 

[AdGuard-Home-Setup] Done. You can now access AdGuard Home on http://192.168.0.1:8008
