### ISSUE TITLE
Configuring opkg for 20.3.c

### ISSUE THREAD

**Issue by ilium007** [seud0nym/tch-gui-unhide#98]
I am running Firmware Version 20.3.c.0389-MR20-RA on a Telstra Technicolor DJA0231. The opkg command below only shows 17,18,19. Should I be using -O 20 for v20 packages?

```
-o                    Configures opkg
-O 17|18|19           Overrides the default opkg repository with the specified version
```

If I try `-O 20` I get:

`ERROR: -O valid options are 17, 18 or 19`

**Comment by seud0nym** [comment]
No. There is no Homeware 20 package repository. Even the Homeware 19 repository is only in testing mode.

The Homeware 18 repository should work for must things on the 20.3.c. firmware. 

If you have a specific issue, _and_ the package exists in the Homeware 19 repository, then you could try it, but as I said, the repository maintainer advised me a while ago that it was only in testing.

**Comment by ilium007** [comment]
Ok, thanks.
